### ISSUE TITLE
D35E\icons\spells\school\con.png has an invalid file handle on Windows 10

### ISSUE THREAD

**Issue by adventuremagic123** [Rughalt/D35E#100]
It makes the D&D 3.5e game system awkward to deal with -- because we can't modify or delete that file due to the invalid file handle.

![Capture](https://user-images.githubusercontent.com/50708405/97389419-3a806f00-18a8-11eb-9d0f-a1d2cc446736.PNG)

![Capture2](https://user-images.githubusercontent.com/50708405/97389513-79162980-18a8-11eb-919a-4ae872839bdc.PNG)

**Comment by Rughalt** [comment]
This is because of that - https://docs.microsoft.com/pl-pl/windows/win32/fileio/naming-a-file#win32-file-namespaces - i will rename the file in next release
