### ISSUE TITLE
Deeper damage types implementations

### ISSUE THREAD

**Issue by Chemist94** [Rughalt/D35E#106]
Requires adding of new item type: damage types, which will have binary parameter: weapon damage or energy damage, and probably formula field for some specific house rules, like when DR ignores partially. There will be Damage Types compendium where DM may add new types presented in his campaign and they will be automatically added in the lists, which will allow to avoid misspelling.
![DR](https://user-images.githubusercontent.com/72754296/97873089-b287e280-1d49-11eb-91cc-d65827f3caca.png)

**Comment by Rughalt** [comment]
Proposition for Damage Item type fields
- Name, ex "Piercing or Slashing"
- Image
- Resistance Type: Energy Resistance, Damage Reduction 
   - Subtypes for Damage Reduction: Base Damage Type, Magic, Material, Alignment
       - Subfields for Material type: Enhancement alternative
   - Subtypes for Energy Resistance: None
- Type Identifier, ex "Piercing or Slashing"
- Type Identifier aliases, ex "P or S" (used for back compatibility with existing weapons and attacks)

Damage from weapons/attacks will be mapped to core item and type identifier and grouped into two categories and finally compared with Damage Reduction of defending creature:
- DR Affected (**DRA**), where the five parameters will be set: Base Damage type (slash/pierc/bludg), Magic/Epic (based on weapon Enhancement), Weapon/Attack Enhancement, Material (gathered from weapon/attack material), and Alignment (Holy/Good). These will be checked agains creature DR (**CDR**): 
    - If CDR base resistance type is not none and is not equal to DRA damage type, apply resistance
    - If CDR magic/epic resistance is not met by magic/epic DRA, apply resistance
    - If CDR material resistance is not met by DRA material *or* alternatively Weapon Enhancement, apply resistance
    - If CDR alignment resistance is not met by DRA alignment, apply resistance
    - If no resistance was applied in each of four previous steps apply full damage.
- Energy damage where each energy part will be checked agains element damage of attack/weapon

**Comment by Jan-Varenkamp** [comment]
Perhapse you are all ready have a solution but i don´t see here vulnerabilities. It doubels damage after DR. Then nobody forget to click twice aply damage.

**Comment by Rughalt** [comment]
Proposition for Damage Item type fields
- Name, ex "Piercing or Slashing"
- Image
- Damage Type: Energy, Base, Alignment
- Type Identifier, ex "Piercing or Slashing"
- Type Identifier aliases, ex "P or S" (used for back compatibility with existing weapons and attacks)

Proposition for Material Item type fields
- Name, ex "Iron"
- Image
- Enhancement alternative

Damage from weapons/attacks will be mapped to core item and type identifier and grouped into two categories and finally compared with Damage Reduction of defending creature:
- DR Affected (**DRA**), where the five parameters will be set: Base Damage type (slash/pierc/bludg), Magic/Epic (based on weapon Enhancement), Weapon/Attack Enhancement, Material (gathered from weapon/attack material), and Alignment (Holy/Good). These will be checked agains creature DR (**CDR**): 
    - If CDR base resistance type is not none and is not equal to DRA damage type, apply resistance
    - If CDR magic/epic resistance is not met by magic/epic DRA, apply resistance
    - If CDR material resistance is not met by DRA material *or* alternatively Weapon Enhancement, apply resistance
    - If CDR alignment resistance is not met by DRA alignment, apply resistance
    - If no resistance was applied in each of four previous steps apply full damage.
- Energy damage where each energy part will be checked agains element damage of attack/weapon
