### ISSUE TITLE
Modifiers from Changes tab to attack rolls aren't added to Attack bonuses fields

### ISSUE THREAD

**Issue by Chemist94** [Rughalt/D35E#117]
All, Melee, and Ranged, all three doesn't added
![image](https://user-images.githubusercontent.com/72754296/98351496-5970c500-204f-11eb-8a16-f77f7bcbba5b.png)

**Comment by Rughalt** [comment]
Issue is this is not added to the display on char sheet. They work on on attack roll

**Comment by Rughalt** [comment]
Fixed, will be released with 87.13
