### ISSUE TITLE
Elemental and Giant types missed in race details

### ISSUE THREAD

**Issue by Chemist94** [Rughalt/D35E#118]
![image](https://user-images.githubusercontent.com/72754296/98355801-3fd27c00-2055-11eb-827d-0648977e8d07.png)

**Comment by Chemist94** [comment]
Also, Elemental Racial HD have construct type and appropriate changes as if they had no Constitution score (but they have normal Constitution).

**Comment by Rughalt** [comment]
> Also, Elemental Racial HD have construct type and appropriate changes as if they had no Constitution score (but they have normal Constitution).

Probably a terrible copypaste error on my part
