### ISSUE TITLE
Implement a system for prestige class and feats requirements

### ISSUE THREAD

**Issue by red5h4d0w** [Rughalt/D35E#122]
The idea I have for that is that the system should warn users when they drop a item for which they do not meet the requirements for.
The idea would be to have an adjustable list similar to changes that can be evaluated (ex: BAB of +4 or higher) and contextual prerequisites that can't be evaluated (ex: Must have burned a creature for fun).
I think it should be a warning and not an obligation, because sometimes DMs bend the rules to best fit their campaign.

Here's an example of what this warning popup could say:
```html
<p>{character-name} doesn't meet the requirements for {name-of-item-drag-n-dropped}<br>
Requirements not met:
<ul>{list of requirements not met}</ul>
Do you still want to give {name-of-item-drag-n-dropped} to {character-name}? </p>
<button name="Yes">Yes</button><button name="No">No</button>
```

**Comment by Rughalt** [comment]
Added simple system for Feat (and other things, Classes for now) requirements. This system will be expanded in extended in subsequent updates.
