### ISSUE TITLE
Support for alternative class features and racial substitution levels.

### ISSUE THREAD

**Issue by omegaghost** [Rughalt/D35E#129]
That kind of feature is sure to be needed at some point. Alternative features replace particular default features. Some of them replace a whole list of things, some give you a list and you choose which ones you want to have. Pretty sure having support for the latter, that is replacing one feature at a time, is going to be enough.

Examples to look up:
Totem Barbarian, UEp48
Elf Ranger, RotWp155

P.S. There might be a similar thing for races somewhere but for now the only ones I can remember are actually feats anyways.

**Comment by Rughalt** [comment]
First UI iteration, with ability to disable default abilities, and add new from list for selected levels
![Example UI](https://media.discordapp.net/attachments/736890376727691345/779080784581492766/unknown.png)

**Comment by Jan-Varenkamp** [comment]
It looks reals helpful, my first sugestion were add D35E and World Class Abilities, some class Abilities are missing in D35E.
And it were nice if the insert method also for creation of new classes or races.

Why the Class Abilities are there twice?
In my opinion its ok if i only insert the level were the class abilitie shod be.

**Comment by Rughalt** [comment]
@Jan-Varenkamp these list only shows UI, data is currently a placeholder.

**Comment by Chemist94** [comment]
Would be better to drag and drop abilities in there, instead of choosing from full huge list.
