### ISSUE TITLE
SRD Monk issues

### ISSUE THREAD

**Issue by omegaghost** [Rughalt/D35E#130]
There is no mention of monk's unarmed damage progression.
Monk's bonus speed is included in changes, but it's set as competence bonus to land speed instead of enhancement bonus to speed, and isn't mentioned in progression.
AC formula in changes uses Wis mod at all time, but it should only be using it if it's positive.

**Comment by Rughalt** [comment]
Monk speed changed to Enhancement in 0.87.2. Unarmed progression is a part of #115.

**Comment by omegaghost** [comment]
My bad, I forgot they classes don't update outside of the main compendium.

**Comment by omegaghost** [comment]
Oh, I also forgot to mention that monk's AC formula uses wis mod, but it should only use it if it's positive, I'll update the ticket

**Comment by Rughalt** [comment]
Fixed, will be released with 87.13
