### ISSUE TITLE
Spells with no material components show an invalid component in chat message

### ISSUE THREAD

**Issue by agrtga** [Rughalt/D35E#135]
Spells that have no material component show an invalid component in the chat message when cast. The invalid component is "vial of holy water" in all the spells I tested.

<img width="471" alt="bad-component" src="https://user-images.githubusercontent.com/12749451/99325293-06172780-2844-11eb-912e-1a1e05d005b8.png">

**Comment by Rughalt** [comment]
This is because import template had this component. Will be fixed
