### ISSUE TITLE
Rapid Shot only adds an attack to the Full Attack option, meaning one cannot make use of it with BAB less than 6.

### ISSUE THREAD

**Issue by sextonmb** [Rughalt/D35E#136]
Would suggest it should add an extra attack to Single Attack when toggled.

**Comment by Rughalt** [comment]
Can you send the attack? I check if attacks has extra attack parts - like attacks with bab < 6 would and it should roll correctly.

> **How to send an item?**
> Sending item can greatly help with debugging on my side.
> - If item is owned by a character, drag and drop it to world item list.
> - Right click on item in browser item list and click export.
> - Attach downloaded item to this ticket.

**Comment by sextonmb** [comment]
I can't reproduce myself now. Previously hadn't been adding the extra attack on Single Attack option. Will mark this as Closed until/unless I see it reproduced in-game.
