### ISSUE TITLE
Nonlethal hp field triggers warnings since Foundry 0.7.6

### ISSUE THREAD

**Issue by sextonmb** [Rughalt/D35E#137]
![image](https://user-images.githubusercontent.com/1394366/99367194-8f187800-28b1-11eb-9185-5f8ec0474371.png)

**Comment by Rughalt** [comment]
Hi! I will need info on where you have used `@attributes.hp.nonlethal` or it just appeared by itself somewhere.

**Comment by sextonmb** [comment]
Aside from using the nonlethal hp damage field on the character sheet, I also used it in the following implementation of the Crusader ability Furious Counterstrike (by using the nonlethal hp damage field to track delayed damage):

`{
  "name": "Furious Counterstrike",
  "type": "feat",
  "data": {
    "description": {
      "value": "<p><strong>Furious Counterstrike (Ex)</strong>: You can channel the pain of your injuries into a boiling rage that lets you lash out at your enemies with renewed vigor and power. Each attack that strikes you only pushes you onward to greater glory. During your turn, you gain a bonus on attack rolls and damage rolls equal to the current value of your delayed damage pool (see steely resolve, above) divided by 5, and rounding down (minimum +1). You can only gain a maximum bonus on attack rolls and damage rolls of +6 from furious counterstrike. Use the table below to quickly determine the attack bonus and damage bonus from furious counterstrike, based on the amount of damage in your delayed damage pool. This ability?s benefits last until the end of your turn.</p>\n<p>&nbsp;</p>\n<table>\n<tbody>\n<tr>\n<th>Delayed Damage Pool Points</th>\n<th>Furious Counterstrike Bonus</th>\n</tr>\n<tr>\n<td>1-9</td>\n<td>+1</td>\n</tr>\n<tr>\n<td>10-14</td>\n<td>+2</td>\n</tr>\n<tr>\n<td>15-19</td>\n<td>+3</td>\n</tr>\n<tr>\n<td>20-24</td>\n<td>+4</td>\n</tr>\n<tr>\n<td>25-29</td>\n<td>+5</td>\n</tr>\n<tr>\n<td>30+</td>\n<td>+6&nbsp;</td>\n</tr>\n</tbody>\n</table>",
      "chat": "",
      "unidentified": ""
    },
    "nameFormula": "",
    "nameFromFormula": false,
    "tags": [],
    "uniqueId": "",
    "source": "",
    "classSource": "",
    "userNonRemovable": false,
    "customAttributes": {},
    "customAttributesLocked": false,
    "activation": {
      "cost": 1,
      "type": ""
    },
    "duration": {
      "value": null,
      "units": ""
    },
    "target": {
      "value": ""
    },
    "range": {
      "value": null,
      "units": "",
      "long": null
    },
    "uses": {
      "value": 0,
      "max": 0,
      "per": null,
      "autoDeductCharges": true,
      "allowMultipleUses": false,
      "chargesPerUse": 1,
      "maxFormula": ""
    },
    "measureTemplate": {
      "type": "",
      "size": 0,
      "overrideColor": false,
      "customColor": "",
      "overrideTexture": false,
      "customTexture": ""
    },
    "actionType": "",
    "attackBonus": "",
    "critConfirmBonus": "",
    "damage": {
      "parts": []
    },
    "attackParts": [],
    "formula": "",
    "ability": {
      "attack": null,
      "damage": null,
      "damageMult": 1,
      "critRange": 20,
      "critMult": 2,
      "twoHandedOnly": false,
      "vsTouchAc": false
    },
    "save": {
      "dc": 0,
      "description": ""
    },
    "effectNotes": "",
    "attackNotes": "",
    "specialActions": [],
    "changes": [
      [
        "min(@attributes.hp.nonlethal*1000, max(1,floor(@attributes.hp.nonlethal/5)))",
        "attack",
        "attack",
        "untyped",
        0
      ],
      [
        "min(@attributes.hp.nonlethal*1000, max(1,floor(@attributes.hp.nonlethal/5)))",
        "damage",
        "damage",
        "untyped",
        0
      ]
    ],
    "changeFlags": {
      "loseDexToAC": false,
      "noStr": false,
      "noDex": false,
      "oneInt": false,
      "oneWis": false,
      "oneCha": false,
      "noEncumbrance": false,
      "mediumArmorFullSpeed": false,
      "heavyArmorFullSpeed": false,
      "uncannyDodge": false
    },
    "conditionFlags": {
      "dazzled": false,
      "wildshaped": false,
      "polymorphed": false
    },
    "combatChanges": [],
    "sizeOverride": "",
    "counterName": "",
    "contextNotes": [],
    "featType": "classFeat",
    "associations": {
      "classes": []
    },
    "crOffset": "",
    "recharge": {
      "value": null,
      "charged": false,
      "_deprecated": true
    },
    "showInQuickbar": false,
    "links": {
      "charges": []
    },
    "attack": {
      "parts": []
    }
  },
  "sort": 400000,
  "flags": {
    "exportSource": {
      "world": "way-of-the-wicked",
      "system": "D35E",
      "coreVersion": "0.7.7",
      "systemVersion": "0.87.4"
    }
  },
  "img": "systems/pf1/icons/feats/great-cleave.jpg",
  "effects": [],
  "_id": "u6tye3NN6Z0Di2jc",
  "custom": {}
}`
