### ISSUE TITLE
Inventory Grouping

### ISSUE THREAD

**Issue by Axecleft** [Rughalt/D35E#149]
There is no way to group/stack similar items in Inventory. 
If you have multiples of the same item in inventory you have to edit the quantity of one to include the full amount and form a stack, then delete all others.

**Comment by Rughalt** [comment]
Will be added in 0.90
![2021-02-27 12 41 17](https://user-images.githubusercontent.com/802214/109386229-a0820f00-78f9-11eb-95fe-af1430084f10.gif)
