### ISSUE TITLE
Ammo Tracking

### ISSUE THREAD

**Issue by Axecleft** [Rughalt/D35E#155]
Could we have the ammo being used appended to the name of ranged weapons? Similar to the Enchanted item auto update naming.

for example:
 Longbow +1 using Arrows +1 would get renamed "Longbow +1 (Arrow +1)"

Shortbow using Flaming Burst Arrows would get renamed "Shortbow, (Arrow, Flaming Burst)"

**Comment by Rughalt** [comment]
I think this is unnecessary as proper ammunition system is implemented and ammo can be selected on the fly.
