### ISSUE TITLE
Make ammunition show in Ammunition tab even when in container

### ISSUE THREAD

**Issue by agrtga** [Rughalt/D35E#158]
I have containers for my players for ammunition like arrows, bolts, skip rocks. When in a container the ammunition doesn't show up in the Ammunition tab. (This is true of anything that is in a container.) This is particularly problematic because of the issue where the container contents don't show a quantity.

**Comment by Rughalt** [comment]
I deem this obsolete after inventory screen rework. Reopen if needed.

**Comment by agrtga** [comment]
> I deem this obsolete after inventory screen rework. Reopen if needed.

I agree it's obsolete based on the reason noted when I opened this. It could be valuable if you hadn't automated ammunition consumption on attacks, because once in a container the ammunition quantity isn't easy to update. My players have been enjoying the automation so I have no skin in it.
