### ISSUE TITLE
Notes in skill check rolls in the chat not working

### ISSUE THREAD

**Issue by jpbsheppard** [Rughalt/D35E#160]
To recreate:
Open a char sheet of a character with a skill with a note e.g. Concentration
Click on Concentration to do a roll
Click on Normal in the roll window

Effect:
Roll in chat window appears with duplicated note in the chat

![image](https://user-images.githubusercontent.com/19222967/101466481-1b5e0e00-3939-11eb-81cd-cdd6bf47112b.png)

Clicking on this note to do the extra roll does not do anything, mix of ux and implementation 

![image](https://user-images.githubusercontent.com/19222967/101466926-97f0ec80-3939-11eb-852c-79a89051bdd5.png)

[fvtt-Actor-Duerdin.zip](https://github.com/Rughalt/D35E/files/5658349/fvtt-Actor-Duerdin.zip)

**Comment by Rughalt** [comment]
I need more info:
1. What version of system? (0.87.7 or beta of 0.87.8)
2. Was the note set directly on the char sheet?
3. How does the note look itself?

**Comment by jpbsheppard** [comment]
1. 0.87.6 (latest current according to Foundry)
2. Haven't touched the compendium or added a note at all. Was there when I installed it
3. I havent set any notes.
![image](https://user-images.githubusercontent.com/19222967/101467705-91af4000-393a-11eb-99a8-cb0369f2f495.png)

**Comment by Rughalt** [comment]
I will need exported actor then to check what has happened.

**Comment by jpbsheppard** [comment]
in the first comment, zipped

**Comment by Rughalt** [comment]
You have to combat casting feats, what have *static* notes (they appear clickable but are not - its how Foundry notes work).  Notes appear twice because you have feat twice.

**Comment by jpbsheppard** [comment]
ahh cool
