### ISSUE TITLE
Bard Class Missing Class Features

### ISSUE THREAD

**Issue by jpbsheppard** [Rughalt/D35E#161]
Version 0.87.6

Bard is missing a lot of class features
![image](https://user-images.githubusercontent.com/19222967/101541975-04033d00-399a-11eb-8298-2e54031bed9c.png)

![image](https://user-images.githubusercontent.com/19222967/101542468-b2a77d80-399a-11eb-9217-cb656fb67da5.png)

Looks like these feats are not present at all in the compendium

**Comment by Rughalt** [comment]
These should be all part of bardic music ability and when bardic music is used, should produce correct buttons on chat card.

**Comment by jpbsheppard** [comment]
Just get on a lvl 7 bard
![image](https://user-images.githubusercontent.com/19222967/101554388-7251fa80-39ae-11eb-83a6-1ed4273a9084.png)

Should in theory also get 
countersong, fascinate, inspire confidence and suggestion

Bardic knowledge should be called out as a separate ability really although probably would be a bit pointless to automate as its a roll against a small table

**Comment by jpbsheppard** [comment]
the inspire courage button doesnt seem to do anything

**Comment by jpbsheppard** [comment]
scratch that figured it out its just not obvious how it works

**Comment by Rughalt** [comment]
I am closing this as now all features are displayed under the class and some missing bardic features were implemented (Bardic Knowledge roll). Reopen if needed.
