### ISSUE TITLE
Hide Apply Damage button on all the things from players

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#164]
Hi

Would it be possible to toggle or hide the apply damage button from the items in chat as if a player sees a button they want to press it and for them it is a bit pointless

![image](https://user-images.githubusercontent.com/22633854/102491146-b2c50e80-4067-11eb-906f-6e3b73d0e1dd.png)

Same for apply crit damage as well

**Comment by Rughalt** [comment]
This will make this button less prone to user clicking and getting "No Permission" message
