### ISSUE TITLE
Compendium Browser trogth uncaught exeption

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#174]
Compendium Browser trogth uncaught exeption but opens more or les normal.

![](https://cdn.discordapp.com/attachments/736890349695401998/789870873728909333/unknown.png)

![](https://cdn.discordapp.com/attachments/736890349695401998/789871838662623302/unknown.png)

**Comment by Rughalt** [comment]
These seems file system errors. I cannot reproduce them at all on Linux and macOS. If issue persist, please reopen the ticket.
