### ISSUE TITLE
Skills not correctly taking into account attribute scores for cross class skills

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#177]
Cross class skills are not calculated correctly and are adding half their score instead of the full score

![image](https://user-images.githubusercontent.com/22633854/102727099-9224df00-431b-11eb-972c-0988453131d7.png)
e.g. here it should be adding +6 for tumble but its only adding +3

0.87.11
[fvtt-Actor-Kurt_Vexallis.zip](https://github.com/Rughalt/D35E/files/5721674/fvtt-Actor-Kurt_Vexallis.zip)

**Comment by RalfvdEnden** [comment]
This hasn't actually been fixed, right ? What happens is you buy cross-class skills at 2 point per rank and then the sheet calculates cross-class skills by dividing the number of ranks (which cost double) by 2. This makes them twice as expensive.

**Comment by RvdE** [comment]
N/m. Works now. My apologies.
