### ISSUE TITLE
Bonus Point Formula on Skill tab doesn't reference sheet attributes

### ISSUE THREAD

**Issue by bigsexy420** [Rughalt/D35E#18]
Not sure if this is a bug or a feature request, the Bonus Point Formula doesn't reference @details.level.value or @attributes.hd.total for calculating Skill points.

![image](https://user-images.githubusercontent.com/1043352/89702842-34f33880-d8fa-11ea-90ca-8f960d5c6a70.png)

![image](https://user-images.githubusercontent.com/1043352/89702828-1d1bb480-d8fa-11ea-9890-a07f9ce8f1ea.png)

**Comment by Rughalt** [comment]
This seems to be bug in Foundry itself, as `4+((@details.level.value)-1)` works as it should (params are passed to `Roll` instance)
