### ISSUE TITLE
Feat labels are coming up in the defence dialog box for the attacker when the feats are on the defender

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#180]
If you have a feat that gives an unconditioned bonus e.g.
![image](https://user-images.githubusercontent.com/22633854/102727732-673c8a00-431f-11eb-801f-b75d9c1050a8.png)

This feat adds 2 to the attack bonus and the damage bonus

When this player is attacked and you select it to take damage, the labels show up
![label in damage](https://user-images.githubusercontent.com/22633854/102727869-66582800-4320-11eb-900c-ea57815ebe6c.gif)

**Comment by Rughalt** [comment]
This is correct behavior, as where the dialog appears is dependent on unfortunately named field "Item Type" which describes *action* type. Naming will be fixed in 0.87.12. To make these feats not appear, set Item Type to attack or Attack Optional (All should be rarely used).
