### ISSUE TITLE
Adding two bonuses from the same feat adds a label and a selector that does nothing to the attack dialog 

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#181]
0.87.11

If you have a feat with more than one bonus to changes
![image](https://user-images.githubusercontent.com/22633854/102728101-c4d1d600-4321-11eb-972c-def91d9c0545.png)
![image](https://user-images.githubusercontent.com/22633854/102728109-cdc2a780-4321-11eb-87a2-892d2191bf6c.png)
[fvtt-Item-Melee_Weapon_Mastery_(Slashing).zip](https://github.com/Rughalt/D35E/files/5721736/fvtt-Item-Melee_Weapon_Mastery_.Slashing.zip)

It gets added as a secondary line with checkbox in the attack dialog
![image](https://user-images.githubusercontent.com/22633854/102727974-1e85d080-4321-11eb-962c-43645aad73f3.png)

**Comment by Straddlecat** [comment]
[fvtt-Actor-Bluebeard.zip](https://github.com/Rughalt/D35E/files/5721738/fvtt-Actor-Bluebeard.zip)

**Comment by Rughalt** [comment]
This is because of usage of "All"/"All" in combat changes. It does not work great, as the change (change is applied as a whole) is both optional and non-optional - and system does not know what to do. Its best to set area that change applies to.
