### ISSUE TITLE
Creating attacks from Unidentified Weapons

### ISSUE THREAD

**Issue by Eldintux** [Rughalt/D35E#189]
Would it be possible to create an attack using the 'Unidentified Name' for both the name of the attack & the 'Created from' fields so that players can't see any 'special' names before they have identified an item. It would also be useful if the this attack used the 'Unidentified Details' too.

Many thanks

**Comment by Rughalt** [comment]
How would you like it to deal with enhancements? My current fix for this does not move them to attack, as well as it does not move enhancement bonus.
