### ISSUE TITLE
Set buff "x" field data.level to random Value

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#191]
It were sometimes helpfull if its possible to get a random value in to a special action.

I see two options.
First make the roll value accessible.
![image](https://user-images.githubusercontent.com/64524134/103211171-c09c4e80-4907-11eb-979d-649f43564242.png)

Second make that rolls funtion in the 'Set buff "x" field data.level to .... ' command.
I find out roll(1dx) function but the animation for the roll ist missing.

**Comment by Rughalt** [comment]
`animation for the roll` if you mean that Dice so Nice! rolls are missing this is because this would need deeper integration in this place (this is made as hidden roll, which is not automatically rolled by Dice so Nice!

**Comment by Jan-Varenkamp** [comment]
yes

And that it was not possible to get rnd value from chatcard in to the special action. Like Player cast Heroes Feast witch gives 1d8+cl/2 tmp HP, so Chatcard shows the result of the roll and the resold is used by special action for the set commando.

And the @useAmount value is also not reachable, it were in some constellation it were helpful if the player can chose how strong the buff get because the buff have a downside like the defending enchantment. Wich i tried to build with a buff.

this Issue is connected with issue https://github.com/Rughalt/D35E/issues/187

**Comment by Rughalt** [comment]
You will be able to use following placeholders in specialActions from 0.87.13
`(@useAmount)` - this is use amount from the Attack Dialog
`(@attack)` - this is total Attack roll value
`(@damage)` - this is total Damage roll value

With these, dice will be rolled once so DsN! integration at this level is not needed.
