### ISSUE TITLE
Bonus Hp calculation 

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#193]
Bonus HP calculation of some classes are broken if they get a Con buff.
Druide and Barbarian seems to by ok. 
![image](https://user-images.githubusercontent.com/64524134/103239633-77bbb880-494e-11eb-8052-f13200470b02.png)

![image](https://user-images.githubusercontent.com/64524134/103239759-cf5a2400-494e-11eb-82c3-b32b8cd5bc4b.png)

**Comment by Rughalt** [comment]
Bug was due to duplicate bonuses applied to origTotal field of ability. Fixed, will b out in 87.12
