### ISSUE TITLE
Untrained Skills on Summary

### ISSUE THREAD

**Issue by st3nd02** [Rughalt/D35E#196]
I was thinking that it would be a good idea to have the untrained skills that do not require training such as Search, spot, listen etc. to be displayed on Summary for easier rolls. Furthermore it would be good it you had some king of control (like a toggle) to select which appear there so to avoid clutter.

**Comment by Rughalt** [comment]
0.88 will contain an option to enable display (per character) of skills that do not require training on summary. Full selection of which skills will be displayed there will come later, as UI is not trivial and required additional per-skill value with 4 settings per skill (always/if untrained/if ranks/never). If I find a good way to implement this it will be added.
