### ISSUE TITLE
Apply half Damage and the Chatcard

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#199]
If a playeruse Apply Damage with override (apply half Damage) the createt chat cart shows full damage not half but the char loss correctly only half damage.

![](https://cdn.discordapp.com/attachments/736890349695401998/794907415854317618/unknown.png)

![](https://cdn.discordapp.com/attachments/736890349695401998/794907490696691723/unknown.png)

Koko lost 11 HP is correct but Chatcard say 22
It were nice if the Chatcard say 11 may be because of apply half.

**Comment by Rughalt** [comment]
Applied will show correct damage applied to an actor. Will be out with 0.87.13
