### ISSUE TITLE
Ability damage modifications apply correct carry weight ranges, but it does not apply related maluses until you modify the inventory

### ISSUE THREAD

**Issue by santalucial** [Rughalt/D35E#200]
Although it does show correct carry weight ranges, it does not apply related maluses until you modify the inventory by adding/removing something, it also seems that the heavy load PCA is the same as medium load, -3 while it should be -6

_Originally posted by @santalucial in https://github.com/Rughalt/D35E/issues/176#issuecomment-753470700_

**Comment by santalucial** [comment]
[fvtt-Actor-Jollito.zip](https://github.com/Rughalt/D35E/files/5761388/fvtt-Actor-Jollito.zip)

**Comment by Rughalt** [comment]
Moved weight-based ACP code to places *before* calculations. Should fix. Will be out in 0.87.13
