### ISSUE TITLE
HP reg and Buff lost while rest 

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#201]
The calculation of resting have to be changed, at moment the resting heal comes first and then the recalculation if a Con buff runs out, the result is then old HP - lost HP from out ran Con Buff. It should be Old HP + Rest reg - Lost HP from out ran buff. For a little moment it shows the HP regain.

![image](https://user-images.githubusercontent.com/64524134/103457904-5880aa80-4d03-11eb-9a2e-308e13f03247.png)
 
 for a littel moment it shows 109 HP and then
 
![image](https://user-images.githubusercontent.com/64524134/103457913-70f0c500-4d03-11eb-820b-428006af78a1.png)

**Comment by Rughalt** [comment]
Moved order around, will be fixed in 87.13
