### ISSUE TITLE
Change System AC Bonus

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#202]
I miss a AC bonus Class for AC and Touch or only AC.
The existing classes are:
Generic: AC, Touch, Flat
Armor: AC, Flat
Shield:  AC, Flat
Natural: AC, Flat
Touch: Touch

missing:
Dodge like: AC, Touch (If you loss Dex bonus to AC then this bonus are also lost to AC)

**Comment by Rughalt** [comment]
Added pure AC bonus, to add Dodge like AC use change type "Dodge" like in the image
![image](https://user-images.githubusercontent.com/802214/104359511-0bc17e80-5510-11eb-9a2f-936f35ccd53f.png)
