### ISSUE TITLE
Monsters Missing/Wrong

### ISSUE THREAD

**Issue by krlsrrll** [Rughalt/D35E#204]
After latest update Lacedon no longer in the bestiary

Should be Ghoul with aquatic

**Comment by st3nd02** [comment]
Ogres and Ogre Magi type is Giant 
![image](https://user-images.githubusercontent.com/67288581/103487760-6b34d580-4e10-11eb-9f14-b09a824f121a.png)

**Comment by st3nd02** [comment]
Giant Octopus (Animal) has an image of a humanoid giant. Also has no vision distance at all (is is set to 0)

**Comment by Rughalt** [comment]
> Giant Octopus (Animal) has an image of a humanoid giant. Also has no vision distance at all (is is set to 0)

Fixed, will be out in 0.88

**Comment by Rughalt** [comment]
All monsters in this ticket are fixed. Please report monsters with broken statblocks in a new ticket.
