### ISSUE TITLE
Shield AC bonus from feat being added when no shield equipped

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#205]
If you add a feat e.g. shield specialisation which adds +1 bonus to AC from shields

![image](https://user-images.githubusercontent.com/22633854/103466787-fa25ed00-4d3f-11eb-84b5-80c140b689db.png)

When you dont have a shield equipped it is still being counted

![image](https://user-images.githubusercontent.com/22633854/103466804-1b86d900-4d40-11eb-952d-e9d70a50f14c.png)

**Comment by Rughalt** [comment]
I looked around and it seems this was initially *not* designed for this (this is still from PF1 code). This is more to add AC for spells like [Shield](http://www.d20srd.org/srd/spells/shield.htm) which explicitly add *Shield* AC. For things like Shield Specialization, Combat change with proper condition may be better - so new field will be introduced in 0.88
`@shieldType` which can be either `none`, `lightShield`, `heavyShield`, `towerShield` or `other` depending on equipped shield type
