### ISSUE TITLE
Spell Browser not showing spells allocated to new spell caster class

### ISSUE THREAD

**Issue by dwayne26120** [Rughalt/D35E#207]
I have created a new spell caster class (eg shaman), I have duplicated the spell compendium and modified each spell allocated to shaman class (by changing caster level attibute as follows)
![spellcastclass](https://user-images.githubusercontent.com/39880134/103480817-d661b600-4dd6-11eb-80b2-b77113f6dd13.png)
however, when I use Browse spell, I see no shaman spell when filtering. I need to delete the Spell file of compendium to see it.
![spellbrowserempty](https://user-images.githubusercontent.com/39880134/103480838-0dd06280-4dd7-11eb-8bbf-7268c22b0954.png)
After deleting system 3.5 spell file:
![spellbrowserempty](https://user-images.githubusercontent.com/39880134/103480856-348e9900-4dd7-11eb-83fe-152340e7a11c.png)

**Comment by Rughalt** [comment]
I cannot reproduce it. I added new compendium for spells with spell for new class and could select it. I will need more details: does it happen after reloading the app, etc.
