### ISSUE TITLE
Arcane Trickster Prestige Class issues

### ISSUE THREAD

**Issue by st3nd02** [Rughalt/D35E#209]
The Arcane Trickster prestige class has several issues.
1) No class skills are selected in the settings
2) HD should be d4
3) This message keeps appearing.
![image](https://user-images.githubusercontent.com/67288581/103483489-44ff3d80-4df0-11eb-9bb1-07c826bf2e38.png)

**Comment by Rughalt** [comment]
Fixed with the help of @st3nd02! Will be out with 87.13
