### ISSUE TITLE
sizeRoll() given static value instead variable when creating an attack

### ISSUE THREAD

**Issue by bigsexy420** [Rughalt/D35E#21]
When creating an attack from a weapon item sizeRoll() is passed a 0 value (medium) instead of the @size variable. Not sure if this is intended.

![image](https://user-images.githubusercontent.com/1043352/89703221-7a653500-d8fd-11ea-87c0-0b2129e78346.png)

**Comment by Rughalt** [comment]
If option "Autosize weapon" is selected attacks from weapons will be created with `@size` modifier
