### ISSUE TITLE
Request: Show all dice rolls from all sources on damage

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#210]
It would be nice to see all the dice rolls for all sources of damage in the attack card 

![image](https://user-images.githubusercontent.com/22633854/103527833-de733180-4e7a-11eb-8263-bfaca06fa70d.png)
This attack supposedly contains 4d6 additional damage from a feat but its hard to tell as you cant see the dice rolls.  It would be nice to see all number breakdowns rather than a total e.g. instead of 1*12 you get the 4d6 expanded dice rolls plus the +1 from point blank shot and +4 from favoured enemy

**Comment by Straddlecat** [comment]
0.87.13

**Comment by Rughalt** [comment]
To not break existing behaviour, this will be done as follows:
- Existing bonuses that were lumped in attack/damage/ST rolls will be still lumped *however* where possible there will be a list below with information what user selected
- For new things new fields will be introduced that allow normal exploded behavior for rolls. Examples will be in docs on site and included in the system.

**Comment by Rughalt** [comment]
Example with exploded damage roll from new fields
![image](https://user-images.githubusercontent.com/802214/104092275-39de5e80-5283-11eb-9ced-d2174ada3320.png)
