### ISSUE TITLE
Request: More info on what a player chose during his attack roll and damage roll

### ISSUE THREAD

**Issue by st3nd02** [Rughalt/D35E#214]
If I may make a suggestion. When the player has such control of his rolls it would be great for us DMs to have a clear view of what he chose on the roll. For example lets say the player opted to use 4 points of power attack.

![image](https://user-images.githubusercontent.com/67288581/103570627-207b9200-4ed2-11eb-9665-c6391c91c979.png)

the roll says -4 but we don't have a clear view of what he chose. If it was possible it would be good to have a summary of the choice under the attack. Perhaps on effect notes like "Effect notes: Power Attack 4, Sneak Attack etc."

**Comment by Rughalt** [comment]
Added where possible, will be out in 0.88
![image](https://user-images.githubusercontent.com/802214/104091611-c76b7f80-527e-11eb-9fe4-4288bc86ac87.png)
![image](https://user-images.githubusercontent.com/802214/104091622-cd616080-527e-11eb-9e88-5eb1a0723028.png)
