### ISSUE TITLE
Confusing close tab on Add Item dialog

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#217]
![image](https://user-images.githubusercontent.com/22633854/103632453-3a51bf00-4f3c-11eb-93d9-38fc991f70d8.png)
Could it be possible to change the location of this close tab to be top right more in line with standard UX or move this dialog down as it catches a lot of people out

**Comment by Rughalt** [comment]
Changed to this, as "slideout tabbed" interface is indeed not used anywhere else in the system

![image](https://user-images.githubusercontent.com/802214/104366963-6a8bf580-551a-11eb-80ea-9220dd165965.png)
