### ISSUE TITLE
Working Metamagic Rods

### ISSUE THREAD

**Issue by st3nd02** [Rughalt/D35E#222]
Metamagic rods (and some other magic items) modify casting time, duration, damage etc. There should be implementation that modifies the spell stats in general and not in a spell by spell basis (by making a buff). Preferably by using the rod and then choosing a spell and that becomes modified for its next cast.

**Comment by Rughalt** [comment]
This can probably be all sone now with Spell Combat Changes and introduction of new Metamagic related setting for spells. Reopen if needed.
