### ISSUE TITLE
Saving Throws

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#225]
The new Saving Throw card has no title, so if the player take saving throw from Char sheet it´s unclear which one he has taken, it miss how the result was built (roll, bonuses) and the context notes are no longer shown that is a problem because many situation bonuses are written in  context notes +x to charm effects ....

**Comment by Rughalt** [comment]
Effect notes should be converted to Combat Changes for saving throws, however as a stop gap I will add this information to items so you remember and display ST notes.
