### ISSUE TITLE
Undead Fixes

### ISSUE THREAD

**Issue by st3nd02** [Rughalt/D35E#226]
1) Undeadhave Immunity to any effect that requires a Fortitude save (unless the effect also works on objects or is harmless).
2) If they have to roll a FOR they use CHA mod instead of CON
3) They use CHA mod for concentration rolls.

**Comment by Straddlecat** [comment]
Their con is also null rather than 0 or any value.

**Comment by Rughalt** [comment]
Con will be 0 as this is technical limitation of the system.

**Comment by Rughalt** [comment]
0.88.0 will update Racial HD, but it will be replaced with future 0.88.X updates.

**Comment by Rughalt** [comment]
Except for 1st one, which is mostly descriptive and things are not automated, rest is fixed and will be out in 0.91
