### ISSUE TITLE
Update from Enhancements button doesnt work

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#227]
![image](https://user-images.githubusercontent.com/22633854/103781473-5170d980-502e-11eb-90ac-5e6bd24a51df.png)
Not sure if this button is supposed to open up the Enhancements list but currently doesn't do anything

**Comment by Straddlecat** [comment]
0.87.15

**Comment by Rughalt** [comment]
This updates Name and Price, will be named differently

**Comment by Rughalt** [comment]
Button label changed to `Update Name and Price`
