### ISSUE TITLE
Missing Spells

### ISSUE THREAD

**Issue by st3nd02** [Rughalt/D35E#230]
1) Ray of Frost has only Wizard 0 in tags. Needs Sorcerer 0 too (Edit: Actually there are two instances of Ray of Frost, one correct S0/W0 and one Wizard 0 only). Both are set to Spell Effects: Other (while they should be Ranged Spell Attack) and missing damage.
2) Lightning Bolt has only Wizard 3 in tags (missing Sorcerer 3). Also it is set to Spell Effects: Other with no damage set. Also the Template is set to circle and not to Line.
3) Vampiric Touch has only Wizard 3 in tags (missing Sorcerer 3). Also Spell Effects are set to Other (should be melee touch attack) and misses damage.
4) Scorching Ray: as above (3) but Wizard 2.

**Comment by Rughalt** [comment]
Sorcerer class will be fixed as part of #311 , spell effect are ongoing work.
