### ISSUE TITLE
Closed Char sheet, buffs and combat tracker

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#232]
If a charsheet is closed and the char has a buff then comes in consol a error after one round:
![image](https://user-images.githubusercontent.com/64524134/103815939-69fbe680-5064-11eb-88b7-a2536cdb179b.png)

First round the buf didn´t appear.
If the Bug appear than buffs are not decremented the time left because Elapsed time didn´t increment.

**Comment by Rughalt** [comment]
Fixed it along other improvements with `updateCombat` hook
