### ISSUE TITLE
Vulnerability of class features

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#234]
Class features are more vulnerable to subsequent changes than attacks of the class abilities type.

If a Class Ability has limited uses which are calculated by using a formula, this can be changed afterwards (the copy of the item that the character has embedded).

If a class feature has limited uses which are calculated using a formula, this should not be changed afterwards. Since the Update Item Routine which is called by the Combat Tracker is then confused. It can happen that he gets into an infinity loop in which he alternates the original formula and the new entered formula and therefore no longer ends. This creates so much load on the event dealer that the Foundry hardly reacts (several seconds delay).

It would be nice if the subsequent customization of the class features would also be possible, similar to the Class Ability type attacks.

https://user-images.githubusercontent.com/64524134/103830835-90794c00-507b-11eb-88ae-0fee43947304.mp4

**Comment by Rughalt** [comment]
Removed this from 0.88.0 as this requires deeper dive and possibly more info (does it happen for more people etc)

**Comment by Rughalt** [comment]
As this is an old tickets, please reopen if it happens again.
