### ISSUE TITLE
Token Action Hud not displaying spells from spontaneous class when mixed with prepared class

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#235]
When you have a spontaneous and prepared spell class as primary and secondary spell classes the spontaneous or first one you set isnt appearing in the TAH
[fvtt-Actor-duskblade_mage.zip](https://github.com/Rughalt/D35E/files/5781383/fvtt-Actor-duskblade_mage.zip)

[fvtt-Actor-sorc_wiz.zip](https://github.com/Rughalt/D35E/files/5781385/fvtt-Actor-sorc_wiz.zip)

0.87.15

**Comment by Rughalt** [comment]
This requires a PR to TAH.

**Comment by Straddlecat** [comment]
This is affecting bard as well

**Comment by Rughalt** [comment]
Fixed - spontaneous spells will now display correctly. Will be pushed in a PR.
