### ISSUE TITLE
Request: Show in TAH which buffs are active and which arent by highlighting the button

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#242]
Whenever a buff is cast on a player it shows up in the TAH and on token right click but then persists in TAH even when not active. Would be nice to show highlight around the button edge or a check mark so show which buffs are active

**Comment by Rughalt** [comment]
This will be fixed with next release of 3.5e SRD (system styling side error).

**Comment by Rughalt** [comment]
![image](https://user-images.githubusercontent.com/802214/115146257-fd768780-a055-11eb-8dc9-f487da866a5c.png)
