### ISSUE TITLE
Add items dialog adds wrong item if you use the search

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#244]
Add items dialog adds wrong item if you use the search and do not scroll or interact with the dialog box before clicking add
![additem](https://user-images.githubusercontent.com/22633854/104030086-c07f3700-51c2-11eb-9f16-ef593475e0e9.gif)

It looks like if you dont interact with the dialog after the search it doesnt find the right place in the list and so doesnt add the item you want but adds in the item that was there before

**Comment by Straddlecat** [comment]
0.87.15

**Comment by Straddlecat** [comment]
The click resets the list THEN adds the item so then adds the incorrect item

**Comment by Rughalt** [comment]
Caused by not overriding default foundry binding for `change` event of inputs.
