### ISSUE TITLE
Missing Italian localization

### ISSUE THREAD

**Issue by elfosardo** [Rughalt/D35E#250]
I play with some Italian friends and would be nice to have it.
I've been working on it in #243

**Comment by elfosardo** [comment]
I found a better way to deal with the localization using babele module https://gitlab.com/riccisi/foundryvtt-babele/-/tree/master/
I've already created the module and the test looks good https://github.com/elfosardo/foundryvtt-dnd35e-lang-it-it

**Comment by Rughalt** [comment]
I will close this then, as this really is a better way to make translations!
