### ISSUE TITLE
Level Drain doesnt work

### ISSUE THREAD

**Issue by st3nd02** [Rughalt/D35E#257]
I created a test character and gave him 5 levels of cleric (I increased STR on 4th). Then I gave him 2 levels of drain. I do not see any changes on BAB, STR etc.
![image](https://user-images.githubusercontent.com/67288581/104620014-2d00a700-5697-11eb-983e-091b5c6a8762.png)

![image](https://user-images.githubusercontent.com/67288581/104620071-3e49b380-5697-11eb-8c67-f2bd2e742bb6.png)

**Comment by Rughalt** [comment]
Level drain is not shown in the boxes, but it is taken into account in rolls
