### ISSUE TITLE
Beta#1 Apply Damage/ Special Action

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#260]
Player can´t use apply Damage and special action out of there turn, but they have to use it if they get attacked by a monster or get a buff from a different player.

![image](https://user-images.githubusercontent.com/64524134/104726401-d1382b80-5733-11eb-97bd-9e8bcf9c6704.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.88.0
