### ISSUE TITLE
Beta#1 Save Throws with out animation

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#261]
The Saving Throws started from the Summary have no roll animation from Dice so nice.

![image](https://user-images.githubusercontent.com/64524134/104727632-f332ad80-5735-11eb-830e-ad06c176ccc5.png)

Saving Throws from Combat also have no animation
![image](https://user-images.githubusercontent.com/64524134/104727712-15c4c680-5736-11eb-9692-3ea57566b373.png)

Saving Throws from Chatcards have no animation
![image](https://user-images.githubusercontent.com/64524134/104728141-bfa45300-5736-11eb-9760-53b6fdde8862.png)

**Comment by Rughalt** [comment]
Fixed, wil be out in next beta/release
