### ISSUE TITLE
Limiting Spells Known

### ISSUE THREAD

**Issue by st3nd02** [Rughalt/D35E#262]
sorcerers, bards and other similar type classes have a limited number of spells known. The system currently is open. Make a toggle feature to restrict spells known to such classes.

**Comment by Rughalt** [comment]
Limit wont be strictly enforced, but will show up in red that number of spells known is over limit. Will be released in 0.89.

![image](https://user-images.githubusercontent.com/802214/106381914-48b8bc80-63bc-11eb-8a0c-27a5344cad83.png)
