### ISSUE TITLE
Self Apply Button and self special action button

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#267]
The Chat card for Apply Button and self special action button needs a class="everyone" so the player can start the script by clicking the button. At moment it locks like usable but didn´t start the script. 

![image](https://user-images.githubusercontent.com/64524134/104963593-29dd2200-59db-11eb-909b-8c92a5ef46bb.png)

![image](https://user-images.githubusercontent.com/64524134/104963614-35c8e400-59db-11eb-94ac-3daa87793f3d.png)

**Comment by Rughalt** [comment]
Option "Allow players to use Apply Action" will now allow *all players to apply all actions to any actor they have permission for. Will be out with 0.88.3
