### ISSUE TITLE
Support for animated tokens

### ISSUE THREAD

**Issue by JoshuaSarver** [Rughalt/D35E#268]
Animated tokens would be amazing!

**Comment by JoshuaSarver** [comment]
**This little guys wants to lay eggs in the bloated corpses of his victims!**
![crawlerANIMATION](https://user-images.githubusercontent.com/77645296/105431381-7dda4780-5c23-11eb-8894-c2bb27b8905a.GIF)

**Comment by Rughalt** [comment]
Added per-actor override that allows to set token on Token dialog - and system setting to enable animation loop. Both of them allow usage of animated tokens.
