### ISSUE TITLE
Damage Reduction not clear on what is full immunity 

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#270]
![image](https://user-images.githubusercontent.com/22633854/104972999-500abe00-59eb-11eb-9aab-fafd752f20f2.png)
Could we add some text here to say or a tooltip that if you select for example Bludgeoning via the box that it means FULL immunity to bludgeoning.  Whereas if you put 5 next to it it means DR 5/Bludgeoning as this isnt clear.  The dialog makes it look like you have to select both bludgeoning and then add 5 for that to work.

**Comment by Straddlecat** [comment]
0.88

**Comment by Rughalt** [comment]
Damage appeared as 0 because it was converted to non-lethal. I will try to add some descriptive text when damage is non-lethal in tooltip so this will not cause confusion.
