### ISSUE TITLE
End Effect announce and debuff capability

### ISSUE THREAD

**Issue by st3nd02** [Rughalt/D35E#281]
Buff Announce option on the turn it ends (like regen but only when it ends) e.g. "SamplePC Rage ended."
Also this can be linked with another thing like Rage fatigue (like have a buff within buff and then rage ends for example can press (like regen) and put a debuff on character

**Comment by Rughalt** [comment]
1. Debuff is already in (deactivate special action)
2. Will be added in 0.89
![image](https://user-images.githubusercontent.com/802214/107887837-3042b900-6f09-11eb-9585-66afefa6c701.png)

**Comment by Rughalt** [comment]
![image](https://user-images.githubusercontent.com/802214/107888083-dd6a0100-6f0a-11eb-8cf7-be2107dd3cf4.png)
Improved card design
