### ISSUE TITLE
Same dice roll used for multiple attacks when they should be new rolls for each

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#283]
0.88.2

When you have multiple attacks like full attack or rapid shot and you have feats that give extra damage in the form of dice rolls e.g. sneak attack or skirmish then the same dice roll for the damage is used for each attack when they should be new rolls each time 

e.g.
![image](https://user-images.githubusercontent.com/22633854/105236689-0c878f80-5b64-11eb-8507-603d285df157.png)

**Comment by Rughalt** [comment]
How is skirmish configured?

**Comment by Rughalt** [comment]
featDamagePrecision needs & (`&featDamagePrecision`) before name in case of skirmish etc - in other case its pre-rolled.
Rogue sneak attack will be fixed in 88.3 and will automatically replace old one for standard rogues/assassins etc.
