### ISSUE TITLE
Resource Update Loop does not correctly check value after update.

### ISSUE THREAD

**Issue by Gritakthegoblin** [Rughalt/D35E#285]
When I try to use a resource like so:

@resources.layOnHands.value > 0 ? 2 : 0

and then change the value of the resource to '0', the command acts as if it were the previous value.

So If I change the value of the resource to '0' and then to '1' the command would treat the value as '0'.

**Comment by Rughalt** [comment]
It seems *resources* were mean (in original) to represent things that should be displayed on token bars. For linking usages - most common item interaction - new mechanic will be introduced.

**Comment by Rughalt** [comment]
Item linking can be tracked in #289
