### ISSUE TITLE
Calculation of non-class skill rank is wrong

### ISSUE THREAD

**Issue by agrtga** [Rughalt/D35E#288]
Recreating a cleric for a player from scratch due to problems from the number of changes that have been made over the months. During the process tonight I have determined that the non-class skill ranks aren't calculating correctly.

<img width="212" alt="1" src="https://user-images.githubusercontent.com/12749451/105621167-bf5d2500-5dd2-11eb-9753-fb41c3b05fc0.png">

This image shows that we're getting a +1 for Int (correct), but we only have one rank. That is incorrect. Two skill points were allocated at level 1, +1 point at level 2, and +1 point at level 3 for a total of 4 skill points allocated. That means 2 ranks! The division is being done twice. The total modifier should be +3.

**Comment by Rughalt** [comment]
This was discussed on Discord several times, and fix will be up in 0.88.3 (half-ranks will be added between levels)
