### ISSUE TITLE
Activated Spells/Abilities on Summary

### ISSUE THREAD

**Issue by st3nd02** [Rughalt/D35E#290]
An option that will allow activated Items from Inventory, activated class abilities, activated racial abilties to appear on the summary page like attacks do.

**Comment by Rughalt** [comment]
Items with Action block have new option "Favorite" that will display them in summary. Will be out in 0.89.
![image](https://user-images.githubusercontent.com/802214/106937770-73897480-671e-11eb-82f9-70cdd6b22aa6.png)
![image](https://user-images.githubusercontent.com/802214/106937900-9ae04180-671e-11eb-8fb5-a71c4d91e146.png)
