### ISSUE TITLE
Bag of holding not behaving as container

### ISSUE THREAD

**Issue by egon1024** [Rughalt/D35E#295]
Hey folks - first up, just wanted to say thanks for this module.  Still learning Foundry, let alone the 3.5e module and it's great.  There's every chance that this is just a PEBCAK issue, so don't hesitate to tell me that's the deal.  :smile: 

In any case, I'm trying to import some characters from an established 3.5 game I've been running and one character has a Bag of Holding.  However, when I add the bag to the inventory, I can't get it to act as a container.  Can you help?

Thanks in advance!

**Comment by Rughalt** [comment]
New Bag of Holding items will be added to compendiums in 0.88.3!

**Comment by egon1024** [comment]
Rock on - you folks are the best.  :)
