### ISSUE TITLE
Toggle spell description cards from appearing in chat

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#301]
![image](https://user-images.githubusercontent.com/22633854/106151803-a3f86e00-6174-11eb-89be-4edf70359b63.png)

These short spell cards contain information such as the DC of the spell.  It would be good if you could stop them from appearing as all you really want is the effect of the spell and any saves that the player needs to make.

**Comment by Rughalt** [comment]
New option will be added in 0.89
