### ISSUE TITLE
Polymorph Does Not Override Racial Traits

### ISSUE THREAD

**Issue by GlognarX9** [Rughalt/D35E#302]
When I polymorph my character that is a grey elf into a cave troll the racial traits for the grey elf are not overridden.

I tried to attach the file for the character as a .json but github would not let me so I changed suffix to .txt I hope that works for you.

[fvtt-Actor-Ofëa__Oh__Tingilindë (1).txt](https://github.com/Rughalt/D35E/files/5890988/fvtt-Actor-Ofea__Oh__Tingilinde.1.txt)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.89
