### ISSUE TITLE
Rogue lvl 10 missing special ability

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#305]
at level 10 we get a special ability for the rogue that give the choice to select a in a list of skill.  But 1 skill is missing from that list.
Improved evasion.

Need to add improved evasion to the special ability list

![image](https://user-images.githubusercontent.com/74456344/106367938-5fa3d400-6314-11eb-8f64-db438242135d.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.89
