### ISSUE TITLE
Missing Sorcerer class in various Spells

### ISSUE THREAD

**Issue by elfosardo** [Rughalt/D35E#311]
List updated 04/02/2021 (should be all)

Acid Splash
Arcane Lock
Chill Touch
Delayed Blast Fireball
Globe of Invulnerability
Interposing Hand
Keen Edge
Knock
Lesser Orb of Fire
Levitate
Lightning Bolt
Limited Wish
Mage Armor
Mage's Faithful Hound
Mage's Magnificent Mansion
Mage's Private Sanctum
Mage's Sword
Magic Jar
Maze
Meteor Swarm
Mental Pinnacle
Mount
Overland Flight
Passwall
Permanency
Phantom Trap
Planar Binding
Polar Ray
Polymorph
Prismatic Spray
Prismatic Wall
Protection from Arrows
Ray of Enfeeblement
Ray of Exhaustion
Ray of Frost
Reduce Person
Resilient Sphere
Rope Trick
Scintillating Pattern
Scorching Ray
Secret Chest
Sequester
Shades
Shield
Shocking Grasp
Shrink Item
Simulacrum
Solid Fog
Spectral Hand
Statue
Stinking Cloud
Stone to Flesh
Telekinesis
Telekinetic Sphere
Teleport Object
Temporal Stasis
Touch of Idiocy
Transformation
Trap the Soul
Vampiric Touch
Vision
Wall of Force
Wall of Ice
Wall of Iron
Waves of Exhaustion
Waves of Fatigue
Web
Wish

**Comment by Rughalt** [comment]
Spells on the list should have correct sorcerer level set. Will be out in 0.91
