### ISSUE TITLE
TAH not showing correct spells for variety of classes depending on npc or character

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#314]
0.88.6

There are a number of classes for both players (D35E.Character) and NPC (D35E.NPC) that do not show spells correctly in the Token Action Hud

Player Bard: does not show any spells
[fvtt-Actor-bard_player.zip](https://github.com/Rughalt/D35E/files/5912003/fvtt-Actor-bard_player.zip)

Player Sorcerer: doesnt show any spells
[fvtt-Actor-sorc_player.zip](https://github.com/Rughalt/D35E/files/5912007/fvtt-Actor-sorc_player.zip)

NPC Cleric: Shows all spells regardless of what is selected when it should only show memorised spells
[fvtt-Actor-test_cleric.zip](https://github.com/Rughalt/D35E/files/5912009/fvtt-Actor-test_cleric.zip)

**Comment by Straddlecat** [comment]
The pattern looks like:
Spontaneous classes for D35E.Character dont show any spells
Divine classes for D35E.NPC show all spells in the spellbook not just those that have been memorised

**Comment by Rughalt** [comment]
Fixed, will be out when PR gets accepted.
