### ISSUE TITLE
Bard Inspire courage maths calculation incorrect

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#315]
Inspire Courage is +1 at levels 1-7
Inspire Courage is +2 at level 8
Then +1 every 6 levels after.

1 + max(0, floor((@item.level - 1) / 4)) breaks at lvl 5

**Comment by Straddlecat** [comment]
0.88.6

**Comment by Rughalt** [comment]
Changed to 1 + max(0, floor((@item.level - 2) / 6)). Will be out in 0.89

**Comment by Rughalt** [comment]
It additionally provides correct combat change now.
