### ISSUE TITLE
Price updates from enhancements overriding base price not adding to them

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#318]
0.88.6

e.g.
Dwarven Waraxe is 30gp
Masterwork should add another 300gp (doesnt happen at the moment)
+1 enhancement is +2000gp

So price should be 2330 but adding a +1 enhancement overrides price to flat 2000.  Think the enhancement is missing the addition.

**Comment by Rughalt** [comment]
Fixed, will be out in 0.90
