### ISSUE TITLE
Toggle use of ammunition during ranged attacks

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#320]
It would be nice to firstly toggle whether ammunition needs to set in order for a ranged attack e.g. with arrows, bolts etc

Secondly grey out attacks if no ammunition is set in the attack dialog

**Comment by Rughalt** [comment]
Added in 0.90
![image](https://user-images.githubusercontent.com/802214/109386920-52233f00-78fe-11eb-86fd-e08299019186.png)
