### ISSUE TITLE
Some monster abilities are missing

### ISSUE THREAD

**Issue by omegaghost** [Rughalt/D35E#323]
Examples: rake, pounce, improved grab.
I'm not sure how to approach this as I don't think it's entirely reasonable to go through every monster entry in monster manual checking what it has and doesn't have. But at least we'll have a list for now. I'll be posting in comments to expand the list as I find other things that are missing.

**Comment by Rughalt** [comment]
I do not think all monsters miss them, see Tiger family:
![image](https://user-images.githubusercontent.com/802214/106852384-43a78600-66b8-11eb-9aa7-663c529463d4.png)
![image](https://user-images.githubusercontent.com/802214/106852410-4f934800-66b8-11eb-8cf2-5a7e4ba1a6f6.png)
At this step, fixing specific monsters you find not working seems the way to go - most of the monsters that have rake/pounce/improved grab seem to have it. All abilities that could be parsed and programmed somehow were during monster import. Some monster with magic weapons can miss attack with them but natural attack stuff should be there.

**Comment by Rughalt** [comment]
I close this in factor of tickets with specific bugs for monsters
