### ISSUE TITLE
Haste is affecting spells which it shouldnt

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#324]
0.88.6

![image](https://user-images.githubusercontent.com/22633854/106910794-7c1b8400-66f9-11eb-899b-891c1043951c.png)

Looks like the extra attack, which should only affect non spell attacks is causing multiple attacks with spells as well

**Comment by Rughalt** [comment]
Fixed, will add attack only for weapon and natural attacks when using full attack
