### ISSUE TITLE
Add nonlethal damage and temporary HP as options for token display bars

### ISSUE THREAD

**Issue by freeformline** [Rughalt/D35E#326]
HP is my group's go-to attribute to display using token display bars, but some of my players regularly use powers that interact with the secondary HP attributes (attributes.hp.nonlethal and attributes.hp.temp), which would benefit greatly from being displayed as a secondary display bar alongside HP, but which are not currently options in the display bar attribute drop-down menu. 

If it is possible and convenient, please add these attributes to the display bar options.

**Comment by Rughalt** [comment]
Added, will be out in 0.89
![image](https://user-images.githubusercontent.com/802214/107086704-aacd5380-67fa-11eb-9955-ea94e06d6350.png)
