### ISSUE TITLE
Buffs on NPC sheets behave incorrectly

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#328]
0.88.6

There appears to be some strange happenings when trying to place buffs on NPC character sheets.

E.g. when doing Inspire courage on an NPC it places multiple copies of the buff icon
![image](https://user-images.githubusercontent.com/22633854/107099872-bcb6f280-680a-11eb-99ce-a6b454b64a37.png)

Secondly when casting a buff on yourself it applies it to the NPC sheet, not the token
![image](https://user-images.githubusercontent.com/22633854/107100032-191a1200-680b-11eb-8752-2032b8017888.png)

and it only seems to apply after doing a refresh.

I have included the character, feat, buff.
[npc_buff_issue.zip](https://github.com/Rughalt/D35E/files/5935835/npc_buff_issue.zip)

**Comment by Rughalt** [comment]
Should be fixed along with #330
