### ISSUE TITLE
Lights from characters are throwing up an error message on start up

### ISSUE THREAD

**Issue by Eldintux** [Rughalt/D35E#332]
When going to a new scene (including start up) a player sometimes receives this message: User 'Player2' lacks permission to update tokens in parent 6ReoAE12Y92GZXCp. (the code at the end is the scene id)

After some investigation there appear to be 2 sources one is the module CommunityLighting - I've removed it. But the other appears to be any light sources emanating from another token. Either from an object carried by that token or if a light source is set directly on the token. Independent light sources set using the lighting layer don't appear to have the same affect.
It doesn't appear to affect play too much (sometimes lights can't be seen but a refresh sorts it), but does occur on all my 3.5 games but not consistantly ie on some scenes other tokens can have light sources without the error, but on the scenes it does occur it can be removed by removing the light source and the error always returns with the return of the light. (I haven't had it happen on any other system)
Using Foundry 0.7.9 & system 3.5e SRD 0.88.7

It doesn't appear to affect play too much (sometimes lights can't be seen but a refresh sorts)

(I have narrowed it down to just Linked PC Actor Tokens)

**Comment by Eldintux** [comment]
Just tried a brand new world with 3.5e. Brand new actors, one with light done through the vision tab in token. Other actors player had the same error. Tried the same in 5e no problem. No Modules loaded into either world. Hope all this helps!

**Comment by Eldintux** [comment]
OK think I'm getting somewhere but still don't know how to solve.  If I tick do not override token light in the Actor settings page the problem is resolved. This of course means that I can't use torches in the inventory. - Hope this helps

**Comment by Rughalt** [comment]
This is not problem with light, more a problem with users trying to update actors they do now own. Fixed initial code not to launch updates on unowned actors.
