### ISSUE TITLE
Incorrect intelligence on Adder familiar

### ISSUE THREAD

**Issue by krlsrrll** [Rughalt/D35E#333]
Familiar (Adder) not having right intelligence, is a lookup (pictured) but has 8 instead of 9.

![2021-02-09](https://user-images.githubusercontent.com/54375380/107345872-f19da080-6abb-11eb-8f5d-85c80e11c9b4.png)
![2021-02-09 (1)](https://user-images.githubusercontent.com/54375380/107345878-f2363700-6abb-11eb-9f33-773f75e51459.png)

**Comment by Rughalt** [comment]
Fixed, along with a toad (old ones must have their base intelligence set to 2 still)
