### ISSUE TITLE
Armor enhancement is adding the incorrect type of enhancement

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#335]
0.88.6

It looks like the armor enhancement
![image](https://user-images.githubusercontent.com/22633854/107401340-a951a300-6afa-11eb-887e-fddd14e9dd97.png)
Is adding the incorrect armor type.

When it does the calculation for AC it displays separately from the armor
![image](https://user-images.githubusercontent.com/22633854/107401408-c4241780-6afa-11eb-9fcc-ccfd455528c4.png)

And when the armor is overriden e.g. using the Luminous Armor spell then it correctly replaces the armor when the spell uses the AC.Base field but not the enhancement
![image](https://user-images.githubusercontent.com/22633854/107401586-f0d82f00-6afa-11eb-938f-670d795c8631.png)

The enhancement itself even has a field which is to day dont add this to base, so I think it is not adding to AC.base in the first place

**Comment by Rughalt** [comment]
Fixed, will be out in 0.89
![image](https://user-images.githubusercontent.com/802214/107539559-5ee92880-6bc5-11eb-911d-684ebcd133c8.png)
