### ISSUE TITLE
Orcs and orcas mixed up in stats/sizes/icons

### ISSUE THREAD

**Issue by tankus157** [Rughalt/D35E#337]
This most probably stems from orca being created first, and the script finding "orca" by looking up "orc".

![orc(a)](https://user-images.githubusercontent.com/9535229/107425342-ddbe6280-6aec-11eb-97a1-f16a231d99ae.PNG)

**Comment by Rughalt** [comment]
Hi! Orcs per se are not in bestiary as they are a race and you create NPC using ORC race (which will be added soon, probably 0.89). Stats are for Orca per SRD (https://www.drivethrurpg.com/browse/pub/3367/Purple-Duck-Games?filters=0_2890_0_0_0_0&keywords=dragon&src=fid2890). Force Dracgon and Thorciasid also have wrong icons. I will fix those for 0.89

**Comment by Rughalt** [comment]
Fixed, will be out in 0.89
