### ISSUE TITLE
Deprecated terms used to roll dice

### ISSUE THREAD

**Issue by tankus157** [Rughalt/D35E#338]
This prevents modules like Dice So Nice! to work properly and we cannot see other player's rolling animations.
![dice_so_nice](https://user-images.githubusercontent.com/9535229/107427395-5a524080-6aef-11eb-9233-a201191529f7.PNG)

**Comment by Rughalt** [comment]
Fixed deprecation.

Dice so nice bug was due to misconfiguration in Dice So Nice for custom chat cards. Fixed, will be out in 0.89 or earlier.
