### ISSUE TITLE
Buff with special actions gets toggled twice on activation

### ISSUE THREAD

**Issue by DenMesh** [Rughalt/D35E#343]
Wne a buff has both an Activate and Deactivate Specail Action, both get triggered on activation in (seemingly) arbitrary order. The "active" checkbox for the buff also changes states.

To reproduce:
1. Create a new buff, in Special Actions add an action to Activate and Deactivate with the following action texts
Activate: Update set "data.attributes.hp.temp" to 10 on self
Deactivate: Update set "data.attributes.hp.temp" to 0 on self
2. Add buff to character
3. Activate buff.

**Comment by Rughalt** [comment]
I cannot reproduce this with buff set up like that:
![image](https://user-images.githubusercontent.com/802214/107877919-901c6e00-6ecf-11eb-9c9c-8965fe98d452.png)

Actor json would be very helpful.

**Comment by DenMesh** [comment]
Attaching actor and buff files. Tried disabling all other modules, the behavior is the same.

When I click "activate" on the buff, it toggles on (checkbox checked), then off (unchecked), then on (checked) again. At the same time the attribute (temp hp) is assigned the right value (10).

If I uncheck "activate" it toggles off (unchecked), then on (checked) and then off again. The attribute switches from 10 to 0, then back to 10 and stays there. This behavior is consistent and persists.

UPD: It seems I was using an NPC sheet for testing. If I use a PC sheet, it is similar (although I do not see the value switching as it is on another tab)

[Temp.zip](https://github.com/Rughalt/D35E/files/5977905/Temp.zip)

**Comment by Rughalt** [comment]
Bug ocurred on older version, does not occur on current.
