### ISSUE TITLE
Shapechange Condition icon is repeated

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#345]
0.88.8

When using Shapechange>alter self the condition marker that is applied is being added multiple times e.g. 

![image](https://user-images.githubusercontent.com/22633854/107863073-307b7f80-6e49-11eb-8f1b-9c9c53dc01a1.png)

Also is it possible to not add a condition icon?  For NPCs who are using alter self it gives the game away. Can this be toggled?

**Comment by Rughalt** [comment]
Fixed:
- Shapechange type buff (wildshape, polymorph and alter-self) buff types will not appear on token
- All other buffs have "Hide Buff from Token" setting that will hide buff from token.
