### ISSUE TITLE
Weapon size on large monsters is still medium

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#346]
Large creatures such as ogres and trolls and others that have weapons have their items set to medium size when they should be large

e.g. Ogre

**Comment by Rughalt** [comment]
Fixes in places where I could easily identify this (this only affected *items* not attacks, as generated attacks were scaled to creature size. Any more monsters - please report them in other tickets, with monster names.

Fixed:
- Ogres
- Angels
- Other assorted monsters
