### ISSUE TITLE
Improved Natural Weapon

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Rughalt/D35E#347]
This feat is currently doing the same thing as a Weapon Focus. Both in the compendium and in any monsters that have this feat:

![image](https://user-images.githubusercontent.com/24766235/107863691-e62fd980-6e1b-11eb-9af6-1995dcbd9f6b.png)

**Comment by Rughalt** [comment]
Fixed in monsters I found this in. Will be out in 0.91
