### ISSUE TITLE
GM's cant access the Character HUD movement icon

### ISSUE THREAD

**Issue by Eldintux** [Rughalt/D35E#352]
The small movement icon for the Character HUD is just under the Game Master Tools icon and so can't be reached. Hence GM can't move the HUD. Any chance it could be placed in a different area to allow for GM's to have this function.

I think this maybe a screen size problem I have a 1920x1200 display. But maybe a 'Default' setting in the configuration maybe a way forward.

**Comment by Rughalt** [comment]
Area that allows dragging is larger now - this should also help with moving the window. Will be out in 0.90
