### ISSUE TITLE
Buffs are expiring one round too short

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#356]
0.88.9

If you have an 8 round buff then it should persist until the 9th round because it expires on round start.  At the moment if you cast a buff in round 1 and it lasts for 8 rounds it will expire in round 8 but before the character can act meaning it only lasts for 7 rounds

**Comment by Rughalt** [comment]
I always assumed - and programmed it that way - so 1 round buffs can work ok. From what I understand, when you have 1 round buff, it expires before you can act. I can make this an option (expire butt at end/expire butt at start round)

**Comment by Straddlecat** [comment]
That works for 1 round buffs but when you have a mage casting haste which should last for 8 rounds it only lasts for 7 then the mage shouts at me. A toggle would be ideal

**Comment by Rughalt** [comment]
I do think that haste gives you action on the round it is casted, and this round is taken into account when buff duration is calculated. I think this was for 5e, but I blieve logic to be the same for 3.5 as spell is worded: https://www.sageadvice.eu/2015/11/23/haste-can-i-take-a-second-action-on-the-same-turn/

**Comment by Straddlecat** [comment]
Turns out this is actually a bug with the Token Action Hud rather than with the buff round calculation.  It was saving the rounds left when toggled on and off and not resetting them when toggled on.
