### ISSUE TITLE
[Request] Spells/Abilities that have an attack but no damage.

### ISSUE THREAD

**Issue by Gritakthegoblin** [Rughalt/D35E#358]
Hello again, I'd like to make a request for spells/abilities to remove the fact that you have to have a damage variable if the spell/ability has an attack in it. I don't like having to put in a 0 damage variable when all I want is just the attack roll it self.

With much love
=========
Goblin

**Comment by Rughalt** [comment]
Added - you need at least Special Action or Effect defined there for it to work with attack roll only.
