### ISSUE TITLE
Buff "Activate Special actions" doesn't have buff item's data when passing to actor entity for applyActionOnSelf

### ISSUE THREAD

**Issue by Calvin263** [Rughalt/D35E#359]
For a given buff's activation special action, say "set the actor's temp HP to the buff's level" (action is "update set data.attributes.hp.temp to @data.item.level on self"), @data.item.level does not exist in the context.

Only actionData gets passed to the applyActionOnSelf function. It contains the action (e.g. "Update"), and its parameters (e.g. "set", "data.attribute.hp.temp", "to", "@item.level").

That'd make sense since applyActionOnSelf only affects, well, self. But you may want to reference the buff itself to affect the actor's data, and not only use the actor's data to affect the actor's data.

**Comment by Rughalt** [comment]
Added two fields to rollData available from special actions:
- `buff` - contains data of buff that caused automatic action to run
- `self` - data of actor that run the action (it was inconsistent previously, some rolls used `this` and some used data of actor that created the action)
