### ISSUE TITLE
[Request] Special actions to modify / toggle arrays

### ISSUE THREAD

**Issue by Calvin263** [Rughalt/D35E#360]
use case: Special action on a buff (or spell) to add a condition immunity.

Currently, you can do so by doing "Update set data.traits.ci.custom to Fear on self" to say, add a Fear condition immunity.

It would be nice to be able to set a certain immunity to true. 

_Similarly, it could be used to set a damage reduction or an energy resistance._
[Edit] You can already do DR/ER

**Comment by Rughalt** [comment]
Editing any array will be hard - I will rather implement actions for conditions/fields, that limit stuff you can enter, as especially removing things from array would be very hard.

**Comment by Rughalt** [comment]
Added action for setting traits:
`Trait set ci dazzle to false on target`
`Trait set ci dazzle to true on target`

Generic command is
`Trait set <group> <name> to <true|false> on <self|target>`
