### ISSUE TITLE
Request Combat Changes can add special actions

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#362]
Would be really cool to have special actions and combat modifiers directly on attacks

e.g. someone with distracting shot shoots someone and it automatically applies a condition on them

![image](https://user-images.githubusercontent.com/22633854/108424363-f76c5200-7230-11eb-84c0-c3aea46c9ddc.png)

**Comment by Rughalt** [comment]
Added, will be out in 0.90
![2021-02-28 11 37 00](https://user-images.githubusercontent.com/802214/109415570-bb1bbd00-79b9-11eb-84e9-a436ccbd5f97.gif)
