### ISSUE TITLE
AC doesn't calculate correctly on NPC sheet

### ISSUE THREAD

**Issue by agrtga** [Rughalt/D35E#37]
The armor class on the NPC sheet doesn't calculate the adjustment due to the Dexterity modifier correctly. This occurs when there is a racial adjustment to Dexterity for example
![AC wrong](https://user-images.githubusercontent.com/12749451/90407765-de61c900-e074-11ea-8f0f-fab70626b8ee.jpg)
.

**Comment by Rughalt** [comment]
This is probably because Chainmail has Max Dexterity bonus equaling 2.

**Comment by agrtga** [comment]
Good catch. I had apparently forgotten to increase the max Dexterity by 2 for it being mithral.
