### ISSUE TITLE
DR Options (Greenbound Creature)

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Rughalt/D35E#375]
Greenbound creatures (a template from the Lost Empires of Faerun) have DR 10 Magic **and** slashing. I am sure they are not the only thing like this out there though I don't know any others off the top of my head. Not sure a good way of making this work in the current set up but I just wanted to bring it to your attention. :)

**Comment by Rughalt** [comment]
You can do that:
1. This is DR with *and*
![image](https://user-images.githubusercontent.com/802214/108586417-b23e4200-734e-11eb-99dd-9f38fde390de.png)
2. This is resistance with *or*
![image](https://user-images.githubusercontent.com/802214/108586425-c84c0280-734e-11eb-8075-febb8ca4b5a4.png)

**Comment by Cosmic-Lattee** [comment]
Sorry I should have been more clear with what I meant:

![image](https://user-images.githubusercontent.com/24766235/108588992-c586e880-7321-11eb-8bf3-e7bfc40a8ffc.png)

I meant from this menu where changes are made in this case via a template.

**Comment by Rughalt** [comment]
You can also do this already:
![image](https://user-images.githubusercontent.com/802214/108590255-bbd1a500-7362-11eb-8210-5ab8d924d40f.png)
