### ISSUE TITLE
Blackguard sneak attack formula error: @classes.blackguard.level not provided in roll data.

### ISSUE THREAD

**Issue by Calvin263** [Rughalt/D35E#377]
Formula reads: "floor(@classess.blackguard.level - 4) / 3" [sic]. Should be @classes (?)
I tried changing it to that but it was still saying that wasn't present in the provided roll data...
Rogue's formula is just "(ceil(@level/2))" for reference.
[Blackguard.zip](https://github.com/Rughalt/D35E/files/6016560/Blackguard.zip)

**Comment by Rughalt** [comment]
Fixed, set tp `ceil((@level - 3) / 3)` which should give correct progression. Will be out in 0.90
