### ISSUE TITLE
Max charges not updating for items

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#378]
0.89
![image](https://user-images.githubusercontent.com/22633854/108873789-63fd9d00-75f3-11eb-9816-2cdfdf3b1292.png)

The max charges never gets populated
![image](https://user-images.githubusercontent.com/22633854/108873897-84c5f280-75f3-11eb-96bf-e34a0f85055e.png)

Even when clicking to recharge them

**Comment by Straddlecat** [comment]
Should add that this happens when using the common uses pool in enhancements bit which might not be the right place to do this. When done through the details tab is seems to be fine

**Comment by Rughalt** [comment]
Common pool is used only for Enhancement uses, and is displayed here. If you want to set up item action, not add converted spell as enhancement, Details page is the way to go.

![image](https://user-images.githubusercontent.com/802214/109380967-d6ae9700-78d7-11eb-87f4-e0be13eb93d5.png)
