### ISSUE TITLE
Request self use action which doesnt use the chat card

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#380]
It would be really good to have a self use action that doesnt require a secondary action through a chat card. 

e.g. Boots of Speed can be set up now to generate a special action on a chat card which you can then use to apply a 1 round haste buff to yourself.

But what is really needed is a self action that just applies that buff to yourself either from an item action or a spell which doesn't need to go through the chat card.

**Comment by Rughalt** [comment]
Added to everything that uses standard attack chat card - items, spells and attacks that use "Action" icon. Will be out in 0.90
