### ISSUE TITLE
Monk, Wholeness of body little bug

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#382]
![image](https://user-images.githubusercontent.com/74456344/108910048-50eacd00-75f3-11eb-88ce-83b338c3dd31.png)
![image](https://user-images.githubusercontent.com/74456344/108910103-6233d980-75f3-11eb-82f8-888248f3fbac.png)
Should be twice as wrote in the description, but is actually equal to the current level.  As seen this level 10 monk have 10 wholeness of body.

**Comment by Rughalt** [comment]
Fixed, also fixed damage type to *healing* so it always applies healing. Will be out in 0.90, will replace old ability on characters
