### ISSUE TITLE
Healing items say damage in the chat card

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#384]
0.89
Minor UI issues but when using the healing action 

e.g. cure spells, potions, etc
The chat card says damage 
![image](https://user-images.githubusercontent.com/22633854/109000639-e2157e80-769b-11eb-80e2-ef3bb24a49be.png)
![image](https://user-images.githubusercontent.com/22633854/109000685-f194c780-769b-11eb-9749-09236bdd2039.png)
![image](https://user-images.githubusercontent.com/22633854/109000827-1a1cc180-769c-11eb-8ad4-d669589299ca.png)

**Comment by Rughalt** [comment]
Fixed - requires Action type set to Healing. Will be out in 0.90
