### ISSUE TITLE
Clothing and Weight

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Rughalt/D35E#389]
![image](https://user-images.githubusercontent.com/24766235/109259932-cce73f80-77c2-11eb-8608-66eb116ef3af.png)

![image](https://user-images.githubusercontent.com/24766235/109259656-45013580-77c2-11eb-9f11-c7e4f65b01d0.png)

You can sort of cheat it by selecting that you aren't "carrying" the clothes. A minor thing not sure if it is worth the hassle either way but wanted to point it out. :)

**Comment by Rughalt** [comment]
Can you point me to this rule in SRD? I cannot find it, and for now I would like it 1-1 with SRD.

**Comment by Cosmic-Lattee** [comment]
Gotcha well feel free to close this one then. This is one of those things that is in the core rulebooks that isn't in the SRD like XP tables (though much less important than those lol).

**Comment by Rughalt** [comment]
This will be done as a generic checkbox "No weight when equipped"

**Comment by Rughalt** [comment]
![image](https://user-images.githubusercontent.com/802214/112607667-be1f9700-8e19-11eb-9492-8e1d5b322ff9.png)
Will be out in 0.92
