### ISSUE TITLE
Rock Gnome & Forest Gnome Issues

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Rughalt/D35E#390]
First issue is that Rock Gnomes get Dancing Lights twice: 

![image](https://user-images.githubusercontent.com/24766235/109554272-9f87e380-7a99-11eb-98bc-d1de990bc6ef.png)

This makes it show up twice into spell-like abilities.

The second issue is a transcription one for Forest Gnomes:

![image](https://user-images.githubusercontent.com/24766235/109554391-c80fdd80-7a99-11eb-8c2d-d22b062a3720.png)

They are currently displaying the text for Rock Gnome though it is just a cosmetic issue since it looks like they have the right features however:

Third issue is it looks like Forest Gnomes get Small Hunter twice:

![image](https://user-images.githubusercontent.com/24766235/109554499-eaa1f680-7a99-11eb-8147-34e246a8fd7b.png)

That one doesn't cause the trait to appear twice though since I imagine it doesn't let you have two features with the same ID while it will let you have two of the spells.

![image](https://user-images.githubusercontent.com/24766235/109554740-3bb1ea80-7a9a-11eb-83c0-212e89d3fccf.png)

**Comment by st3nd02** [comment]
Sorryyyy... :(

**Comment by Rughalt** [comment]
Fixed, will be out in 0.91
