### ISSUE TITLE
Math for Even Number Ability Score Penalties 

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Rughalt/D35E#394]
![image](https://user-images.githubusercontent.com/24766235/109758026-9d647880-7bb0-11eb-8889-e78dee525e2a.png)

So when you have a even number and apply a penalty to it the math isn't done right.

So if you have a 12 and you take a -1 strength penalty you should act as though you have a 11 strength, however:

![image](https://user-images.githubusercontent.com/24766235/109758210-d7357f00-7bb0-11eb-865a-61148ffb3266.png)

If you have a 13 and do a 1 penalty the modifier remains correct:

![image](https://user-images.githubusercontent.com/24766235/109758286-f46a4d80-7bb0-11eb-81fc-bb68cd170cdf.png)

Same thing happens with damage and drain as well.

This was tested with a game with no modules running. Foundry is 7.9 and 3.5 is .89.

**Comment by Rughalt** [comment]
Fixed, will be out in 0.90
