### ISSUE TITLE
Allow ammo recovery to be turned off

### ISSUE THREAD

**Issue by agrtga** [Rughalt/D35E#398]
Automatic ammo recovery is something I don't see fitting in; however, I'd like my players to be able to use the ammo consumption capability. Right now I cannot use any of it due to the limitation. My understanding it is all-or-nothing.

Please provide a way to specifically turn off ammo recovery.

**Comment by Rughalt** [comment]
As most of system features automatic ammo recovery can be turned off/on in system settings.
