### ISSUE TITLE
Familiar Hit Points

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Rughalt/D35E#399]
So Familiar hit points should be half of your wizard's HP. 

![image](https://user-images.githubusercontent.com/24766235/110067653-c7957200-7d39-11eb-9d7d-1f068e03c0fd.png)

However currently familiars seem to be adding HP instead of changing it's HP to be half of the masters:

![image](https://user-images.githubusercontent.com/24766235/110067990-60c48880-7d3a-11eb-990a-3c1fae689635.png)

![image](https://user-images.githubusercontent.com/24766235/110067796-0d523a80-7d3a-11eb-9ca4-d3e99a03f809.png)

**Comment by Rughalt** [comment]
This needs backend work as a part of update, moving to 0.92

**Comment by Rughalt** [comment]
Added ability to use "Replace" with HP change. Change must be applies to existing familiars, new ones have this fixed in compendium directly. Will be out in 0.92
