### ISSUE TITLE
[Bug] Limited Uses always subtracts by 1 regardless of other values.

### ISSUE THREAD

**Issue by Gritakthegoblin** [Rughalt/D35E#402]
Hello, I am Goblin. I have encountered an issue with a custom item of mine based on the class feature of the Fatespinner Prestige Class known as 'Spin Fate'. I've decided to test out the new subtract value special actions and the new @range value released in V.90. (The item has Limited used per day) However, when I changed the value of the 'Charges per use' value to 0 and the @range scale was set to the value of '2' then activated the item, it used 1 charge instead. I then attempted other values to test out why it was doing this, but the value was always subtracted by 1, even when the 'Automatically deduct charges' was turned off.

The item in question was built with the intent to optionally increase a spell DC bonus via combat changes 'featSpellDCBonus' with the modification formula being set to '@range'. No other values have been set besides combat changes, and limited uses per day.

**Comment by Rughalt** [comment]
Added - you can make feat use "Charges per use" value or slider selected range value. Will be out in 0.92

![image](https://user-images.githubusercontent.com/802214/112606203-65033380-8e18-11eb-8cf5-9d65fbf62a90.png)
