### ISSUE TITLE
Allow for special actions on attacks to be applied only once during a full attack

### ISSUE THREAD

**Issue by freeformline** [Rughalt/D35E#403]
I am currently automating Combat Expertise and similar feats by adding an optional combat change slider to melee attacks, which creates a one-round temporary buff that applies the feat's modifiers for the rest of the round. This works well on single attacks, but the system gets confused when I use it as part of a full-attack, as each attack in the full attack automatically applies the buff to the attacking actor, which sometimes causes the buffs to misbehave (explained below). Adding an option in the special action programming that would allow the writer to determine if the action will be applied for all attacks in a full attack or only in the first attack in the full attack would be helpful to solve this problem.

Normal buff behavior: Make attack > Check "Combat Expertise" optional combat change and set slider value > A featAttackBonus penalty for the attack is set based on @range value and a temporary "Combat Expertise" buff is automatically applied via special actions, using the @range value as its item level > The actor gains featAC and loses featAttackBonus equal to the buff's item level > The buff expires at the start of their next round.

I observed three forms of buff misbehavior during full attacks, all using a two-attack full attack:
- When the full attack is made, two buffs are added to the Buffs tab. One has an item level set, is activated automatically, and behaves normally. The other does not have an item level and is not automatically activated (and is therefore also not automatically deleted), but can be edited normally. If you activate Combat Expertise again while one or both of the buffs is still active, the older extant buff is updated with the new item level, but no new buffs are added. The updated buff deletes itself at the end of its duration, leaving no buffs active.
- When the full attack is made, two buffs are added to the Buffs tab. Neither has an item level set, and therefore neither grants any stat modifications. Neither buff is active. One of the two buffs can be made active and/or deleted, but the other cannot be activated, deleted, or edited. New activations of Combat Expertise apply the combat change featAttackBonus but do not apply the Combat Expertise buff by special action. Refreshing the game removes the malfunctioning buff and restores normal behavior.
- When the full attack is made, two buffs are added to the Buffs tab. One is activated and has an item level properly set. It expires normally after its duration elapses. The other has no item level, is inactive, cannot be edited or deleted, and prevents further applications of the Combat Expertise buff by special action, as described in the previous bullet.

I have not determined the conditions that cause each of the above cases. It is seemingly random, so I guess that it may be tied to some form of lag in my computer that prevents proper activation or logging of the buff.

In both of the cases in which the special action cannot apply a new copy of the buff, other buffs can still be applied as normal. The Combat Expertise buff can still be added from the World compendium, and is fully functional when applied that way.

I have attached a zip file containing one of the actors I tested this on, the feat I wrote, and the accompanying buff.
[Combat Expertise testing jsons.zip](https://github.com/Rughalt/D35E/files/6093466/Combat.Expertise.testing.jsons.zip)

**Comment by Rughalt** [comment]
Added a toggle so special action will be used only once (with first attack). Will be out in 0.92

![image](https://user-images.githubusercontent.com/802214/112610016-8534f180-8e1c-11eb-886f-17349b14f722.png)
