### ISSUE TITLE
Add optional "combat" changes for skill checks

### ISSUE THREAD

**Issue by freeformline** [Rughalt/D35E#404]
Please add support for letting feats/features add check-boxes and sliders to the skill roll dialog. This would make it easier for players to remember rarely-used conditional modifiers, such as bonuses to Spot secret doors, Survival bonuses while tracking, or the Dwarven racial Stonecunning bonus.

**Comment by Rughalt** [comment]
Added, will be out in 0.92
![image](https://user-images.githubusercontent.com/802214/113093146-9e101f00-91ef-11eb-985a-a268afd5b9d8.png)
