### ISSUE TITLE
Request Extend the slider mechanic to have multiple

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#405]
The slider mechanic is awesome, could it be possible to make this into multiple so the same way you can have multiple combat changes you could have multiple sliders

![image](https://user-images.githubusercontent.com/22633854/110221083-fb030880-7ec1-11eb-909e-dc3b69b80e1e.png)

**Comment by Straddlecat** [comment]
n sliders with range1, range 2 etc

**Comment by Rughalt** [comment]
After looking at the UI side of things, I think I can easily fit up to 4 sliders there - one in line, 3 below. Any more will be getting out of hand. Will max 4 sliders (1 base and up to 3 additional) be OK?

**Comment by Straddlecat** [comment]
Thats great

**Comment by Rughalt** [comment]
Will be out in 0.92
