### ISSUE TITLE
Allow embedded expressions in object references in special actions

### ISSUE THREAD

**Issue by freeformline** [Rughalt/D35E#408]
Please add syntax that will allow references to objects in special actions to be partially defined by variables in the game, such as @range selections made in combat changes.

This would, for example, allow special actions to add or reduce daily spell charges to a slider-defined spell level, rather than targeting a fixed spell level. 

Example code change: "Update add [value] to field data.attributes.spells.spellbooks.primary.spells.spell1.value on self" would be re-written as "Update add [value, possibly including an embedded expression] to field data.attributes.spells.spellbooks.primary.spells.spell[[embedded expression]].value on self".

**Comment by Rughalt** [comment]
Added special action "Eval <one line js code, where running actor is `actor`> on self". This allows to execute any JS code using special action (and it also can break anything! So beware!).
