### ISSUE TITLE
Token Action HUD shows all skills including those that the characters can't use

### ISSUE THREAD

**Issue by Eldintux** [Rughalt/D35E#409]
I've noticed that the Token Action HUD lists ALL skills including the ones that you need training in, even if the character has no training, from this the character can roll ANY skill. So for instance Decipher script is available to every one not just those who are trained, and nowhere on the HUD does it say the skill is not available. I know the HUD is not yours but I know you have been working with the author is it possible to either take untrained skills out of the HUD or at least add a marker to show that these should not be used - I have had a play with the js & have done the latter, but of course during the next update of the HUD that'll be over-written & I'll have to change it again. Many thanks

**Comment by Rughalt** [comment]
Fixed, will be PRd to TAH repo.
