### ISSUE TITLE
Bard (possibly others) Spells known is offset by +1 level

### ISSUE THREAD

**Issue by Mesignosis** [Rughalt/D35E#413]
![image](https://user-images.githubusercontent.com/68146147/110695457-05b0fb00-823e-11eb-9f44-525f16bbd803.png)
![image](https://user-images.githubusercontent.com/68146147/110695467-08135500-823e-11eb-8af0-fa58e90bc0db.png)
![image](https://user-images.githubusercontent.com/68146147/110695550-25482380-823e-11eb-8418-8da2ad7e4f52.png)

**Comment by Rughalt** [comment]
This is a problem not with class definition, but with display on char sheet. Fixed, will be out in 0.91
