### ISSUE TITLE
Gnomes are missing the racial +2 Craft (alchemy) bonus

### ISSUE THREAD

**Issue by ZosoDerGoldene** [Rughalt/D35E#414]

**Comment by ZosoDerGoldene** [comment]
ok, same for alchemy lab. And as far as I can see, this is cause by the fact that subskills are indexed instead of named, and that numbering scheme may vary per actor, so there's no way to reliably target that subskill. I guess e.g. some gnomes might not spend ranks in Craft (Alchemy) and therefore not have that particular subskill at all. In the class dialog, Craft (Alchemy) only becomes available as a target after explicitly creating it.

**Comment by Rughalt** [comment]
Yes, and I do not know a good way to work around it (there are few ideas I have, but no strikes me as brilliant). I will tinker with it however - maybe something will come to my mind.

**Comment by Rughalt** [comment]
Fixed gnomes with combat changes (the value won't show up on the char sheet, unfortunately, only when rolling). The alchemist lab is a "loot" type item and has to be accounted for manually.
