### ISSUE TITLE
Added formula to Measure Template

### ISSUE THREAD

**Issue by bigsexy420** [Rughalt/D35E#42]
I don't know if this is a foundry thing or a bug with 3.5, but I can't enter anything but whole numbers into the Measure Template field. If a spell has an area based on caster level and you enter something like [[40*(@cl)]] it reverts to 0 when you click outside the field.

**Comment by Rughalt** [comment]
This was added in one of the previous updates.

**Comment by Rughalt** [comment]
![image](https://user-images.githubusercontent.com/802214/146582441-3ea96be9-9a4f-4fcf-bd3d-daafc6573e52.png)
