### ISSUE TITLE
Add "Emission Angle" to item light sources

### ISSUE THREAD

**Issue by freeformline** [Rughalt/D35E#421]
The LotD/3.5 system currently supports light emission from inventory items, which works well for items like torches and hooded lanterns. However, some items, such as the bullseye lantern, provide light in a cone rather than a circle, so their light patterns cannot currently be reproduced in Foundry. Adding the "Emission Angle" option found in the vision and lighting options on tokens to items would allow for these items to be properly implemented in the LotD/3.5 system.

**Comment by Rughalt** [comment]
Added, will be out in 0.92
![image](https://user-images.githubusercontent.com/802214/112883110-1d0d3680-90ce-11eb-95ca-4e3ac5bd8a0d.png)
