### ISSUE TITLE
Knowledge Psionics is listed as a class skill and does not require training for all classes

### ISSUE THREAD

**Issue by Axecleft** [Rughalt/D35E#422]
![image](https://user-images.githubusercontent.com/73614995/111075021-546bc880-84bc-11eb-9c79-c2a202d143dd.png)

Knowledge skills require training to be used unless you are seeking general or common knowledge (DC 10 or lower).

**Comment by Rughalt** [comment]
As for class skill, new actors should have this fixed, it is also not set as class skill in all classes. For monsters in Compendium, I will fix them so if they do not have ranks, its not a class skill for them, if they have it is, and all will require training.

**Comment by Rughalt** [comment]
I mark this as closed, monsters will be fixed in #463
