### ISSUE TITLE
Bard feature 'Bardic Knowledge'

### ISSUE THREAD

**Issue by DavidAremaCarretero** [Rughalt/D35E#424]
**As a** sexy bard
**I want** bardic knowledge feature working
**so that** when my DM ask me for rolling my really vast knowledge about everything, I can click on the feature and my DM can give me all the information about that thing that I already know... 🙃

JK. Opening feature request for bardic knowledge, can be find here:

https://www.d20srd.org/srd/classes/bard.htm

Bardic Knowledge
A bard may make a special bardic knowledge check with a bonus equal to his bard level + his Intelligence modifier to see whether he knows some relevant information about local notable people, legendary items, or noteworthy places. (If the bard has 5 or more ranks in Knowledge (history), he gains a +2 bonus on this check.)

A successful bardic knowledge check will not reveal the powers of a magic item but may give a hint as to its general function. A bard may not take 10 or take 20 on this check; this sort of knowledge is essentially random.

DC	Type of Knowledge
10	Common, known by at least a substantial minority of the local population.
20	Uncommon but available, known by only a few people legends.
25	Obscure, known by few, hard to come by.
30	Extremely obscure, known by very few, possibly forgotten by most who once knew it, possibly known only by those who don’t understand the significance of the knowledge.

It might be cool to be rolling against the table, but that's lowest priority for me.

**Comment by Rughalt** [comment]
Fixed, will be out in 0.92
