### ISSUE TITLE
Action Button is Gone for some abilities

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Rughalt/D35E#425]
![image](https://user-images.githubusercontent.com/24766235/111079401-e0372200-84c7-11eb-8297-efd4c2b6b4e7.png)

Some actions that had a action button before seem to be gone. I can still "use" them via Token Action HUD.

![image](https://user-images.githubusercontent.com/24766235/111079451-12e11a80-84c8-11eb-97d2-4aad299b2e91.png)

**Comment by Rughalt** [comment]
I would be glad if you could export that one ability and put json here! Thanks!

**Comment by Cosmic-Lattee** [comment]
Had to zip it to load it up on here.

[fvtt-Item-Dark_Knowledge.zip](https://github.com/Rughalt/D35E/files/6137741/fvtt-Item-Dark_Knowledge.zip)

**Comment by Rughalt** [comment]
If this item *really* was clickable before, I would be glad for more info and reopen :)
