### ISSUE TITLE
Unarmed strike not usable from Unarmed strike 'item'

### ISSUE THREAD

**Issue by Mesignosis** [Rughalt/D35E#426]
![image](https://user-images.githubusercontent.com/68146147/111130796-bcf59b00-85cb-11eb-9584-7a82c4ca8b04.png)
it's in the inventory I create an attack and it shows like above
![image](https://user-images.githubusercontent.com/68146147/111130826-c1ba4f00-85cb-11eb-8ad1-3d817120b94c.png)

**Comment by Rughalt** [comment]
This is because Unarmed Strike is unequipped. This requires code change, will be addressed in 0.92

**Comment by Rughalt** [comment]
Unarmed strike should be fixed in 0.92 - Added as an attack directly.
