### ISSUE TITLE
Apply half damage with no check is applying Full Damage

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#428]
0.91

![image](https://user-images.githubusercontent.com/22633854/111372354-71f28b00-8692-11eb-9673-251490c842a8.png)
So lets say you are in a situation when you want to apply the damage but you dont want to check against the roll for hit against AC, so just applying straight damage.  When clicking apply 1/2 then clicking no check in the damage dialog it is still applying full damage to a token

**Comment by Rughalt** [comment]
Fixed, clickins Apply Half will automatically select "Apply Half Damage" in dialog box. Will be out in 0.92
