### ISSUE TITLE
Damage Ability choice not remembered in Attack dialog

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#429]
I keep setting "Damage Ability" to x1.5 for the same attack that i select from Character Sheet > Combat > All

![SNAG-1017](https://user-images.githubusercontent.com/55966777/111400228-45903c00-869d-11eb-9673-520c4e7cfc19.png)

console log after invoking attack dialog to output being displayed in chat log:
---
entity.js:1755 {data: {…}, id: "rkQ3eDCtOcJIUsBv", item: {…}, rollMode: "roll", rollModes: {…}, …}
foundry.js:4503 Foundry VTT | Rendering Dialog
VM17800:11 All fields from save are loaded
entity.js:1412 D35E | Enabled conditionals []
entity.js:1912 D35E | Calculated spell DC {dc: null, type: null, description: null, cl: 0}
entity.js:1610 D35E | Updating item on attack.
entity.js:3410 D35E | Item updates []
entity.js:3539 D35E | ActorPF | _updateExp | Update exp data from class level count 2
entity.js:3541 D35E | ActorPF | _updateExp | Race LA, racial HD, level 0 0 2
entity.js:1640 D35E | Generating chat message.
entity.js:1918 D35E | Setting attributes hd total | 2
entity.js:2289 D35E | Setting attributes hd total | 2
foundry.js:29510 Foundry VTT | Created ChatMessage with id ciwANoXRNb3p8ZDT
base.js:781 D35E | Item Browser | Loading pack inline browser on load
---
actor json: [fvtt-Actor-Numb.zip](https://github.com/Rughalt/D35E/files/6153085/fvtt-Actor-Numb.zip)
line 1534 shows size = med.  a bit confusing, as when i inspect the race attached to the actor it looks like this:
![SNAG-1018](https://user-images.githubusercontent.com/55966777/111400851-8fc5ed00-869e-11eb-8d6d-37851f6a0683.png)

**Comment by Rughalt** [comment]
As discussed on Discord, tooltip and icon near Ability multiplied dropdown will change as it depends on Wield Mode dropdown value
