### ISSUE TITLE
equipment value total gives away value of unidentified items, doesn't change when items changed to unID'd

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#430]
![SNAG-1019](https://user-images.githubusercontent.com/55966777/111403833-14ffd080-86a4-11eb-921b-02b1bf208678.png)
this character has two items worth 100gp and 150gp each.  when i change the two items to Unidentified, the total value does not drop.
actor JSON: [fvtt-Actor-Numb.value-total.zip](https://github.com/Rughalt/D35E/files/6153249/fvtt-Actor-Numb.value-total.zip)
the two trade items defined as such:
![SNAG-1021](https://user-images.githubusercontent.com/55966777/111404110-99eaea00-86a4-11eb-9416-7a6d11a748cf.png)
![SNAG-1020](https://user-images.githubusercontent.com/55966777/111404112-9a838080-86a4-11eb-8661-a48d7d95e212.png)

line 7416 in the JSON

`        "price": 150,
        "identified": false,
...
       "unidentified": {
          "price": 0,
          "name": "Emerald Earring"
        },
`

and line 7483

`        "price": 100,
        "identified": false,
        "hp": {
          "max": 10,
          "value": 10
        },
        "hardness": 0,
        "carried": true,
        "unidentified": {
          "price": 0,
          "name": "Gold Bracelet"
        },
`

**Comment by Rughalt** [comment]
Does this appear even if you log in as player? As a GM you always see total value.

**Comment by wmve** [comment]
that completely slipped my mind.  player sees correct value.  **issue can be closed.**
![image](https://user-images.githubusercontent.com/55966777/111483038-d05b5000-870a-11eb-9edb-87dafc33e801.png)
