### ISSUE TITLE
unidentified magic item reveals spell-like properties in player's sheet

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#431]
**steps to reproduce:**

1. clone standard Ring of Nine Facets 
2. change description
3. add Spell Uses on Enhancements tab
4. add to player's inventory
5. check player's inventory in connection through firefox

**expected behaviour:** 
- should not see any of the spell uses

**actual behaviour**
- see spell uses

**notes**
magic item displays all the spell like properties, but the item is marked as "unidentified"
![image](https://user-images.githubusercontent.com/55966777/111570433-37185200-877b-11eb-80dd-591d03c6480a.png)
![image](https://user-images.githubusercontent.com/55966777/111570454-45666e00-877b-11eb-9eab-5f303796c8ec.png)
![image](https://user-images.githubusercontent.com/55966777/111570473-4f886c80-877b-11eb-9efd-858ffa24d88f.png)

here's appearance in inventory for GM:

![SNAG-1034](https://user-images.githubusercontent.com/55966777/111570341-06381d00-877b-11eb-8484-ed9d43533784.png)

here's appearance for player:

![SNAG-1033](https://user-images.githubusercontent.com/55966777/111570246-bd806400-877a-11eb-96ba-122d1ac84a85.png)

here's the JSON for actor and item:
[fvtt-Actor-Neahman-shows-unid-props.zip](https://github.com/Rughalt/D35E/files/6161198/fvtt-Actor-Neahman-shows-unid-props.zip)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.92
