### ISSUE TITLE
Allow taking half damage from particular energy types

### ISSUE THREAD

**Issue by Heliomance** [Rughalt/D35E#432]
The [Fire Shield](https://www.d20srd.org/srd/spells/fireShield.htm) spell makes the target take half damage from the caster's choice of fire or cold energy. There is currently no way to model this in the system - could it be added?

**Comment by Rughalt** [comment]
This will be added in 0.92, but for fire shield example, it should be done by DM when applying damage (Selecting Half/None), as this works more like Improved Evasion but only for Fire/Cold damage (very complex behavior). https://www.dandwiki.com/wiki/SRD:Evasion_and_Improved_Evasion
