### ISSUE TITLE
Feature request: Show non-active class features on character sheet

### ISSUE THREAD

**Issue by Heliomance** [Rughalt/D35E#433]
Currently, non-active class features are not displayed anywhere on the character sheet. To see them, you have to click down into the class window and go to the full class description. It would be useful if there was a section of the character sheet that detailed all class abilities, with their explanatory text, whether active or not.

**Comment by Rughalt** [comment]
Added, will be out in 0.92.2
![image](https://user-images.githubusercontent.com/802214/113904954-e96b9400-97d2-11eb-831e-c4db2ae492f5.png)
