### ISSUE TITLE
Character sheet dice roll problem

### ISSUE THREAD

**Issue by Nmaria41100** [Rughalt/D35E#435]
[fvtt-Actor-Kaori_Nozomi_(Copy).zip](https://github.com/Rughalt/D35E/files/6177533/fvtt-Actor-Kaori_Nozomi_.Copy.zip)

I have issues with the saving throws and attack throw, in the console show that the throw is been made, but instantly dissapear and dont show anything in the chat or any result in the console. Can you help me plis :(

**Comment by Rughalt** [comment]
I think this was resolved and was an issue with an actor itself. Please reopen if not!
