### ISSUE TITLE
Jump and High Speed

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Rughalt/D35E#439]
Currently your speed doesn't change your jump bonus.

![image](https://user-images.githubusercontent.com/24766235/111961137-a618e200-8abe-11eb-927c-3f39f177a8dd.png)

This seems to just be pre-added into monster stat blocks. See something like the Fleshraker (MM3 page 40) as a example of this.

I _think_ Tiny Monstrous Spider is a example as well (https://www.d20srd.org/srd/monsters/monstrousSpider.htm) because they should have a -8 due to strength and 20 foot move speed (having slow speeds lowers the jump bonus). I am guessing they have a -4 because the dumb spider put 4 of it's skill points into jump. I _think_.

**Comment by Rughalt** [comment]
Added, will be out in 0.92 (enabled by default for chars, not for npcs).
