### ISSUE TITLE
[Implementation] Tumble and Total Defense

### ISSUE THREAD

**Issue by Grotzmaul** [Rughalt/D35E#441]
In the SRD, 5+ ranks in tumble grants a bonus to the dodge AC granted by total defense and when fighting defensively
The rule:
If you have 5 or more ranks in Tumble, you gain a +3 dodge bonus to AC when fighting defensively instead of the usual +2 dodge bonus to AC.
If you have 5 or more ranks in Tumble, you gain a +6 dodge bonus to AC when executing the total defense standard action instead of the usual +4 dodge bonus to AC.

PS. There's also the epic skill version for this rule: A character with 25 or more ranks in Tumble gains a +5 dodge bonus when executing the fight defensively standard or full-round action, instead of a +2 bonus (or the +3 bonus from having 5 or more ranks). Increase this dodge bonus by +1 for every 10 additional ranks above 25 the character has. A character with 25 or more ranks in Tumble gains a +10 dodge bonus to AC when executing the total defense standard action, instead of a +4 bonus (or the +6 bonus from having 5 or more ranks). Increase this dodge bonus by +2 for every 10 additional ranks above 25 the character has.

**Comment by Rughalt** [comment]
Added, both normal and epic. Will be out in 0.92
![image](https://user-images.githubusercontent.com/802214/112671424-6ce7c580-8e62-11eb-9af5-090cdc0e1fb7.png)
