### ISSUE TITLE
Request: Miss Chance

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Rughalt/D35E#442]
Being able to add miss chance as a Change on items/abilities would be nice. So that way Cloaks of Displacement can be automated.

Also having it be something you can modify like Spell Resistance or Fortification would also be cool. I am sure there are monsters out there with miss chance.

**Comment by Rughalt** [comment]
Added, will be out in 0.92.2 - Added Concealment field to actor that can be changed using Changes.
