### ISSUE TITLE
Etherealness enchantment bug

### ISSUE THREAD

**Issue by Leaguescience** [Rughalt/D35E#447]
Etherealness is 49000 and +5 is 26650 for full plate, total = 75650, but when i add the Etherealness to the armor it now cost 900251650 gold....
![Etherealness](https://user-images.githubusercontent.com/33700136/112746194-639e4c00-8f7b-11eb-9dc1-205e36c696f0.PNG)

**Comment by Rughalt** [comment]
Fixed, will be ou tin 0.92
