### ISSUE TITLE
See the roll of HP when a character levels up

### ISSUE THREAD

**Issue by Jarlok2** [Rughalt/D35E#448]
When a character levels up it has to roll the HP dice but the GM can't see it. I would like to see in the chat the result of that roll.
Thanks.

**Comment by Rughalt** [comment]
Will be out in 0.92.2
![2021-04-07 17 56 58](https://user-images.githubusercontent.com/802214/113896994-c0df9c00-97ca-11eb-92d6-29dacf50203a.gif)
