### ISSUE TITLE
Power Attack on macro attacks

### ISSUE THREAD

**Issue by felippemontez** [Rughalt/D35E#46]
When selecting the option "power attack", it is calculating automatically.
For example, for a lvl 20 fighter (base attack +20), Power Attack is removing -6 from the attack roll.

![image](https://user-images.githubusercontent.com/65147904/91609471-e14e9a80-e94d-11ea-8bc5-27a5c295218f.png)

**Comment by Rughalt** [comment]
What would correct calculation be? I need more info/possible resolution. Do you want a dropdown with possible power attack values?

**Comment by felippemontez** [comment]
Hi Rughalt! Thanks for answering.

The Power Attack rule is below.
My suggestion is that we could have a dropdown with possible power attack values (any value from 1 to the current Base Attack Bonus). This value would be subtracted from the attack, and added to the damage roll. If we can't do the check automatically for "two handed weapons", we could have a check button to select "two handed mode".

Example:

We select -2 on the power attack dropdown menu.
If "two-handed mode" in unchecked, it adds 2 points of damage to the roll. If this option is checked, it adds 4 points of damage.



**Power Attack [General]**
Prerequisite
Str 13.

***Benefit***
_On your action, before making attack rolls for a round, you may choose to subtract a number from all melee attack rolls and add the same number to all melee damage rolls. This number may not exceed your base attack bonus. The penalty on attacks and bonus on damage apply until your next turn._

***Special***
_If you attack with a two-handed weapon, or with a one-handed weapon wielded in two hands, instead add twice the number subtracted from your attack rolls. You can’t add the bonus from Power Attack to the damage dealt with a light weapon (except with unarmed strikes or natural weapon attacks), even though the penalty on attack rolls still applies. (Normally, you treat a double weapon as a one-handed weapon and a light weapon. If you choose to use a double weapon like a two-handed weapon, attacking with only one end of it in a round, you treat it as a two-handed weapon.)_

**Comment by Rughalt** [comment]
I'll add slider with values from 0 to BAB, and I could possibly add field to attack indicating if it is two weapon/primary/off-hand/light etc, so changes would be also applied automatically.

**Comment by felippemontez** [comment]
Sounds like a great solution, thank you very much! 👍
