### ISSUE TITLE
racial HD bug sheet

### ISSUE THREAD

**Issue by Leaguescience** [Rughalt/D35E#469]
the resistance and DR sections are bugged, heres what happens
![Construct 1 bug](https://user-images.githubusercontent.com/33700136/114835192-4fda4e80-9d9f-11eb-8beb-dcfd86107ce3.PNG)
adding DR
![Construct 2 bug](https://user-images.githubusercontent.com/33700136/114835392-83b57400-9d9f-11eb-9d55-cfa8939dd4ab.PNG)
when i add slashing this happens
![Construct 3 bug](https://user-images.githubusercontent.com/33700136/114835637-c70fe280-9d9f-11eb-9970-9569e673c4f6.PNG)
now if i click immunity on slashing it does this
![Construct 4 bug](https://user-images.githubusercontent.com/33700136/114835794-f32b6380-9d9f-11eb-95c3-7555ecf5e3e6.PNG)
heres with more
![Construct 5 bug](https://user-images.githubusercontent.com/33700136/114835938-19510380-9da0-11eb-9ecc-8c1313395a6b.PNG)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.92.3
