### ISSUE TITLE
Base attack Bonus on Epic levels

### ISSUE THREAD

**Issue by felippemontez** [Rughalt/D35E#47]
The BAB progression is increasing on levels above 20, while it shouldn't according to the Epic level rules.

A Fighter with lvl 24 should have BAB +20 and another +2 Epic attack bonus, and not +24 BAB.
Currently, due to the high base attack, the character can make 5 (or more) attacks, while the maximum should be 4 attacks for a Fighter at level 20.

_"Epic Attack Bonus
Similarly, the character’s base attack bonus does not increase after character level reaches 20th. However, the character does receive a cumulative +1 epic bonus on all attacks at every odd-numbered level beyond 20th, as shown on Table: Epic Save and Epic Attack Bonuses. Any time a feat, prestige class, or other rule refers to your base attack bonus (except for gaining additional attacks), use the sum of your base attack bonus and epic attack bonus."_

https://www.d20srd.org/srd/epic/basics.htm#epicAttackBonus

![image](https://user-images.githubusercontent.com/65147904/91609788-705bb280-e94e-11ea-9c90-cabc8070c53a.png)

**Comment by Rughalt** [comment]
Added Epic Saving Throw and Attack progression when not using Fractional Progression alternate rule.
