### ISSUE TITLE
Buff symbols on Tokens

### ISSUE THREAD

**Issue by Eldintux** [Rughalt/D35E#471]
At present everyone can see Buff symbols on the tokens of evryone. Is it possible to turn this off, make them GM only or make them owner & GM only. Asking as Players can see Buffs on NPC's and sometimes these Buffs are not obvious. Many thanks

**Comment by Rughalt** [comment]
Per buff toggle was already in the system:

Added per actor toggle:
![image](https://user-images.githubusercontent.com/802214/115982550-4cfc0c80-a59c-11eb-8bf7-914563e78387.png) I am still exploring if its possible to hite it per client but it may be limited by how foundry deal with that.

**Comment by Rughalt** [comment]
This was added in one of the subsequent updates.
![image](https://user-images.githubusercontent.com/802214/146587880-3945fafa-a2b5-4a97-9edf-e77b8371211e.png)
