### ISSUE TITLE
Resistance and Damage Reduction in Changes Tab not refering to things outside of itself such as Class

### ISSUE THREAD

**Issue by Mesignosis** [Rughalt/D35E#472]
![image](https://user-images.githubusercontent.com/68146147/115021673-9cd53680-9eff-11eb-9376-b0e2a850c3f4.png)

**Comment by Mesignosis** [comment]
The Class feature can't read the level of the class it is in

**Comment by Rughalt** [comment]
Fixed. Should work with all existing items that use either @enh or @levels field, plus now has access to full actor rollData. Please report any regressions.
