### ISSUE TITLE
Unarmed Strike (Monk) stops working after adding Weapon Focus

### ISSUE THREAD

**Issue by Revq** [Rughalt/D35E#475]
Unarmed Strike (Monk) completely stops working after adding Weapon Focus feat to a character sheet. Even without anything typed in required field.

[Character Sheet](https://www.mediafire.com/file/bbibo9dhug1kbz6/fvtt-Actor-Tesco.json/file)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.92.3. Feat to function will require removing it from monk, so updated version is put in its place. Weapon Focus should use just "Unarmed Strike" name
