### ISSUE TITLE
human skill point not added at lvl 1 and at each level

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#477]
each level a human should get a +1 additionnal bonus and at level 1 he should get a +4 skill bonus

![image](https://user-images.githubusercontent.com/74456344/115963016-ec14fb80-a4eb-11eb-81ee-f10b7a1e3e84.png)

As seen in this example this human get 8 only he's priest so (2+Int) x 4 but should have 12 with the +4 of human (he have +0 Int)

![image](https://user-images.githubusercontent.com/74456344/115963072-2d0d1000-a4ec-11eb-9b97-0fef4ac4d715.png)

And each additionnal level he should have 3 but he only have 2 ( 2 +0 Int)  he should have 3  (2 +0 Int +1 human)

![image](https://user-images.githubusercontent.com/74456344/115962969-b6701280-a4eb-11eb-96d8-52ea82942ef9.png)

**Comment by Dany-Deaneris** [comment]
After some test, it seems it's only my old character that have this issues and new created character seems fine.

**Comment by Rughalt** [comment]
Can be added manually by either replacing human race on character or setting following field on Human race on character
![image](https://user-images.githubusercontent.com/802214/115981837-1cfe3a80-a597-11eb-8e8e-b4a95d156a69.png)
