### ISSUE TITLE
Spellcasting Prodigy - feat - bonus in "Spellcasting Ability" for a given spellbook

### ISSUE THREAD

**Issue by ramondsa** [Rughalt/D35E#478]
Possibility to add a special change/bonus in "Spellcasting Ability" for a given spellbook

**Comment by Rughalt** [comment]
Added, will be out in 0.93
![image](https://user-images.githubusercontent.com/802214/120114937-c8e00a80-c181-11eb-824f-e8eb49be4466.png)
