### ISSUE TITLE
Spells for Multiclass casters are placed under the primary caster.

### ISSUE THREAD

**Issue by bigsexy420** [Rughalt/D35E#48]
When adding spells for a secondary spell caster the spells appear under the primary spell casters list.
![image](https://user-images.githubusercontent.com/1043352/91647829-410f7900-ea14-11ea-90f0-fe10f84f9cdb.png)
Call Lighting is a Druid Spell
![image](https://user-images.githubusercontent.com/1043352/91647823-348b2080-ea14-11ea-893d-449fa1c904ad.png)
Yet it appears under the Wizard primary Spell casting
![image](https://user-images.githubusercontent.com/1043352/91647839-6c926380-ea14-11ea-95fb-f0165511e37f.png)
And nothing under the secondary tab for Druid Spells

**Comment by bigsexy420** [comment]
Adding spells via the Summary tab defaults spells to the primary caster, even if they don't have the spell on their list. Adding spells via the Spells tab, places them on which ever tab is selected at the time. 

Not really a bug but a future feature request, spells get sorted not only by level but also by caster.

**Comment by Rughalt** [comment]
I'm going to extend this feature so if you drop spell:
- item tab - create scroll window
- spellbook - add spell but show warning if character cannot learn this spell (as GM can allow anything)
- anywhere else - on spellbook for correct class (first one found) - if not found, on primary spellbook (with warning)
