### ISSUE TITLE
Display special names for feats in "optional" Action Types

### ISSUE THREAD

**Issue by BernhardHH** [Rughalt/D35E#481]
When setting an optional "Combat Change", it would be great to have an optional name for the feat which would be displayed there.

Example: the feat is called "Battle Clarity" (adds INT modifyer to REF save, unless flatfooted), but in the Ref roll window it would be better to have the option named "Flatfooted (BC)" or similar. Also makes sense if the feat only works on flatfooted enemies.

**Comment by Rughalt** [comment]
Added both custom names for chatcard *and* for dialogs (can be different). Will be out in 0.93
![2021-05-30 20 20 51](https://user-images.githubusercontent.com/802214/120115599-a8fe1600-c184-11eb-971d-e173ff017796.gif)
