### ISSUE TITLE
an idea we got for spell caster with a lot of spell

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#485]
![image](https://user-images.githubusercontent.com/74456344/116770492-6bd22700-aa12-11eb-965d-c9a29fbc2348.png)

It would be fun to hide spell of the day we did not prepared.  For class as cleric, mage.  Maybe  a button to hide/show those spell.

**Comment by Rughalt** [comment]
Added, will be out in 0.93

**Comment by Rughalt** [comment]
![2021-05-27 18 50 30](https://user-images.githubusercontent.com/802214/119865974-91245900-bf1c-11eb-9711-9cd4fd04ad1b.gif)
