### ISSUE TITLE
improvement for special action

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#490]
Would be nice for special action to be able to send a message to GM for the choice made by the player.

"MessageGM 'text'" 

So imagine a player could choose one of those but the message send to GM is different.  Could even be used for enigma or special spell as summon monster etc.
![image](https://user-images.githubusercontent.com/74456344/117061256-f4d9ae80-acef-11eb-9150-77db4ec3d244.png)

**Comment by Rughalt** [comment]
Added, will be out in 0.93
Special action is `Message <type> text is text is text on self/target`. Type can be `public`, `gmroll` etc
![2021-05-18 18 13 36](https://user-images.githubusercontent.com/802214/118687139-f71a2d80-b804-11eb-9a76-129c50f7d5dc.gif)
