### ISSUE TITLE
Display Max Power Points

### ISSUE THREAD

**Issue by BrianRyan245** [Rughalt/D35E#495]
Would be nice to have a field that displays Max Power Points per day alongside the Power Points section so that you could see how many you have remaining of your total. This is useful for classes such as Psions and classes that use "Ki Points" like power points such as Ninja.

**Comment by Rughalt** [comment]
![image](https://user-images.githubusercontent.com/802214/118362205-dc3e8380-b58e-11eb-89b2-da36fc291af7.png)
Added, will be out in 0.93
