### ISSUE TITLE
Throwing weapon 

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#499]
![image](https://user-images.githubusercontent.com/74456344/117555706-8cf8d000-b02f-11eb-8ece-f3fc9bc045ce.png)

Throwing weapon have many form but not all weapon are throw as this club is a throwing weapon, but when attacking it remove the weapon as if it was throw, but if the player just want to use it as melee weapon he need to add it again in his inventory.  Could there be a possibility to have throwing weapon a button or something when used with action so we choose if we throw or melee with it.

**Comment by Rughalt** [comment]
Throwing weapon creates 2 attacks now, one for thrown attack and one for melee.
