### ISSUE TITLE
creature invisible still visible by player

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#500]
i just see another bug
this boar should be invinsible, the DM push the invisible button and i still can see it.  It seems to only be creature hidden that are still visible.  But a token of a tree that was invisible was really invisible.
![image](https://user-images.githubusercontent.com/74456344/117556394-7013cb00-b036-11eb-8743-ce6d88fef648.png)

**Comment by Rughalt** [comment]
This turned out to be incompatibility with a module.
