### ISSUE TITLE
need Monk-type abilities to be useable for user-created monk-type classes

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#504]
some plumbing uses @classes.monk.level.  i am trying to design an alternate monk class, and would like to "pretend to be a monk" for the purposes of some of this plumbing, like flurry of blows, unarmed strike damage, etc.

![image](https://user-images.githubusercontent.com/55966777/117860487-594fbd00-b25e-11eb-8cf2-17de6af17c6f.png)

i can reproduce this message just by hitting F5 refresh.

here's a copy of what this class looks like currently and a couple of NPCs created as such, but i am still getting the error message above and not exactly sure why.

[Sarlet_Sohei-entities.zip](https://github.com/Rughalt/D35E/files/6461017/Sarlet_Sohei-entities.zip)

**Comment by wmve** [comment]
Rugalt indicates that entering the value "monk" in the tag of the class on the character fixes this.

![image](https://user-images.githubusercontent.com/55966777/117878401-b7d36600-b273-11eb-85ae-756a9bae4334.png)

i no longer get the error.  i haven't finished functional testing of this actor yet.

**Comment by Rughalt** [comment]
This is indeed they correct way to work around this if you do not want to have to copy abilities and map them to new class. This unfortunately has one caveat - hero with class with this custom tag cannot also have Monk class on itself.

**Comment by wmve** [comment]
that's fine because i wouldn't assign such character monk levels.  it is indeed an exclusive monk-replacement class for npcs.
