### ISSUE TITLE
Non-active Class Features not populating

### ISSUE THREAD

**Issue by BrianRyan245** [Rughalt/D35E#505]
Non-active class features show fine in the class progression area of the description, but they do not populate on the character sheet when leveling up. All active class features populate upon progression.

![Character](https://user-images.githubusercontent.com/83768067/117955846-15040180-b2de-11eb-8076-05f17b342b46.JPG)
![Class](https://user-images.githubusercontent.com/83768067/117955858-18978880-b2de-11eb-826b-c05a0dc6c7d0.JPG)

**Comment by Rughalt** [comment]
Fixed, will e out in 0.93
