### ISSUE TITLE
FR: Add in the ability to place Class Abilities (and others) into a Shared Data Module

### ISSUE THREAD

**Issue by Eldintux** [Rughalt/D35E#506]
At present New Class Abilities for Homebrew have to be placed in a compendium in the world you're working in. Some of us work in multiple worlds & use a module to share compendiums between them. It would be great if the module could contain a compendium named the same & have the same functionality. eg Class Abilities (SharedData) works the same as Class Abilities (world)

**Comment by Rughalt** [comment]
Modules can now import and leverage functions `addRacialAbilitiedFromPackToCache` and `addClassAbilitiesFromPackToCache` from /systems/D35E/cache.js to add things to cache. Will be out in 0.93.

Example to follow
