### ISSUE TITLE
Custom item with charges throws console error

### ISSUE THREAD

**Issue by BernhardHH** [Rughalt/D35E#508]
Tried to set up a healing belt with&without Pool:

![image](https://user-images.githubusercontent.com/20403145/118331424-ee75de80-b508-11eb-8020-5fdc47196d6e.png)

entity.js:1863 Uncaught (in promise) TypeError: Cannot read property 'type' of null
    at ItemPF.useAttack (entity.js:1863)
    at ItemPF.use (entity.js:1129)
    at ItemPF.useEnhancementItem (entity.js:3658)
    at ItemSheetPF._quickItemActionControl (base.js:1918)
    at HTMLAnchorElement.<anonymous> (base.js:1045)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)
useAttack @ entity.js:1863
use @ entity.js:1129
useEnhancementItem @ entity.js:3658
_quickItemActionControl @ base.js:1918
(anonymous) @ base.js:1045
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
async function (async)
_quickItemActionControl @ base.js:1918
(anonymous) @ base.js:1045
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

Attached the JSON.
[fvtt-Item-Healing_Belt.zip](https://github.com/Rughalt/D35E/files/6481197/fvtt-Item-Healing_Belt.zip)

**Comment by Grotzmaul** [comment]
I would like to add to this issue what I discovered today. First, when added a spell with conditionals based on the caster level, like cure wounds the formula uses the atribute @enhancement for the CL, but the attribute for the CL is @data.enh inside the Enhancement item data. The second issue is that when an item is created, is created with a random _id. That random _id interfere with the _id of the spell added with the enhancement system.

**Comment by Rughalt** [comment]
This probably was fixed along with fixes to how the spells in items work.
