### ISSUE TITLE
Error trying to open a character's sheet.

### ISSUE THREAD

**Issue by omegaghost** [Rughalt/D35E#513]
This ticket refers to a particular world sent to Rughalt's DMs. Foundry version 0.8.5, 3.5SRD version 0.93-beta2.

I get this error upon trying to open the character sheet of character "Cat" (the one in "Characters" folder)
![image](https://user-images.githubusercontent.com/7759628/119230765-4c687e80-bb26-11eb-81ce-df9f177a7f8a.png)

The other "Cat" character (outside of the folder) is fine.

**Comment by Rughalt** [comment]
Fixed, related to a bug in character. The fix will ignore the wrong value, allowing the char sheet to open. Persisting to the database should clear up value according to docs.
