### ISSUE TITLE
Error trying to move characters

### ISSUE THREAD

**Issue by omegaghost** [Rughalt/D35E#514]
This ticket refers to a particular world sent to Rughalt's DMs. Foundry version 0.8.5, 3.5SRD version 0.93-beta2.

This is the error I get trying to move either "Etellorion" or "Terga" characters.
![image](https://user-images.githubusercontent.com/7759628/119231285-c26de500-bb28-11eb-8683-47a26b8cca90.png)
![image](https://user-images.githubusercontent.com/7759628/119231288-c568d580-bb28-11eb-9aa2-5e7afa78175d.png)

**Comment by Rughalt** [comment]
Fixed, related to ternary operations breaking in 0.8.X. Patched core to roll ternary operations corretly
