### ISSUE TITLE
Attacks have no visible description on their list.

### ISSUE THREAD

**Issue by omegaghost** [Rughalt/D35E#517]
All attacks (newly created or converted from earlier versions) lack visible description on their list, although it does exist if you try to edit it or view it from a character's sheet.

![image](https://user-images.githubusercontent.com/7759628/119231440-9c951000-bb29-11eb-9f2c-0992b6ef26c1.png)

3.5SRD version 0.93-beta2.

**Comment by Rughalt** [comment]
Fixed, related do data structure change in core
![image](https://user-images.githubusercontent.com/802214/119248670-0b5a8380-bb93-11eb-9e5c-03f84d2e75a7.png)
