### ISSUE TITLE
Error adding class levels

### ISSUE THREAD

**Issue by omegaghost** [Rughalt/D35E#518]
There is an error that appear upon adding class levels via level progression. It results in no class level being added to total progression, but one level is still added to the particular class chosen.

![image](https://user-images.githubusercontent.com/7759628/119231774-4032f000-bb2b-11eb-89bf-6a1f2c70ad2e.png)

It doesn't appear on all classes. Barbarian and Druid get the error, Fighter and all NPC classes don't. I can't seem to find a particular link between those.

3.5SRD version 0.93-beta2.

**Comment by Rughalt** [comment]
Fixed, caused by a change to data structure in core.
