### ISSUE TITLE
Error when opening level up window.

### ISSUE THREAD

**Issue by omegaghost** [Rughalt/D35E#519]
There is an error that appears in console (but for some reason only about 90-95% of the time) upon opening your character's level up window. Fortunately it doesn't seem to result in any abnormalities.

![image](https://user-images.githubusercontent.com/7759628/119231911-c64f3680-bb2b-11eb-9b8d-b2f88735fa27.png)

3.5SRD version 0.93-beta2.

**Comment by Rughalt** [comment]
Fixed - error was caused by wrong initial state of the window.
