### ISSUE TITLE
Error on boot up with Familars

### ISSUE THREAD

**Issue by Eldintux** [Rughalt/D35E#520]
Error message from all Wizard Familiars tested about a formula error when booting into a world. Have tested migrating from Foundry 0.7.9 & newly created wizard (Familiar taken from Compendium) and finally new wizard with a freshly created familiar by taking an animal from the compendium & adding Wizard Familiar Class 

![Error message](https://user-images.githubusercontent.com/75202428/119242924-088f6c80-bb5a-11eb-9a39-cdf0e4053109.png)

![F12](https://user-images.githubusercontent.com/75202428/119242926-0decb700-bb5a-11eb-8711-d0f0bea0f7ea.png)

**Comment by Rughalt** [comment]
Yellow things are warnings - will be dealt before 0.9.0 hits.
 Possible other errors, related to ternary operators being broken - are fixed by patching the function.
