### ISSUE TITLE
Spells with Templates don't appear to cast

### ISSUE THREAD

**Issue by Eldintux** [Rughalt/D35E#521]
Done several tests on both Religious & Arcane Spells, if they have a template the spell simply doesn't cast. Spell slot not used (spell points not spent). Disable the template & the spell casts fine (Foundry 0.8.x, D35E 0.93-Beta3)

**Comment by Rughalt** [comment]
Fixed, along with other problems with measureTemplates (port from PF1e system by Furyspark)
