### ISSUE TITLE
@attributes.bab.value is not recognize in buffs

### ISSUE THREAD

**Issue by Tanky06** [Rughalt/D35E#522]
In the formula @details.level.value - @attributes.bab.value, it doesn't substract the BAB. 
If I change the formula to @attributes.bab.value alone, it doesn't do anything.

![BAB Buffs](https://user-images.githubusercontent.com/84699607/119302303-e36e2d00-bc31-11eb-8217-917bb537b6ae.png)

**Comment by Rughalt** [comment]
Closing along with #713
