### ISSUE TITLE
FR-Formulas in Item Value stat

### ISSUE THREAD

**Issue by Axecleft** [Rughalt/D35E#523]
I would like the ability to set a formula that will roll a random value for the item each time that it is dropped into inventory with in the formula range. 

This would allow the creation of base value items like gems with a base value of 10 GP that could have a actual value of (((1d100)+50)/100)baseValue for a value range of 5-15 GP

**Comment by Rughalt** [comment]
To keep this feature lightweight, for now, you can only do simple rolls without references to the item or the actor. Creation changes are removed from the item once it's added to the actor to prevent further changes on drag and drop.
![2021-06-04 11 14 00](https://user-images.githubusercontent.com/802214/120779213-262fdf00-c527-11eb-8410-86075f057800.gif)
