### ISSUE TITLE
FR: change weights on items depending on character size

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#526]
**resize inventory items to character _when they are first acquired_ from compendium or local items collection**
- do not resize when they come from other characters
- (might make sense to simply boil this down to "resize when it doesn't come somewhere with a size" or "resize when it comes from compendium/items")
- also require an item property "Do not resize" for items that are, for example, unique, and must never be resized

**Stories**
========
Given: a battleaxe defined to weigh 6 lbs (which shall be presumed to be the medium-sized weight) and a small sized pc
When: i add the object to the pc inventory 
Then: when i examine the battle axe thereafter in pc inventory, it weighs 3 lbs

Given: a battleaxe defined to weigh 6 lbs (which shall be presumed to be the medium-sized weight) and a large sized pc
When: i add the object to the pc inventory 
Then: when i examine the battle axe thereafter in pc inventory, it weights 12 lbs

Given: a medium-sized pc with shape change holding a battle axe (6 lbs)
When: the pc shape changes to a small size
Then: when i examine the battle axe thereafter in pc inventory, it weighs 3 lbs

Given: a medium-sized pc with shape change holding a battle axe (6 lbs)
When: the pc shape changes to a large size
Then: when i examine the battle axe thereafter in pc inventory, it weighs 12 lbs

Given: a small-sized pc holding a battle axe (6 lbs) is displayed as a loot sheet
When: the battle axe is looted by another pc
Then: when i examine the battle axe in looter's inventory, the battle axe weighs 6 lbs (unchanged)

Given: small-sized pc and a medium sized pc character sheets opened side-by-side
When: a battle axe is dragged from the small character (which weighs 3 lbs) to the medium character
Then: the battle axe moved to the medium character still weighs 3 lbs (unchanged)

**Comment by Rughalt** [comment]
Added, will be out in 0.93
