### ISSUE TITLE
Bonus Casting from prestige classes not applying to spells known

### ISSUE THREAD

**Issue by ChronosCrake** [Rughalt/D35E#529]
The "Bonus Arcane Spellcaster Level" class feature does not add additional spells known for spontaneous casters with limited spells known. Have not tested with a theoretical spontaneous divine caster, though presumably the functionality is the same there

**Comment by Rughalt** [comment]
Fixed, will be out in 0.93
![2021-05-30 07 47 56](https://user-images.githubusercontent.com/802214/120093578-97345880-c11b-11eb-9257-3b1f0d370c00.gif)
