### ISSUE TITLE
Issue/Bug: DR Immunity Magic Not Working

### ISSUE THREAD

**Issue by 011ver** [Rughalt/D35E#530]
Shadow token created from Shadow in 35E Bestiary Compendium. DR Immunity/Magic or Incorporeal added to token.

![image](https://user-images.githubusercontent.com/77106500/119816531-25e48200-bf30-11eb-95c5-8e25396b906e.png)

Kobold PC created with a standard spear - Kobold and Spear standard race/weapon taken from 35E compendiums.

Kobold attacks Shadow and succeeds on attack roll and succeeds on concealment. When damage is applied DR seems to be ignored.

![image](https://user-images.githubusercontent.com/77106500/119816602-3bf24280-bf30-11eb-9fe9-4d1d67f96fdb.png)

**Comment by Rughalt** [comment]
Fixed, will be ou tin 0.93
