### ISSUE TITLE
Spellpoint System

### ISSUE THREAD

**Issue by Jan-Varenkamp** [Rughalt/D35E#531]
I change a lot of spells, and pit them in to a world compendium because i use my own Spell point costs, but i have the issu that  in the description is my value for spellpoints but if a drag and drop them on a char the spellpoint cost are overwritten with default costs.

I wish me one of two Options:

The first option set a individual spellpoint cost table.

Or a checkbox to stop overwrite existing spellpoint costs of spells.

**Comment by ChronosCrake** [comment]
Another thing for the spellpoint system is to include a checkbox for prepared spellcasters to define prepared spells from their spell lists. Currently there is no way to define which spells are prepared from the spell list. As per the spell points system (found on the SRD [here](http://www.d20srd.org/srd/variant/magic/spellPoints.htm)), the number of prepared spells available to a prepared caster should be equal to the base spell slot allotment, plus any bonus spells from features such as domains or school specialization, but NOT spell slots from a high ability score (as that is instead converted to bonus spellpoints).

**Comment by Rughalt** [comment]
I moved @ChronosCrake comment to a new ticket as this is a different thing altogether. 

Original request added and fixed, will be out in 0.93

**Comment by Rughalt** [comment]
![image](https://user-images.githubusercontent.com/802214/120064739-2125e800-c06e-11eb-91a4-8d539cf81ca0.png)
