### ISSUE TITLE
Arrow recovery not working

### ISSUE THREAD

**Issue by Leaguescience** [Rughalt/D35E#538]
its not working at all :(, i pew pew 100 arrows got none back, got flashbacks from classic wow hunters lol :)

**Comment by Rughalt** [comment]
Could not replicate - ammo is correctly recovered after shooting, and applying damage where the attack was a miss.
![image](https://user-images.githubusercontent.com/802214/120110963-2cf9d300-c170-11eb-8db9-00b915bf8e9c.png)
