### ISSUE TITLE
Spell : Lesser Orb of Fire --> errors

### ISSUE THREAD

**Issue by dcpc007** [Rughalt/D35E#541]
Some errors in the Spell Lesser Orb of Fire : 
- [ ] Range = short (not Long)
- [ ] Subschool = Creation (missing)
- [ ] Types = Fire (missing)
- [ ] Spell Effect : Empty
(maybe other things)

**Comment by dcpc007** [comment]
If i create a custom spell locally, can i export to sent you the data and help you consolidate the base DB ?

**Comment by skepickle** [comment]
Lesser Orb of Fire isn't even in the SRD... should it even be in the system spells compendium?

**Comment by dcpc007** [comment]
Nice spotting !

**Comment by Rughalt** [comment]
I have no idea, removed from compendium.
