### ISSUE TITLE
FR: Display outcome of special actions in chat

### ISSUE THREAD

**Issue by ChronosCrake** [Rughalt/D35E#542]
Currently when you apply a special action, there is no feedback on how the action was applied. Would be very nice to have ability damage for example, or conditions applied to characters, rolled and displayed in chat for the GM and/or players to see.

**Comment by Rughalt** [comment]
Added, will be out in 0.93.1
![2021-06-03 07 19 11](https://user-images.githubusercontent.com/802214/120591253-21dac780-c43c-11eb-8ac7-1b0881b717a6.gif)
