### ISSUE TITLE
Unable to add enhancements to items

### ISSUE THREAD

**Issue by mscottnelson** [Rughalt/D35E#544]
FoundryVTT: 0.8.5
3.5eSRD: 0.93.0

In macOS -> Chrome or Firefox, dragging an Enhancement onto an item doesn't do anything at all (performed as demonstrated on 3.5 docs animation of applying enhancements). It doesn't seem to matter which part of the item the enhancement is dragged to. No Network traffic is triggered; nothing appears to happen at all.

**Comment by Rughalt** [comment]
Fixed, will be out in 0.93.0
