### ISSUE TITLE
Bug: Class features requisites not passing formula

### ISSUE THREAD

**Issue by irbian** [Rughalt/D35E#549]
I added this formula 

@skills.prf > 14

And in this line, https://github.com/Rughalt/D35E/blob/master/module/item/entity.js#L4044

_requirement[1] is empty, instead of having the value of the formula passed

**Comment by Rughalt** [comment]
Cannot reproduce on 0.93.0
![image](https://user-images.githubusercontent.com/802214/120428058-46b73800-c373-11eb-928b-b0a38452a052.png)
If the issue persists with the correct configuration (shown on the screen) reopen with the attached item!
