### ISSUE TITLE
Names of the playlists with custom skin are showed up cutted.

### ISSUE THREAD

**Issue by ilore** [Rughalt/D35E#550]
If I use the custom skin the names of the playlists are showed up like in the picture, cutted. If I use the FVTT skin they return to normal.
![Bug](https://user-images.githubusercontent.com/32924279/120280308-cbdd1700-c2b7-11eb-8779-d32ecd4d51db.jpg)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.93.1
![image](https://user-images.githubusercontent.com/802214/120588481-8cd5cf80-c437-11eb-9bb3-be89dad2363d.png)
