### ISSUE TITLE
PC number of attacks

### ISSUE THREAD

**Issue by BlackWand1** [Rughalt/D35E#561]
When creating an attack for a monster with additional attacks - it works. I can for example ha 10 attacks.

But for a PC, it does not work. The number if attacks seems limited by some other rule.

**Comment by Rughalt** [comment]
The number of attacks for PC is governed by their Base Attack Bonus, as described in SRD rules - the system also adds all required attacks for haste, a flurry of blows, etc. This can be turned off globally in system settings. If the feature is needed on a per-character basis, please open a new ticket!

**Comment by BlackWand1** [comment]
If i turn it off - that would not affect anything? The PC would still follow its BaB etc, but I would be able to create attacks that go beyound

Greatly appreciate the time and effort you guys spend for this system!

**Comment by Rughalt** [comment]
Its either on or off - when turned off you need to manually create number of attacks for your PCs.

**Comment by BlackWand1** [comment]
Cool. I just read about the option in system settings. And if i turn it off, I would always have to create the additional "standard bab" attacks manually, which would be a pain.

How about moving the option for auto/off to the attack action?
Should I then open a new ticket describing this?

**Comment by Rughalt** [comment]
Yes!
