### ISSUE TITLE
Feature request: New spell effect option (buff)

### ISSUE THREAD

**Issue by BlackWand1** [Rughalt/D35E#563]
Would be nice to have a new spell effect option named "buff", where selected gives you the option to drag and drop one or more buffs to the spell. Once casted you could have a button for "apply buffs" instead of "attack/damage".
And those buffs would be applied on the target. Maybe the target must be a PC for convenience.

![image](https://user-images.githubusercontent.com/85252943/120543131-3f804080-c3ec-11eb-914d-a8c2a9b8a383.png)

**Comment by Rughalt** [comment]
You can do this already via special actions! I see you have a lot of questions and ideas - it would be best if you jumped into our discord!

**Comment by BlackWand1** [comment]
The special action does on the other hand require the knowledge of some kind of scripting, instead of the easy click/drag n drop approach :)
