### ISSUE TITLE
Low-light vision doesn't work propertly

### ISSUE THREAD

**Issue by ilore** [Rughalt/D35E#565]
I have a scene with one light and two PCs: an elf with low-light vision selected in his senses window and in his token vision configuration panel, and a human without low-light vision. I don't have active modules and I have activated the "low-light vision requires selection" option in the System settings. 

The light is a common light and the "D35E.DisableLightLowLightVision" option is not selected.

When I select the elf, the light doesn't react with the low-light vision and the radius of the light doesn't change at all, like if I where selecting the human. The only way to make it work is uncheck the low-light vision in the token panel saving changes, and select it again saving changes. But, if I do that, the light reacts even when I select the human, the system gives low-light vision to everyone. 

If I go to another scene an return to the previous, the low-light vision fails again and the light doesn't react anymore. 

A strange thing that I have noticed is: if in the same scene the elf enters to a room in order to not see the light and he goes outside again, the light now reacts with the low-light vision, but the other tokens do too.

All this things happen with GM User and with Player Users too.

**Comment by Rughalt** [comment]
Fixed, will be out in 0.93.2
