### ISSUE TITLE
get the focus on the first field of a window by default

### ISSUE THREAD

**Issue by dcpc007** [Rughalt/D35E#572]
When creating  an item like journal entry, table,.... a windows pop.
But we can't write directly as the focus is not in the first field : the name.

Could you make this automatic focus (cursor) in the first field by default ?
It will save a lot of time.

**Comment by dcpc007** [comment]
Note : same improvement for browse compendium.
Would be easier to : 
- click on the Browse Spell compendium for example
- directly write the spell name without have to click on the far upper left of the screen in the search name field

**Comment by Rughalt** [comment]
I can do second part, but first is core foundry.

**Comment by dcpc007** [comment]
Thx any info for creating an issue on core foundry (if it's possible ?)

**Comment by Rughalt** [comment]
There is a gitlab for Foundry VTT (https://gitlab.com/foundrynet/foundryvtt/-/issues)

Compendium browsers will autofocus from 0.94.2

**Comment by dcpc007** [comment]
Note : already existing issue. I +1 it : 

https://gitlab.com/foundrynet/foundryvtt/-/issues/5259
