### ISSUE TITLE
[bug] adding a Common buff adds a missing icon in status list

### ISSUE THREAD

**Issue by dcpc007** [Rughalt/D35E#574]
To reproduce : 
* open common buffs
* drag Bull's Strength on the player sheet (-> temporary)
* Clic on the "Assign status effect" of the token 

--> a new icon is present (named bull's strength), but with a brokin link or no link image

![image](https://user-images.githubusercontent.com/847516/120935605-e6721e80-c703-11eb-93ff-beacd1437ac4.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.93.3
