### ISSUE TITLE
Make buffs subtab default 

### ISSUE THREAD

**Issue by michalgm** [Rughalt/D35E#577]
Right now, clicking on the buffs tab in a character sheet will show the 'shapechange' subtab by default (versus the 'buffs' subtab). I'd imagine that most characters will be interacting with buffs more often than shapechange, and I know my players have gotten confused when clicking on 'Buffs' and then seeing shapechange info. Would it be possible to make the 'buffs' subtab show by default, and require the extra click to show shapechange?

**Comment by Rughalt** [comment]
Changed! Will be out in 0.93.3
