### ISSUE TITLE
NPC's only get base skill points at first level instead of 4 times

### ISSUE THREAD

**Issue by Eldintux** [Rughalt/D35E#578]
ALL NPC's regardless of class only get the number of skill points allocated per level at first level. But they should get 4 x like players. (This is done with level progression on)

In addition Monsters also get 4x at first level unless they have classes.
Mindless get no skill points

**Comment by Rughalt** [comment]
When using Level Up Dialog a correct number of skills will be shown for 1st level, both NPC and Characters
