### ISSUE TITLE
Allow class features and feats to add bonus base damage

### ISSUE THREAD

**Issue by Heliomance** [Rughalt/D35E#579]
Currently the Combat Changes section doesn't allow you to add damage to attacks of whatever damage type the base weapon does. You have to specify, eg, `&featDamage.piercing`. It would be really useful if you could tell it to just add unspecified damage, which would be bludgeoning when using a bludgeoning weapon, piercing when using a piercing weapon, and slashing when using a slashing weapon.

**Comment by Rughalt** [comment]
This should be already possible with &featDamage.base - it was just undocumented.
