### ISSUE TITLE
Change the cost of the points in the "Point Buy" screen.

### ISSUE THREAD

**Issue by ilore** [Rughalt/D35E#581]
I have been examining the "Use Point Buy" screen. The values that you can obtain are different than the rules from the Dungeon Master's Guide (page 169) due SRD laws. 

For example, this abilities: STR 16, DEX 14, CON 14, INT 10, WIS 8, CHA 9 would be legal using the DMG rules (standard point values = 25) but illegal using  the "Use Point Buy" screen. Why? because the "climbing" of points value between this two sources is different: in the DMG this climbs are between 14-15 and 16-17. In the "Use Point Buy" screen, that climbs are between 13-14, 15-16 and 17-18. 

So, I have calculated new values of the points to make them equivalent to the DMG rules, but they still start at value 10:

8 = -2
9 = -1
10 = 0
11 = 1
12 = 2
13 = 3
14 = 4
15 = 6
16 = 8
17 = 11
18 = 14

Now, with this new points, the values of the "campaign types" are: Low Fantasy = 8 points, Standard Fantasy = 13 points, High Fantasy = 16 points and Epic Fantasy = 20 points. 

Also, an average NPC like a farmer, would have 3 points to invest with this system. It would be great add this "use Point Buy" screen to the NPCs sheet.

**Comment by Rughalt** [comment]
Changed point buy values only. Added button to NPC character sheet.
