### ISSUE TITLE
Feature request: Allow the usage of a formula in the critical threat range of an attack

### ISSUE THREAD

**Issue by cilvet** [Rughalt/D35E#584]
Right now we can only use a static number. This is okay for most cases but I've run into the need of stablishing a formula for a custom attack, that depends on the character's BAB to define the critical threat range.

**Comment by cilvet** [comment]
Where has this been implemented? I can't find it 😓

**Comment by Rughalt** [comment]
There was a minor error in second place that didn't allow you to enter it, when the logic in code was implemented. WIll be out as part of 0.95
