### ISSUE TITLE
DR X/Bludgeoning considers "Custom: B" not bludgeoning

### ISSUE THREAD

**Issue by Calvin263** [Rughalt/D35E#588]
In the compendium, bludgeoning weapons have damage types "custom: B". DR X/Bludgeoning applies on those weapons attacks, where it should bypass it instead.

![image](https://user-images.githubusercontent.com/10062913/121777761-b8586880-cb61-11eb-8c17-3c11ca9cf4ec.png)
![image](https://user-images.githubusercontent.com/10062913/121777767-bbebef80-cb61-11eb-8659-31d663fe2854.png)

**Comment by Rughalt** [comment]
This will be fixed in 0.93.3
