### ISSUE TITLE
the notes in the chat when you try a skill check are missing

### ISSUE THREAD

**Issue by ilore** [Rughalt/D35E#590]
The first image is from FVTT 0.7.10 and the second is from FVTT 0.8.6. As you can see, in the previous version, when you try to make a spot check with a ranger, in the chat window you can see "notes" that indicate the Favored Enemy feature. In the 0.8.6 version, those notes are missing. Other bug is the fact that it doesn't matter what Favored Enemy you have chosen, the notes always includes "Ooze" as Favored Enemy: as you can see in the first picture, I have chosen "human" as FE and the notes include Human and Ooze.

[
![Favored-Enemy](https://user-images.githubusercontent.com/32924279/121804439-b74d3700-cc46-11eb-9f08-c55c637872a6.jpg)
](url)

**Comment by Rughalt** [comment]
Notes fixed, ranger skill fixed (you need to delete skill and make system re-add it to character)
