### ISSUE TITLE
HP rolling can't be hidden

### ISSUE THREAD

**Issue by 7ssshadowsss** [Rughalt/D35E#594]
Whenever you add a level of a class to an NPC sheet or PC sheet. it auto rolls the HP for them and showing the Full Character Name in Chat. Even if you swap to GM roll, Self roll, or Public roll. All users can see it as if it was public.

**Comment by Rughalt** [comment]
What would be the suggested route? This was added specifically so players cannot hide their hp rolls (see #448)

**Comment by Rughalt** [comment]
Added as a part of #363

**Comment by 7ssshadowsss** [comment]
> What would be the suggested route? This was added specifically so players cannot hide their hp rolls (see #448)

I would recommend having it be the player name rather than the name of the  sheet. This way it wouldn't reveal anything about an NPC sheet. I have a work around of just temporarily changing the name. But it seems a bit weird to force it to be revealed.

**Comment by 7ssshadowsss** [comment]
> Added as a part of #363

Oh ignore me, only saw the first message for some reason on phone but now that I opened on computer I see a lot more. Sorry for the late replies life has been hectic
