### ISSUE TITLE
Formula error in item {0} on characters with more than one class

### ISSUE THREAD

**Issue by duebbers** [Rughalt/D35E#595]
I'm not sure if it is an error of the D35E-System or Foundry VTT itself, but since it appears on characters with more than one class I'll report it here. 
I use Foundry 0.8.7 / 3.5e SRD 0.93.3
These Errors occur since last week, when I updated Foundry to 0.8.6 and 3.5e SRD to 0.93.x (not sure which)

  
---
If I add a second class to a character or load a game with older multiclass-characters I get theses error messages:
![grafik](https://user-images.githubusercontent.com/18099824/122131817-08714c80-ce3a-11eb-8f83-8b98348df174.png)

They appear whenever I do anything with the Actor which updates it -  e.g. edit the inventory, change hp, edit notes...
I get no Errors in the console, just the update info:
![grafik](https://user-images.githubusercontent.com/18099824/122132430-1b385100-ce3b-11eb-9a4a-8166877fb93a.png)

If I delete the second class, the errors won't occure.

**Comment by duebbers** [comment]
[fvtt-Actor-wyrmlord-hravek-kharn.zip](https://github.com/Rughalt/D35E/files/6659166/fvtt-Actor-wyrmlord-hravek-kharn.zip)

**Comment by Rughalt** [comment]
The message should hopefully give more info so debugging is easier. Will be out in 0.94

**Comment by duebbers** [comment]
Ok, the more detailed error is now:
![grafik](https://user-images.githubusercontent.com/18099824/122686125-e9930180-d20f-11eb-8b02-6b01f2b8bfec.png)

hope this helps :-)

**Comment by Rughalt** [comment]
This is because automatic hp is on and bugged. That will be fixed in 0.94.1

**Comment by duebbers** [comment]
thank you! :-)
