### ISSUE TITLE
SRD says Medium Armour max for barbarian but Heavy Armour Proficiency assigned at 1st level

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#598]
steps to reproduce:

1. create new actor
2. assign Barbarian Class
3. examine Features > Classes > Barbarian

expected behaviour: best Armour Proficiency assigned will be Medium
actual behaviour: best Armour Proficiency assigned is Heavy

![image](https://user-images.githubusercontent.com/55966777/122278445-e537b300-ceb4-11eb-9f8c-9ff5271af48b.png)

SRD says (http://www.d20srd.org/srd/classes/barbarian.htm):
![image](https://user-images.githubusercontent.com/55966777/122278687-2d56d580-ceb5-11eb-960c-1581968de7d9.png)

**Comment by Rughalt** [comment]
Fixed will be out in 0.94
