### ISSUE TITLE
Add custom class feature not shown in class feature tab

### ISSUE THREAD

**Issue by dcpc007** [Rughalt/D35E#599]
- I create a custom class.
- I create a custom class feature.
- I add the class feature in my PC sheet
- Additions works
- I see the class feature in the Features > Classes tab
- i don't see the class feature in the Features > Class Features tab
![image](https://user-images.githubusercontent.com/847516/122390600-7b7dde80-cf72-11eb-8ea7-f5dc6c5b1eec.png)
![image](https://user-images.githubusercontent.com/847516/122390632-833d8300-cf72-11eb-9584-9dc804f6ce60.png)
![image](https://user-images.githubusercontent.com/847516/122390719-94868f80-cf72-11eb-85e8-a75ccb0ee0d4.png)
![image](https://user-images.githubusercontent.com/847516/122390780-a10ae800-cf72-11eb-9702-478e0f3f42cf.png)

**Comment by Rughalt** [comment]
Unless you have a system option set up it will work like that. You can change behavior there
![image](https://user-images.githubusercontent.com/802214/122667768-d6067d00-d1b4-11eb-8635-73c34f535153.png)
