### ISSUE TITLE
Application of AoE damage or Buffs / Debuffs etc with 'Basic Controls > Select Targets'

### ISSUE THREAD

**Issue by Mesignosis** [Rughalt/D35E#6]
![image](https://user-images.githubusercontent.com/68146147/89201855-7384ac80-d5f5-11ea-963e-b6cae85f768f.png)
The ability to select tokens with 'Select targets' and mass apply effects based on selection

**Comment by agrtga** [comment]
Nice! You’re doing great work.

I’m really looking forward to switching over to this fork. I had a planned session on Saturday that was postponed to this Saturday. I want to get this running before I go on vacation the week after.
