### ISSUE TITLE
Multi-class Rogue gets no Sneak Attack Bonus

### ISSUE THREAD

**Issue by Eldintux** [Rughalt/D35E#600]
Seems to be a problem with Sneak Attack for multiclass characters. I have a player with a barbarian character who has just leveled up & chose Rogue as their 4th Level. When she tries a sneak attack the precision damage is 0d6. So I tried recreating a new character with 1 level Barbarian + 1-3 levels of Rogue. Same result. A multiclass that starts as the Rogue appears fine

**Comment by Rughalt** [comment]
Its a bug with Barbarian class - it has "rogue" sneak attack group added. Will be fixed, but need fix on characters.
