### ISSUE TITLE
[feature request] Make radio button more visible

### ISSUE THREAD

**Issue by dcpc007** [Rughalt/D35E#601]
the losange button that can be on or off are a little difficult to see ; 

Ex: monster buffs sheet : 
![image](https://user-images.githubusercontent.com/847516/122650578-0ce87e80-d134-11eb-8b90-334d6eaa26fa.png)

A brigther color for the dot should be better.

**Comment by Rughalt** [comment]
Changed to green to match rest of the toggles
![image](https://user-images.githubusercontent.com/802214/122662257-c3c71780-d191-11eb-9707-b52356ca666b.png)
