### ISSUE TITLE
Items missing names

### ISSUE THREAD

**Issue by shadowfray** [Rughalt/D35E#605]
All items in the players inventory have names in the overview inventory, but upon opening them the players [cannot see their names](https://gyazo.com/530f6a5103c7c65431812596ecbcb39a). Because of this whenever they try to edit things like the amount they are carrying it spits out the error "Required field 'name' not present in ItemData". Any attempts by them to give the item a name vanishes upon closing the item. As the GM I don't have this issue and [can see the item name present](https://gyazo.com/5eaa4e66b4dc52ba16b89660291b6a22), as well as edit the amount of items, names etc.

**Comment by Rughalt** [comment]
This will be fixed in 0.94.1!
