### ISSUE TITLE
clicks on Weapons Properties buttons register on oldest open weapon window

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#606]
steps to reproduce:

1. open two weapons from same character
2. click on Finesse weapon property button in SECOND weapon window opened
expected behaviour: Finesse button lights up green in SECOND window (if it was off before)
actual behaviour: Finesse button in FIRST window is now lit (if it was off before)

before step 2
![image](https://user-images.githubusercontent.com/55966777/122687445-8c358b00-d1e4-11eb-8a2d-4d98147f7045.png)

after step 2
![image](https://user-images.githubusercontent.com/55966777/122687448-90fa3f00-d1e4-11eb-94bb-ce74877d2da1.png)

versions
![image](https://user-images.githubusercontent.com/55966777/122687412-58f2fc00-d1e4-11eb-8cdc-0c7e05ce9bf7.png)

item exports
[click-to-wrong-window.210620.zip](https://github.com/Rughalt/D35E/files/6683037/click-to-wrong-window.210620.zip)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.94.1
