### ISSUE TITLE
unable to change enhancement on magic sword

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#607]
steps to reproduce:
1. open item
2. change enhancement bonus from 1 to 2
3. delete & recreate attack
4. run attack & check chat card for results
expected behaviour: enhancement bonus to attack and damage should be 2
actual behaviour: enhancement bonus is still 1

![image](https://user-images.githubusercontent.com/55966777/122703048-bd32b180-d21e-11eb-9bc8-4f28e20ddd03.png)

now, here's my versions right now, but i played around with this earlier today with all modules disabled and saw the same behaviour.  i ended up just manually setting the enhancement on the attack, which i'm guessing SHOULD have been set properly when the attack was automatically created from the weapon.

![image](https://user-images.githubusercontent.com/55966777/122703203-0aaf1e80-d21f-11eb-969a-12a78a4273a2.png)

item + actor (the older item file is from earlier in the day when Rughalt and i discussed this)
[fvtt-Actor-brokensword-actor.zip](https://github.com/Rughalt/D35E/files/6683854/fvtt-Actor-brokensword-actor.zip)

**Comment by Rughalt** [comment]
This seems correct as the item in question was unidentified and this is done to hide properties.
