### ISSUE TITLE
AC tooltips are not complete until AC changes

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#609]
steps to reproduce:

1. open character sheet
2. select combat tab
3. hover over AC; observe tooltip

expected behaviour:
![image](https://user-images.githubusercontent.com/55966777/122822192-be5df000-d2ab-11eb-99f3-9232fc3ad5b9.png)

actual behaviour: 
![SNAG-0078](https://user-images.githubusercontent.com/55966777/122822228-cb7adf00-d2ab-11eb-9af1-109b0d2e599c.png)

if i perform the following steps, i can restore expected behaviour
4. change AC by unequipping then equipping something like armour or shield
5. hover over AC; observe tooltip

![image](https://user-images.githubusercontent.com/55966777/122822323-e9484400-d2ab-11eb-9988-768c123666fe.png)

i've observed this behaviour several times in the last couple of days.
let me know if i need to repro with all modules disabled, but i think it's likely base D35E.

**Comment by wmve** [comment]
i can reproduce this on all actors, character + npc.

**Comment by Rughalt** [comment]
Fixed, should not introduce performance problems. Will be out in 0.94.2
