### ISSUE TITLE
Item weight not modified when put on small size monster

### ISSUE THREAD

**Issue by dcpc007** [Rughalt/D35E#616]
* i create a npc actor with race kobold (size = medium, actual size = small)
![image](https://user-images.githubusercontent.com/847516/122932874-650ac500-d36e-11eb-9e0a-57bd8be256be.png)

* i put a leather armor in its inventory with 2 methods : 
  * from the Add button inside the sheet
  * drag & drop from Armors compendium
=> the weight stay at 15lbs

**Comment by Rughalt** [comment]
Fixed.
