### ISSUE TITLE
"No Buffs On Actor Token" hides buffs from owner and GM

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#617]
steps to reproduce:
1. disable "No Buffs On Actor Token" on actor
2. activate conditions and buffs on actor
3. observe token on map
4. enable "No Buffs On Actor Token" on actor
5. observe token on map (as player in browser or GM on on server console)

expected behaviour: icons for activated buffs ands conditions appear, consistent with text in UI
![image](https://user-images.githubusercontent.com/55966777/122981761-18bc8680-d368-11eb-926b-2e351ba6c795.png)
actual behaviour: icons do not appear for player (which i tested in chrome) or GM (in server console)

with checkbox OFF (what i see after step 3)
![image](https://user-images.githubusercontent.com/55966777/122980952-405f1f00-d367-11eb-923f-a302d7f2bd5e.png)

with checkbox ON (what i see after step 5)
![image](https://user-images.githubusercontent.com/55966777/122980901-34735d00-d367-11eb-86bc-a6e6775d2c8e.png)

versions:
![image](https://user-images.githubusercontent.com/55966777/122981250-887e4180-d367-11eb-9a94-d9e91a3b5520.png)

actor in question (although this happens with other actors as well)
[fvtt-Actor-imra.210622.zip](https://github.com/Rughalt/D35E/files/6696671/fvtt-Actor-imra.210622.zip)

notes:
- in neither case do the conditions appear as icons on the token; aren't they supposed to?
- also, i no longer see buffs show up on the party HUD; am i forgetting another setting for this?  they used to show (about a month ago); do i need to write up a different ticket for this?

**Comment by Rughalt** [comment]
> - in neither case do the conditions appear as icons on the token; aren't they supposed to?
> - also, i no longer see buffs show up on the party HUD; am i forgetting another setting for this? they used to show (about a month ago); do i need to write up a different ticket for this?

These two will be fixed in 0.94.2

**Comment by Rughalt** [comment]
Fixed, will be added in 0.94.2
