### ISSUE TITLE
Swarms

### ISSUE THREAD

**Issue by Chemist94** [Rughalt/D35E#62]
Swarms considered to be tiny, fine or diminutive creatures, but by the rules should occupy 10x10 ft. square.

**Comment by Rughalt** [comment]
Wil be added by craeting and additional "Token Size" field for actors that will allow them to have mechanic size different than appearance size. Will also be used for Alter Self.

**Comment by Rughalt** [comment]
Swarms will be fixed after monster reimport - slated for 0.87.1. New field is added to characters and can be used as of 0.87.0
