### ISSUE TITLE
FR: collapsible currency panel

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#620]
in this part of the UI
![image](https://user-images.githubusercontent.com/55966777/123150206-1887be00-d430-11eb-9ac0-5685f972f0ee.png)

suggest either 
(a) the wealth header be collapsible, like this one
![image](https://user-images.githubusercontent.com/55966777/123150327-3a814080-d430-11eb-9d4c-36ff712a2353.png)
(b) subtabs for Wealth and Equipment, like on the Buffs tab
![image](https://user-images.githubusercontent.com/55966777/123150415-5553b500-d430-11eb-8c29-2d7eee5a5a28.png)

**Comment by wmve** [comment]
i am not seeing this in my server and i am running 0.96.1.  need to reschedule for another release?

**Comment by wmve** [comment]
just noticed that SRD coins are 1/50 lb.  my standard is 1/20 lb.  since the introduction of the feature, i have set up currency as shown in the screen cap in the original post.  if i now want to go back and add my own version of PP, GP, SP, CP with my customized weight, they will be out of order.  (for me, "FS" is the standard "default" currency, so i just added the extra denominations)

![image](https://user-images.githubusercontent.com/55966777/134954519-efd0f037-4fc6-49cd-8183-ee4aebb1fcca.png)

this implies i have to tear out all the custom coins definitions and replace them from scratch.  i have two campaigns already in progress, so i don't want to disturb the data in places in various places....  any suggestions?

would still like to see a collapsible currency panel, because this is impeding our use of the inventory panel, which is a near constant activity in any game.

**Comment by wmve** [comment]
it says above that this was "added this to the 0.95 milestone on Jul 12" but i'm not seeing that and i'm running 0.96.4

**Comment by Rughalt** [comment]
Added as a part of 0.98 line
