### ISSUE TITLE
Add new race on sheet doesn't work

### ISSUE THREAD

**Issue by Mesignosis** [Rughalt/D35E#622]
![image](https://user-images.githubusercontent.com/68146147/123426589-f005ec80-d606-11eb-8457-24f36aa896b6.png)
Clicking on the + sign doesn't work it brings up an error in the console instead
![image](https://user-images.githubusercontent.com/68146147/123426722-1af04080-d607-11eb-960d-1da1ef3696f7.png)
0.94.1

**Comment by Rughalt** [comment]
Fixed, will be out in 0.94.2
