### ISSUE TITLE
Feature request : show the right basic attack value in combat tab

### ISSUE THREAD

**Issue by dcpc007** [Rughalt/D35E#623]
Currently some basic and default modifiers are not included in the default attack value, like size +1 attack modifier.

Then the values shown are not those use in a default attack roll (which is right when used !), and different than values shown on official sources like the monster manual.

suggestion :  include all the default modifier in the basic attack modifier.

Alternatives : 
- show no value (....)
- show a warning that those values could not be the right one used in a default attack roll

Notes : i try to think on all the default modifiers that should be part of the default attack bonus.
It must be permanent modifier that applies on all attacks by default (not temporary or conditional ones)
- size (ex : small +1 attack)
- weapon focus feat (+1 attack)
- masterwork or magic weapon (+1 or +x attack)
(follow this thread if you see other ones)

**Comment by Rughalt** [comment]
Size is added (will be out in 0.94.2), masterwork/magic weapon calculations were always in. As for feats adding them is unfeasible since that would require scanning all items for the feats.
