### ISSUE TITLE
Attack Roll Bonus formula display error in Combat Tab

### ISSUE THREAD

**Issue by esb** [Rughalt/D35E#625]
When the Attack Roll Bonus formula includes variables (e.g. "@abilities.wis.mod - @abilities.str.mod" to switch to a Wisdom rather than a Strength modifier), the value is not evaluated correctly and shows up as "NaN" under "Atk" on the Combat tab.

**Comment by Rughalt** [comment]
Added, however, if the performance hit is too big the change will be reverted.

To select different ability for attack rolls, use dropdown below "Attack Ability"
