### ISSUE TITLE
Debuff system in the buff tab of character sheet wiping ability data.

### ISSUE THREAD

**Issue by Axecleft** [Rughalt/D35E#630]
I had an issue during my game last night. I had a character reduced to 0 HP so I placed him in helpless status. When I removed the status after he was healed his Dex was not reset, it was still 0. I had to put the Dex value back in by hand. Later in the last combat of the night a character was paralyzed and the same thing happened to Str and Dex. I fooled around with it this morning and If i set the debuff on the condition menu on the token this clears correctly and resets the abilities to their formal values. If I set the debuff using the character sheet checkbox in the Buffs tab it wipes the ability score

**Comment by Axecleft** [comment]
![odaxi buff one](https://user-images.githubusercontent.com/73614995/123544057-7c0b3780-d71f-11eb-87c6-f6dddd378d54.gif)

**Comment by Axecleft** [comment]
![odaxi buff two](https://user-images.githubusercontent.com/73614995/123544064-81688200-d71f-11eb-80ee-107a620b7c9f.gif)

**Comment by Axecleft** [comment]
![image](https://user-images.githubusercontent.com/73614995/123544140-e15f2880-d71f-11eb-96c5-c900ef3cef42.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.94.2
