### ISSUE TITLE
Bug : prepare spell with Extend Spell = no result

### ISSUE THREAD

**Issue by dcpc007** [Rughalt/D35E#632]
Trying to prepare a spell with a metamagic Extend Spell doesn't result in any result.

![image](https://user-images.githubusercontent.com/847516/123557815-54ee4d80-d793-11eb-9764-e5f91005b6e8.png)

![image](https://user-images.githubusercontent.com/847516/123558051-959a9680-d794-11eb-8996-c3e4987da1b3.png)

I'll try with other metamagic feat

**Comment by wmve** [comment]
i can repro this with other metamagic feats.
here's the actor i repro'd with.
[fvtt-Actor-wiz15.210627.zip](https://github.com/Rughalt/D35E/files/6722247/fvtt-Actor-wiz15.210627.zip)
second screenshot above in OP is mine

**Comment by Rughalt** [comment]
Fixed, will be out in 0.94.2
