### ISSUE TITLE
Extend Spell doesn't change the spell's duration

### ISSUE THREAD

**Issue by dcpc007** [Rughalt/D35E#635]
I create a mage armor with extend spell metamagic, with a wizard 4 and when i launch the spell, the buff duration is 4 hours, should be 8 hours

![image](https://user-images.githubusercontent.com/847516/123685799-5b41ff80-d84f-11eb-835f-9b62a7d3f72c.png)

In the spell prepared with Extend, seems no indication of new duration :
![image](https://user-images.githubusercontent.com/847516/123686199-d7d4de00-d84f-11eb-8764-a1b90c744bf3.png)

**Comment by Rughalt** [comment]
This is because this is non-trivial, and probably will not be automated in close future, as buff time is set up differently (it is set up using special action inside spell).
