### ISSUE TITLE
[Bug] - Attacks are not working

### ISSUE THREAD

**Issue by Gritakthegoblin** [Rughalt/D35E#637]
Hello I'm a goblin, and I've got a problem. Attacks are not working anymore.
![Screenshot 2021-06-28 131444](https://user-images.githubusercontent.com/77771375/123691408-d46f3180-d812-11eb-939f-d4181f5b7a7c.png)

**Comment by Rughalt** [comment]
This should be fixed as of 0.94.4, check on that version, please, and report back.
