### ISSUE TITLE
[Bug] talent browser in character sheet not working

### ISSUE THREAD

**Issue by santalucial** [Rughalt/D35E#640]
pressing add button does nothing
![image](https://user-images.githubusercontent.com/18719694/124168618-afdeb800-daa5-11eb-81bb-5cf8f79a9de5.png)
`Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at ActorSheetPFCharacter._addItemFromBrowser (base.js:2631)`

**Comment by Rughalt** [comment]
Fixed, will be out in 0.94.5
