### ISSUE TITLE
Vanishing text on attack, effect and snippets

### ISSUE THREAD

**Issue by Leaguescience** [Rughalt/D35E#642]
foundry VTT 0.8.6 / D&D 3.5 - 0.94.5
![01](https://user-images.githubusercontent.com/33700136/124351324-acdbe880-dbc7-11eb-9898-3544ca675b0c.PNG)
 on the same area, i can not erase it
![02](https://user-images.githubusercontent.com/33700136/124351398-03492700-dbc8-11eb-88bd-e8ae211f8585.PNG)
the second pic adding anything on this area also vanished and doesn't appear in the description

**Comment by Rughalt** [comment]
Fixed, will be out in 0.95
