### ISSUE TITLE
lootsheet not working (using 0.8.6/ 0.94.5)

### ISSUE THREAD

**Issue by Leaguescience** [Rughalt/D35E#643]
heres an example of how its still not working (using 0.8.6/ 0.94.5)
this is the store guy
![03](https://user-images.githubusercontent.com/33700136/124352038-edd5fc00-dbcb-11eb-8f41-706129dfa475.PNG)

PLayers view before buying the potion, player has 50000 gold
![04](https://user-images.githubusercontent.com/33700136/124352059-034b2600-dbcc-11eb-8144-cdef5bada561.PNG)

 player after buying 1 potion, losing all 50000 gold :(, notice on the chat it say (for NaN gp)
![05](https://user-images.githubusercontent.com/33700136/124352103-44433a80-dbcc-11eb-81cd-71cf1fedc5f6.PNG)

_Originally posted by @Leaguescience in https://github.com/Rughalt/D35E/issues/555#issuecomment-873390166_

**Comment by Rughalt** [comment]
Fixed
