### ISSUE TITLE
big delay with temporary bonus add/remove

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#648]
[fvtt-Actor-priona-fudiel.zip](https://github.com/Rughalt/D35E/files/6760506/fvtt-Actor-priona-fudiel.zip)

**Comment by Dany-Deaneris** [comment]
when i activate a bonus like bard song it need 2 attack before taking the bonus in count waiting seems not to work.

**Comment by Dany-Deaneris** [comment]
it does the same when i remove a buff, it keep it in count as long i don't do a last attack

**Comment by Dany-Deaneris** [comment]
i have make some test and it don't seems like being a delay issue.  I apply the buff on the temporary bonus and it will never display on the token right away.  But when i launch an attack the token display the bonus and then a second attack will have the bonus.  

Before the attack : 
![image](https://user-images.githubusercontent.com/74456344/124398269-d473a380-dce2-11eb-9b6a-a59328d47b7a.png)

After the first attack;  Bonus not given and token get the buff:
![image](https://user-images.githubusercontent.com/74456344/124398312-1270c780-dce3-11eb-9dd3-9f14bab43b61.png)

After a second attack: Bonus in the att-dmg as intended 
![image](https://user-images.githubusercontent.com/74456344/124398341-477d1a00-dce3-11eb-962e-82c5bdbb9113.png)

**Comment by Dany-Deaneris** [comment]
Second test;  If i use the combat tracker and get the bonus on my turn it will not apply, but if a turn is pass then i will get the bonus.
Player 1 use bard song, everyone add the bonus on their sheet.  If the bard could attack he would not have the bonus.  The bard pass his turn and...
Player 2 turn, every player that haded the bonus now have it on their token.  The player 2 attack and have the bonus.

I don't know if all those details will help you to see if there is a real bug there or something that can be done ^^

**Comment by Rughalt** [comment]
Fixed, will be out in 0.95
