### ISSUE TITLE
inventory on all characters shows 0 total weight

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#650]
steps to reproduce

1. create new actor
2. go to inventory tab
3. open items browser
4. drag Longsword to character sheet

![image](https://user-images.githubusercontent.com/55966777/124532760-200b7780-dddf-11eb-9d47-41190bedb8fb.png)

expected behaviour: "Carrying 4 lbs"
actual behaviour: "Carrying 0 lbs"

versions: see screenshot above
ALL MODULES: OFF

almost all of the characters in three different worlds (PC or NPC) have a non-zero inventory weight total
attaching the same character above...
[fvtt-Actor-inventorytest.zip](https://github.com/Rughalt/D35E/files/6766920/fvtt-Actor-inventorytest.zip)

...and one that doesn't have the problem
[fvtt-Actor-nonzerototal.zip](https://github.com/Rughalt/D35E/files/6766922/fvtt-Actor-nonzerototal.zip)

BTW, i also notice that any characters that have a zero inventory weight total also have NaN for total inventory value (see "inventorytest" character above).  i suspect this is related.

**Comment by Rughalt** [comment]
Fixed and made so it will not break. Will be out in 0.95
