### ISSUE TITLE
Action button on Item Spell Uses does not work; throws Uncaught TypeError

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#651]
steps to reproduce:

1. Import Staff of the Magi from D35E compendium
2. Add Magic Missile to Spell Uses, selecting Per Day (although i think i have tried them all and gotten the same results)
3. Click Action button for Magic Missile

expected behaviour: see a chat card in chat log indicating the spell use has been activated
actual behaviour: no chat card appears in chat log

Uncaught TypeError that happens immediately on clicking the button:
![image](https://user-images.githubusercontent.com/55966777/124534410-36ff9900-dde2-11eb-8620-333f6c9852a0.png)

zip of item created by above instructions
[fvtt-Item-x-staff.zip](https://github.com/Rughalt/D35E/files/6766987/fvtt-Item-x-staff.zip)

versions: 
![image](https://user-images.githubusercontent.com/55966777/124534679-c0af6680-dde2-11eb-8e33-419e5acfdb56.png)

**Comment by Rughalt** [comment]
Is the action button one in the item details?

**Comment by Rughalt** [comment]
Fixed, it was an error in item sheet definition, will be out in 0.95
