### ISSUE TITLE
Deactivating temporary buff doesn't remove effect from character

### ISSUE THREAD

**Issue by ChronosCrake** [Rughalt/D35E#662]
As title. Only way to actually remove the buff is to delete the buff from the character sheet entirely, and then drag it back in from the compendium when you want to reapply it.

**Comment by wmve** [comment]
can you show the steps you used to recreate this, including suitable screenshots?  then describe what you were **expecting** would happen at the end of the steps and what **actually** happened.

Just because the buff is still listed, doesn't mean it's active.
![image](https://user-images.githubusercontent.com/55966777/125085744-eb2a4980-e098-11eb-936b-f2a13a32e5e7.png)

only bull's strength is active in the above, the others i keep around because it saves me having to fish them out of the buffs compendium on short notice.

**Comment by wmve** [comment]
and if you think the a buff is still active even though it's not listed as active, you should substantiate that with some screen shots.
also, please list the versions with a screenshot like this, and make sure you have **all modules turned off**.
![image](https://user-images.githubusercontent.com/55966777/125086084-465c3c00-e099-11eb-8c84-c22426f0867d.png)

**Comment by ChronosCrake** [comment]
so I have a custom buff for the spell "one with the land", which gives +2 to a bunch of skills:
![image](https://user-images.githubusercontent.com/84900202/125087259-eef0b700-e0fe-11eb-9c7c-ab05c6d52135.png)
When I first activate it, it's all fine, but when I deactivate it, the buff is still active on the skills in question:

![image](https://user-images.githubusercontent.com/84900202/125087394-07f96800-e0ff-11eb-9252-418e3446ff74.png)
![image](https://user-images.githubusercontent.com/84900202/125087443-1182d000-e0ff-11eb-8aa8-6b4c76e1a9e7.png)

Also, because you requested it:
![image](https://user-images.githubusercontent.com/84900202/125087558-28c1bd80-e0ff-11eb-9bcd-63a89b82c05a.png)

**Comment by wmve** [comment]
that's much clearer, thanks.
i would suggest posting a zipped up copy of the json for this character and the buff.  that should provide everything needed for Rughalt to investigate.

**Comment by ChronosCrake** [comment]
Where abouts would I find that?

**Comment by ChronosCrake** [comment]
Nevermind, Figured it out, here's the zip:
[fvtt-Item-one-with-the-land.zip](https://github.com/Rughalt/D35E/files/6791888/fvtt-Item-one-with-the-land.zip)

**Comment by wmve** [comment]
go to the object in your object collection and right click
![image](https://user-images.githubusercontent.com/55966777/125089863-bae4aa00-e09c-11eb-8754-9a090359a37d.png)
select Export Data and save the file.
i think you can only post zip files in issue text here, so i always zip up all the json files in one zip file before posting.

**Comment by wmve** [comment]
just drag the zip file on the text field here, just like for screenshots

**Comment by wmve** [comment]
never mind, i missed where you posted it already

**Comment by Rughalt** [comment]
I may have fixed something related to that because I cannot reproduce it on local version. If it happens after 0.95 is released please reopen @ChronosCrake

**Comment by Rughalt** [comment]
Fix may be related to #648
