### ISSUE TITLE
Armor Item bug

### ISSUE THREAD

**Issue by Leaguescience** [Rughalt/D35E#668]
the armor not calculating the max dex bonus if its not in the base

![bugg](https://user-images.githubusercontent.com/33700136/125226965-031fea00-e2a0-11eb-8e6f-babdb06efbcb.PNG)

**Comment by Rughalt** [comment]
That was hard one to track (if the base strength was lower than modified, the first max dex value was always used). Fixed and will beo out in 0.95

**Comment by Leaguescience** [comment]
cool awesome :)
