### ISSUE TITLE
Extra Turning feat not working correctly

### ISSUE THREAD

**Issue by Axecleft** [Rughalt/D35E#670]
When added, the extra turning feat will add to the total turn attempts but will not correctly add to the number f uses remaining per day. 
![image](https://user-images.githubusercontent.com/73614995/125294590-63d81280-e2f2-11eb-97a7-634d0c39b12b.png)

**Comment by Rughalt** [comment]
I see that the turn undead uses does not get updated right away after adding - but after something else is changed on the actor (this has to deal with actor update that I will work on as a part on 0.95, but there are no promises there - I do not want to make too many update passes and this is a very specific feat that affects existing item), but the uses *does* set to maximum after **rest** (I cannot easily manipulate value when adding an item). If it does not, please reopen.
