### ISSUE TITLE
Suggestion: Applying damage would select the token targeted by the player

### ISSUE THREAD

**Issue by vittordrow** [Rughalt/D35E#673]
As suggestion, when a player attacks a token their targeted token info would be put on the attack/damage card. So when the MM presses apply damage, it would apply it to the token the player had targeted when they generated the attack info.

With this the GM wouldn't need to select/target tokens to apply damage, saving a lot of time and avoiding mistakes.

**Comment by Rughalt** [comment]
Automatic targetting is hard in case of full attacks, but a feature that allows players to target mobs, and those targeted mobs will be shown in the attack card so GM can easily click on the portraits to select the same target as player, as shown in the GIF below.

![2021-08-08 18 54 52](https://user-images.githubusercontent.com/802214/129441157-650c30c1-5e32-4050-9eaa-55dd1258e78e.gif)
