### ISSUE TITLE
text in effect text box/ spell description invisible

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#679]
text as soon as saved is invisible 
![image](https://user-images.githubusercontent.com/74456344/126081931-04be6a26-effd-4a14-b7d9-c15010a727e6.png)

But when i go look into description text is there
![image](https://user-images.githubusercontent.com/74456344/126081945-575caf0a-e2ac-43a8-9259-1db2175e1720.png)

The same for note effect or note on attack are empty even if something is wrote inside.
![image](https://user-images.githubusercontent.com/74456344/126081993-5f29621f-f7ec-40eb-8f60-3cc15c9155ea.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.95
