### ISSUE TITLE
Feature Request: Ability to hide Spell Cards

### ISSUE THREAD

**Issue by agrtga** [Rughalt/D35E#680]
The new Spell Cards feature is relatively niche. It would be valuable to have that be able to be hidden so as to avoid player confusion and cleanup the interface.

**Comment by Rughalt** [comment]
Added, will be out in 0.95
![image](https://user-images.githubusercontent.com/802214/126516445-80b5d6cd-d867-494c-8a8d-d879423b3312.png)

**Comment by agrtga** [comment]
> Added, will be out in 0.95
> ![image](https://user-images.githubusercontent.com/802214/126516445-80b5d6cd-d867-494c-8a8d-d879423b3312.png)

Awesome! Thank you.
