### ISSUE TITLE
Monks Flurry of Blows roll wrong amount of attacks.

### ISSUE THREAD

**Issue by Revq** [Rughalt/D35E#681]
15 Level monk rolls 3 attacks with flurry of blows instead of correct 5.
![image](https://user-images.githubusercontent.com/10102281/126118975-6bb8c985-fb6d-4d4d-9ed0-fe427fa83345.png)
![image](https://user-images.githubusercontent.com/10102281/126119070-b5f98456-cdb0-4182-b379-1868caf77613.png)

[fvtt-Actor-balthazar.zip](https://github.com/Rughalt/D35E/files/6838722/fvtt-Actor-balthazar.zip)

**Comment by Rughalt** [comment]
Fixed, the problem was with Unarmed Strike of a monk not auto-scaling with BAB, not with Flurry of Blows
