### ISSUE TITLE
Missing button to edit spell description!?

### ISSUE THREAD

**Issue by duebbers** [Rughalt/D35E#683]
![grafik](https://user-images.githubusercontent.com/18099824/126220936-ae7f6915-3b22-4771-9310-553aa217b365.png)

I'm not quite sure if there was a button before, but all other item descriptions can be edited with the buttons which appears if you hover over the item description. I have no such button for the spell descriptions nor any other obvious method to edit it. This isn't a write protection probblem, since it happens not only with spells from a compendium but also with new created spells.

Is this a bug or am I missing something?
![missing description editor](https://user-images.githubusercontent.com/18099824/126220724-c5cea18f-c066-4ef7-afa5-800111d531ea.gif)

**Comment by Rughalt** [comment]
You edit this in the Details tab - this is bugged in 0.94.X line though - it will be fixed in 0.95.

**Comment by duebbers** [comment]
wow, that was a quick response :-)

Thanks for the tip with the Details tab. I have seen the large blank space there but I didn't try to hover under the snippet-field...

**Comment by Rughalt** [comment]
Fixed, will be out in 0.95
