### ISSUE TITLE
Weapon Created From not displaying 

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#684]
![image](https://user-images.githubusercontent.com/22633854/126355884-040bcebf-d4d5-4165-8599-f1820ee93948.png)
![image](https://user-images.githubusercontent.com/22633854/126355921-5b68eec1-6981-4689-acf5-5d8a8d95db47.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.95
