### ISSUE TITLE
Weapon Finesse not working

### ISSUE THREAD

**Issue by Grotzmaul** [Rughalt/D35E#687]
![Weapon Finesse 1](https://user-images.githubusercontent.com/55845788/126642600-c25d732d-95ef-415c-98ac-458a6b5c3ef7.PNG)
![Weapon Finesse 2](https://user-images.githubusercontent.com/55845788/126642616-d8659ee3-0fc6-4c1d-90e6-e0c295f4145a.PNG)

As can be seen from the images, weapon finesse does not change the attack ability from strength to dexterity

**Comment by Rughalt** [comment]
Fixed, will be out in 0.95
