### ISSUE TITLE
Deleting an Aura on a character don't remove the bonus automatically on other player

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#696]
As said in title, i've made an Aura and if i delete it while fighting as if the character lose the Aura, other character around will still have the buff in they're Aura as seen in this picture.  

![image](https://user-images.githubusercontent.com/74456344/126882978-61dc92d2-35e4-4a80-ad03-2ed81cae45a6.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.95.3
