### ISSUE TITLE
Aura (Enhencement)

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#697]
Aura is too cool for not upgrading it ;)

it would be nice to have an activate/desactivate button for Aura as well as temporary bonus.  So Spell like Prayer that give +1 att/dmg/skill and all could be give by that method from 1 character and with the distance instead of giving them all a temporary bonus that everyone need to add manually.  Only the player that give the bonus would need to activate it.  

As seen from this image i would love the same as temp bonus. And have time duration so it can count the turn and remove it when the effect is finished. 
![image](https://user-images.githubusercontent.com/74456344/126883026-5d640a22-3c5f-4399-843f-bad90cd3cde6.png)

**Comment by K484L-v1** [comment]
![immagine](https://user-images.githubusercontent.com/87317002/132185497-92c10234-8e33-4810-a2f3-a067a35925da.png)

by pressing the square on the aura buff, of the caracter that emits it, it doesn't turn off.

**Comment by Rughalt** [comment]
Added, will be out in 0.96.4
