### ISSUE TITLE
Bug: Favored Enemy not working on attack

### ISSUE THREAD

**Issue by RafaelFett** [Rughalt/D35E#703]
Favored Enemy (Ranger) checkbox works on damage, but not on attack.

**Comment by Rughalt** [comment]
According to RAW, the ranger does not get an attack bonus against favored enemies:
https://www.d20srd.org/srd/classes/ranger.htm#favoredEnemy

**Comment by RafaelFett** [comment]
Sorry, you are right, I'm playing with the (portugues - Brasil) translated version PHB, and on the book says attack and damage, but in the english really is only damage, what a mess, as always, thanks.
