### ISSUE TITLE
Low-light Vision radio-button on custom Races

### ISSUE THREAD

**Issue by skepickle** [Rughalt/D35E#704]
The Low-light Vision radio-button on custom races doesn't seem to take effect. The UI seems to uncheck the radio-button as soon as it's checked, and regardless of how I mess with that, the character with that race assigned never gets low-light vision.
Foundry - 0.8.8
3.5e SRD - 0.94.5

**Comment by skepickle** [comment]
Here's a screenshot: ![image](https://user-images.githubusercontent.com/3783101/127196211-b41fc6ac-2130-4a5f-9c41-ba743e45b308.png)

**Comment by Rughalt** [comment]
Will be out in 0.95.3
