### ISSUE TITLE
Divine Power Buff

### ISSUE THREAD

**Issue by gmichalec-pandora** [Rughalt/D35E#713]
I've added a Divine Power buff for my cleric, but I am unable to get one effect to work properly. The spell states that your BAB should become equal to your character level. I've added the effect as a change to base attack, and set the type to 'replace', but instead of replacing the value, it is adding the value. Maybe I've messed up the syntax - not entirely sure.

![image](https://user-images.githubusercontent.com/39168929/127598025-a55a388c-8747-437b-bee8-69bb54fc71f2.png)

![image](https://user-images.githubusercontent.com/39168929/127598110-3f5ac4d4-7665-4bf5-8914-21f5e1f6a533.png)

**Comment by gmichalec-pandora** [comment]
[fvtt-Item-divine-power.txt](https://github.com/Rughalt/D35E/files/6904993/fvtt-Item-divine-power.txt)

**Comment by Tanky06** [comment]
There is already an issue open for this @attributes.bab.value is not recognize in buffs #522

The correct value in the change sheet should be @details.level.value - @attributes.bab.value to add the level then substract the current bab value so in your case it should be 
6 (Current bab) + 8 (level.value) - 6(Current bab) = 8

**Comment by Rughalt** [comment]
BAB replace will now work correctly it will set replace base value from classes and HD.
