### ISSUE TITLE
Bard refuses to level up for some reason

### ISSUE THREAD

**Issue by Amiplaize** [Rughalt/D35E#717]
When I try to level this character up to level 3, nothing saves. Other characters work fine, but when I hit the save button on the Features > Classes tab to save the hit points and skill points, it doesn't stick. 
[fvtt-Actor-karin-wyndrad-(old).txt](https://github.com/Rughalt/D35E/files/6912772/fvtt-Actor-karin-wyndrad-.old.txt)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.95.5
