### ISSUE TITLE
Dispel Psionics nut subject to Power Resistance

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#719]
given that Power Resistance is selected for Dispel Psionics,
![image](https://user-images.githubusercontent.com/55966777/127936654-92533f46-4c8d-462e-8d55-c55c24f83176.png)

referring to [https://www.d20srd.org/srd/psionic/powers/dispelPsionics.htm](https://www.d20srd.org/srd/psionic/powers/dispelPsionics.htm)

![image](https://user-images.githubusercontent.com/55966777/127936581-35c5f4a3-c8d4-43a5-ac7e-7a0bf30e5f25.png)
i see that the Power does not appear to be subject to Power Resistance

i am guessing this needs to be turned off for Dispel Psionics

**Comment by Rughalt** [comment]
Fixed.
