### ISSUE TITLE
Human Race Bug

### ISSUE THREAD

**Issue by jnickg** [Rughalt/D35E#72]
When adding the Human Race to a character, its bonus skill point is not accounted for in the calculated total points available. This is easy to work around by adding it manually (by adding the missing total to the "Bonus Point Formula" box), but this seems like a bug since the Human Race _does_ account for other things, e.g. Feats.

**Comment by Rughalt** [comment]
Was fixed a while back ago, however the fix assumes you use Class Progression (this is only really needed for class-based PCs, as even class based NPCs have inconsistent skill points in source materials).
