### ISSUE TITLE
Feature Request: show Special abilities etc. in Statblock Sheet

### ISSUE THREAD

**Issue by drbleifuss** [Rughalt/D35E#722]
The current statblock sheet doesn't show Traits, Class Features or Special Abilities. It would nice to have access to them on the Statblock Sheet.

**Comment by Rughalt** [comment]
Can you give an example of what doesn't show up? My quick test shows that most of the features show up in feats part (I can separate that into separate lines like in example below)
![image](https://user-images.githubusercontent.com/802214/129440741-babfc652-632d-4d93-ba2d-7ecc8bb61eda.png)
