### ISSUE TITLE
Light Color is blank in bestiary entries

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#725]
Evion reported this error message along with "this is making players crash" (#bugs, Aug 7, 17:08 EDT)

![image](https://user-images.githubusercontent.com/55966777/128780083-f39f8669-cb40-4fa2-adea-dc50860815c6.png)

which lead to Rughalt's suggestion there needed to be an extra check on Light Color being blank on the token.

![image](https://user-images.githubusercontent.com/55966777/128779651-fd89b354-2679-4f57-910a-007fff021f7a.png)

i have tried a half dozen random entries from the Bestiary in my demo world (all modules off) and they all have a blank Light Color

Righalt suggested we needed a ticket.  not sure what the action is here besides more robust error checking, since no one else reproduced Evion's behaviour.

**Comment by Rughalt** [comment]
Fixed, will be out in 0.96
