### ISSUE TITLE
Feature request: Ability damage

### ISSUE THREAD

**Issue by BlackWand1** [Rughalt/D35E#728]
Where you defined "Combat" for your weapons, you can today add normal damage and energy damage such as fire etc.
But would be nice to also be able to add ability damage (Str, Dex, Con).

**Comment by Rughalt** [comment]
You can do that already using special actions https://docs.legaciesofthedragon.com/en/character/special-actions#ability-damage

**Comment by BlackWand1** [comment]
Hey!

That is all good. But using api/script/macro is more time consuming and requires the knowledge.

If not possible - i would appreciate "ability damage (str)" etc was a drop down option.


Robert Winbladh
________________________________
