### ISSUE TITLE
Character Sheet Can't Open

### ISSUE THREAD

**Issue by jnickg** [Rughalt/D35E#73]
Two of my players hit this while they were dragging spells onto their character. After dragging several spells, both reported that dragging some spell caused the sheet to switch pages, and then render as if they had "Limited" view of the character rather than "Owner." Then, they couldn't open the character sheet. And neither could I. And neither could anyone else, even after changing permissions. _Duplicating_ the character did not resolve it, and neither did _Export to JSON_ → _Create New Character_ → _Import from JSON_. I didn't see anything logged in the node server itself, and wasn't getting a popup error, but it felt like something got corrupted in the sheet causing the character sheet to be un-openable.

I will spend some time trying to coerce a reproduction of this issue. For now I am having players export their characters to JSON at the end of each session, just in case it happens again.

**Comment by jnickg** [comment]
After speaking with @Rughalt on DIscord, this sounds likely to be a race-condition type of bug with Foundry itself, that can happen when multiple users are interacting heavily with their character sheet.

**Comment by Axecleft** [comment]
I spotted this on in the list when searching for buff related Issues. Was this ever corrected on the Foundry side, can it be closed?
