### ISSUE TITLE
[Suggestion] Spell Card Insert Description/Public Notes

### ISSUE THREAD

**Issue by Gritakthegoblin** [Rughalt/D35E#730]
Hello, It's a wild Goblin here. I would like to request the ability to insert descriptions in the spell card system so that spells/maneuvers/ect., that are too circumstantial for the cards to represent with the current system can be shown via text instead of an empty box.
![Screenshot 2021-08-12 154228](https://user-images.githubusercontent.com/77771375/129274088-d6442efd-f45e-4b8e-ac01-9b74a3184896.png)

A secondary request would be to add a public notes section that all players can see as the Effect/Attack notes are private to the DM currently.

**Comment by Rughalt** [comment]
This was a bug - descriptions should work like for spells. Will be out in 0.96
