### ISSUE TITLE
power attack always set to max

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#736]
1. give an actor power attack feat
2. execute a melee attack
3. set power attack slider to 0
4. complete attack so it shows up in chat log
5. repeat process

expected behaviour: power attack slider will be at 0
actual behaviour: power attack slider is at max

![image](https://user-images.githubusercontent.com/55966777/130366794-465bd449-3975-444f-a48d-3467eba779d8.png)

versions
![image](https://user-images.githubusercontent.com/55966777/130366846-0d671509-41c0-41c4-b589-9fb5c1dd6e39.png)

i have reproduced this in two different worlds, so it would seem to be actor-independent

**Comment by Rughalt** [comment]
Please check if it happens on the newest version of the system, reopen if needed.
