### ISSUE TITLE
Automatic buff from spells (mage armor/bless) do not get active

### ISSUE THREAD

**Issue by BlackWand1** [Rughalt/D35E#738]
After activating the "special action" from the mage armor spell on a npc/character - the buff remains inactive.

[localhost-1629661308250.log](https://github.com/Rughalt/D35E/files/7028042/localhost-1629661308250.log)

**Comment by BlackWand1** [comment]
I casted the spell from a NPC that has no token on the scene, only still in the character directory. Casted it as a scroll

**Comment by Rughalt** [comment]
Fixed, will be out in 0.96
