### ISSUE TITLE
dark vision don't work on npc sheet

### ISSUE THREAD

**Issue by RafaelFett** [Rughalt/D35E#740]
dark vision don't work on npc sheet

**Comment by RafaelFett** [comment]
1 - Create a npc sheet, enable vision and set darkvision to any number
2 - The npc can see light but can't see the darkvision
![image](https://user-images.githubusercontent.com/62724675/130753475-969c60b1-f01e-4530-877b-894d965040f6.png)
![image](https://user-images.githubusercontent.com/62724675/130753529-0e0b3d0f-b417-4300-8511-8f0b622326b8.png)

**Comment by wmve** [comment]
i confirmed this on one of my maps pretty quickly.
i have a PC token that has darkvision.  it shows monochromatic vision.
![image](https://user-images.githubusercontent.com/55966777/130797584-45e38302-2ef6-487f-828b-6a7af04e71ba.png)
i added an NPC token and added darkvision 60 and it doesn't show when the token is selected
![SNAG-0327](https://user-images.githubusercontent.com/55966777/130797646-8226af01-6299-424a-b99d-7ebdb776c54c.png)

**Comment by Rughalt** [comment]
This may be dependent on "Do not override token vision setting on a character". Also, in the case of NPC, settings are *per token* and are not shared from the main creature if modified there, after dropping the tokens.
