### ISSUE TITLE
Repeating "deactivated buff" in chat

### ISSUE THREAD

**Issue by BlackWand1** [Rughalt/D35E#743]
I noticed that if the player has set values in the "timeline" tab of the Buff - they are repeatedly deactivated in the chat upon the players turn.
See pictures of how they have configured it.

![timeline on buff equal repeating deactivate buff in chat](https://user-images.githubusercontent.com/85252943/130847943-6c01606f-c5be-49e0-9305-6776eda1353f.PNG)
![buffs1](https://user-images.githubusercontent.com/85252943/130847945-3b210f83-06a6-4616-8968-dec7dc7e2696.PNG)
![Buff list on chr](https://user-images.githubusercontent.com/85252943/130847947-d7f4fb16-f6e0-4c2d-bc6e-aeabc88ef641.PNG)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.96.2
