### ISSUE TITLE
Staffs - how they should work

### ISSUE THREAD

**Issue by BlackWand1** [Rughalt/D35E#748]
According to DMG staffs has a lowest caster level, but else will use the wielders caster level if higher.
Today each added spell can be set with each own caster level which is wrong - and does not work as well.

The spells added (those who at least have some damage formula) use the "min" and hence has the lowest possible CL.
Should be "max" so that each spell use the highest possible caster level of the laster - but minimum what the staff has (CL).

![image](https://user-images.githubusercontent.com/85252943/131262382-81e76f7c-5cd0-48a9-b2de-4a6a163ffaf8.png)

All staffs should be "weapon" as well since they deal 1d8 damage. Is a dual weapon, and can have enchantment etc.

**Comment by Rughalt** [comment]
You can now implement staffs like that, you however need to set caster level per spell (as caster level inside whole item is used when item action is used - enhancement spell is a separate entity). When leveling up you may need to update values on the staff.
