### ISSUE TITLE
Hill Giant missing default Throw Rock attack

### ISSUE THREAD

**Issue by Straddlecat** [Rughalt/D35E#751]
![image](https://user-images.githubusercontent.com/22633854/131372900-c9765bbe-1fab-427c-b2c4-94fce38cd8a9.png)

https://www.dandwiki.com/wiki/SRD:Hill_Giant

By default the hill giant doesnt have its rock throwing attack

**Comment by Rughalt** [comment]
Fixed all giants, added new image to giant ants as well
