### ISSUE TITLE
[BUG] Conditional modifiers in weapon 

### ISSUE THREAD

**Issue by Grotzmaul** [Rughalt/D35E#752]
The conditional modifiers in weapon attacks doesn't show any field. In addition, if an attack with a conditional modifier created by an enhancment is modified in some way, the previous working conditional modifier stop working

![Unholy Boy 1](https://user-images.githubusercontent.com/55845788/131382311-2be7c5a8-c5bb-4cd8-a72b-2937d7b036d1.PNG)
![Unholy Boy 2](https://user-images.githubusercontent.com/55845788/131382315-bb61cf8c-7fba-4800-85d5-701c908e1704.PNG)

**Comment by wmve** [comment]
i'm wondering the same thing; seeing the same thing.  promising feature, tho.

**Comment by Rughalt** [comment]
Feature was added in Nev 2021, and it worked probably up until Foundry version 0.8. It will be fixed in 0.96.2
