### ISSUE TITLE
Feature request: quick roll in chat

### ISSUE THREAD

**Issue by BlackWand1** [Rughalt/D35E#753]
If i for example do the following in chat:

/r 4d5 fire dc 17
It should give me a chat box with damage/apply/apply1/2 and the roll save button.

/r 4d6 healing
Same thing, would be considered healing instead.

The fire/cold/negative energy/healing should be the names you can currently pick from "combat changes"

The "dc xx" should be optional.

This would be awesome :)

**Comment by Rughalt** [comment]
I have no idea if this is even possible. Will ask around.
