### ISSUE TITLE
DC value of spells in staffs

### ISSUE THREAD

**Issue by BlackWand1** [Rughalt/D35E#760]
DC of staffs should use the ability modifier of the caster. Looking at the pictures below it looks like it still uses the minimum required ability value - instead of 22(+6) as in my case for this Wizard.

Spell
![image](https://user-images.githubusercontent.com/85252943/132565588-cea70fe3-24c3-4ffe-a600-f3487a181e09.png)

Staff
![image](https://user-images.githubusercontent.com/85252943/132565636-2cda4a80-40fc-4809-b08c-55152b817028.png)

When casting spell
![image](https://user-images.githubusercontent.com/85252943/132565680-f8e53ba8-7486-4399-ab7c-f0f51183fe4f.png)

**Comment by Rughalt** [comment]
Added ability to set CL and Spelsting Ability directly on the enhancement tab. CL replaces CL in the spell box, the ability is added to DC.
![image](https://user-images.githubusercontent.com/802214/133309278-9a04b118-bb6a-4b09-b469-9fae880d855b.png)
