### ISSUE TITLE
future request - custom formula in the "size" box (cone, circle.. )

### ISSUE THREAD

**Issue by K484L-v1** [Rughalt/D35E#764]
If it's possibile, please add the possibility to insert custom formula in the "size" box, like (@attributes.hd.total*5). 
To let change the size of the measure template in according to some ohter values and not to have a fix value.

![immagine](https://user-images.githubusercontent.com/87317002/132768840-96617c76-4058-4b21-be84-305d016127d3.png)

**Comment by Rughalt** [comment]
Added, will be out in 0.97
