### ISSUE TITLE
Feature request: Scroll case

### ISSUE THREAD

**Issue by BlackWand1** [Rughalt/D35E#766]
Hey!

Maybe this could/should be a module? I did a search but dont think I could find anything like it.

But here comes. A mage/cleric can over time collect a bunch of scrolls and having all these in the "consumable" part will create a rather large view and harder to locate the correct spells/scrolls etc.

What if scrolls could be hidden and instead viewed through some kind of "scroll case" function. Where your scrolls are listed more or less like the "spell browser".
A list of your spells and count of the scroll and the "action" button". Maybe showing the "short snippet text".
Could also be a separate "inventory" view-style.

Would be cool of the correct spell image could be to the left of the spell as in the spell browser.
But since when converting to scroll the image gets replaced with a scroll - and hence the spell icon is "gone".

**Comment by Axecleft** [comment]
I created a container item named scroll case for this function. The scrolls are still in the consumables tab but it can be reduced to not display it's contents. Each container in the containers tab can also be opened and closed to reduce the size of your lists.

**Comment by BlackWand1** [comment]
Oh. I would have to look at that.
