### ISSUE TITLE
Feature Request - Combat changes - additionnal modified field - healing formula 

### ISSUE THREAD

**Issue by Johnmish** [Rughalt/D35E#767]
![image](https://user-images.githubusercontent.com/87750944/132962867-1868f8c7-2ddb-47f3-8865-8eeb6c7152a1.png)

Adding in "combat change" the healingFormula for "Modified field". This would permit to develop feats that alter the effectiveness of healing spells...

Eg. In Complete Divine, there is a feat named "Augment Healing" that adds the spell level * 2 to the amount of healing applied.
Currently, we can only modify damage. And negative damage does not work with healing... -> negative damage will be rounded to 1 minimal damage, then the damage reduction system applies, and so on....

This would be a great feature !

**Comment by Rughalt** [comment]
It should work just by adding featDamage. This will get added to the first line of a healing spell, that should have its damage correctly set to positive energy, which I think always heals non-undead creatures unless directly stated otherwise.

**Comment by Johnmish** [comment]
Hi, thanks for the tips. 
You can alter the amount of healing by adding &featDamage.healing. 
Found the proper damage type "string" to include by looking at the damage-type compendium. 

![image](https://user-images.githubusercontent.com/87750944/132984506-447e0f56-39f8-490a-b73d-afda29b0e684.png)

Previously, i was attempting to add "positive energy" damage, which were ... damages... I'll close the RFC.
