### ISSUE TITLE
Bug: Missing non active class features on the class description

### ISSUE THREAD

**Issue by irbian** [Rughalt/D35E#768]
![image](https://user-images.githubusercontent.com/3071767/132986478-4d1af155-91ef-473d-98e3-f87df6d80bdb.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.96.4
![image](https://user-images.githubusercontent.com/802214/133301820-f62159fd-86bf-4cd0-b6e2-ab897ccd7f4c.png)
