### ISSUE TITLE
Weapon and Armor enhancements works wrong

### ISSUE THREAD

**Issue by Chemist94** [Rughalt/D35E#77]
Special enhancements like Fortification adds +bonuses to AC (or attack and damage in case of weapons), while they shouldn't. +bonus in the description of such enhancements only used for determining cost and enhancements limit, but not added as real bonus to AC/Attack/Damage. So item can have maximum +5 regular enhancement bonus and +5 special effects, with a total if +10, but will have only +5 to AC/Attack/Damage.

**Comment by Rughalt** [comment]
Adding enhancement is indeed a bug but allowing higher enhancement bonuses uses Epic rules (so item can have more than +5 base enhancement).
