### ISSUE TITLE
Kobold in the race compendium -2 charisma instead of constitution

### ISSUE THREAD

**Issue by Tanky06** [Rughalt/D35E#770]
Kobold in the race compendium -2 charisma instead of constitution

![image](https://user-images.githubusercontent.com/84699607/133514466-9bc85d5c-ef23-425a-b696-574dba25cd24.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.96.4

**Comment by K484L-v1** [comment]
![immagine](https://user-images.githubusercontent.com/87317002/133643905-885b2262-0127-4ae5-8232-9f24efcf605a.png)

-4 Strength, +2 Dexterity, -2 Constitution.

Small size: +1 bonus to Armor Class, +1 bonus on attack rolls, +4 bonus on Hide checks, -4 penalty on grapple checks, lifting and carrying limits ¾ those of Medium characters.

A kobold’s base land speed is 30 feet.

Darkvision out to 60 feet.

Racial Skills: A kobold character has a +2 racial bonus on Craft (trapmaking), Profession (miner), and Search checks.

Racial Feats: A kobold character gains feats according to its character class.

+1 natural armor bonus.

Special Qualities: Light sensitivity.

Automatic Languages: Draconic. Bonus Languages: Common, Undercommon.

Level adjustment +0.

**Comment by Tanky06** [comment]
Specific Skill Craft, Hide and Profession is missing

**Comment by Rughalt** [comment]
I think this was fixed where possible i 0.96.4
