### ISSUE TITLE
Bug: Named feats break with Babele translations

### ISSUE THREAD

**Issue by irbian** [Rughalt/D35E#774]
Several things here check for feat name, but they are broken due babele translations

https://github.com/Rughalt/D35E/blob/master/module/item/entity.js#L2022

Maybe it would be better if here checks by some kind of id or something

**Comment by irbian** [comment]
Looks like things like    "maxFormula":"@classes.bard.level" break too

**Comment by Rughalt** [comment]
Added a special tag based on original name that is left by babele - it should fix both of those things. All new feats are programmed in a way that is unaffected by name change.
