### ISSUE TITLE
Aura bug

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#777]
today we were lagging a lot and discover that the aura the bard was using was dupplicating 100 times and incrasing.  we removed the Aura and reloader many time and it finally removed.  The bug was on other player than the bard, that was receiving the bard inspiration to get bonus.  Each feat had also 100x the bonus given by the song.

**Comment by Rughalt** [comment]
One possible culprit in `Monk's TokenBar` but i cannot reproduce it. Please try with modules off and then see what module breaks the aura's.
