### ISSUE TITLE
Spell Focus (or anything using featSpellDCBonus) causes DC in spell description to keep incrementing

### ISSUE THREAD

**Issue by skepickle** [Rughalt/D35E#785]
Foundry Virtual Tabletop 0.8.9
3.5e SRD 0.96.4

I'm seeing the incorrect DC being shown in expanded spell descriptions in character sheets for any character that has a feat that uses featSpellDCBonus. This behavior used to also show up in the Chat Log, but that seems to have been fixed already.

Steps to recreate:
1) Create spellcaster
2) Add Spell Focus feat, and assign a school.
3) Find a spell in the spellcaster's list, and expand the description by left-clicking on the spell name.
4) See that the DC is wrong.
5) Left-click on the spell name to close the description, and then click on it again to expand again.
6) See that not only is the DC wrong, but is 1 higher than the first time you looked.
7) Repeat steps 5-6 and see the DC keep going up.

**Comment by Rughalt** [comment]
Fixed, will be out in 0.99
