### ISSUE TITLE
Although you cancel casting a spell, the spells per day counter changes.

### ISSUE THREAD

**Issue by ilore** [Rughalt/D35E#788]
As you can see in the images, when you cancel the casting of a spell, the spells per day counter understands that you have casted it.

![bug1](https://user-images.githubusercontent.com/32924279/136945830-2391db10-c2e9-4eb8-8908-f7dae7b38be6.jpg)
![bug2](https://user-images.githubusercontent.com/32924279/136945844-09a9c540-efd5-4ca1-97db-51da2bf5da68.jpg)
![bug3](https://user-images.githubusercontent.com/32924279/136945855-3696d60c-a914-413d-ac18-edbdde2642fd.jpg)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.98
