### ISSUE TITLE
You must edit every new spell added to character sheet in order to activate the automatic template.

### ISSUE THREAD

**Issue by ilore** [Rughalt/D35E#789]
In the first picture, I have dragged a new spell from the compendium to the character sheet spellbook:

![B1](https://user-images.githubusercontent.com/32924279/136950671-4aac704d-8662-47cb-8e5d-001e151f1343.jpg)

In the second picture, I have pushed the action button (the black button with the white sword) to launch the spell. As you can see, in the cast window, under the "Miscellaneous" section there is nothing:

![B2](https://user-images.githubusercontent.com/32924279/136950913-b68463e0-1f6d-4d21-93fe-c980af4eb432.jpg)

In the third picture, I have opened the edit spell window. As you can see, in the "measure template" section, _Override color_ and 
_Override texture_ are unchecked:

![B3](https://user-images.githubusercontent.com/32924279/136951164-6112e586-5cbb-425a-b784-b671f93a74b5.jpg)

In the fourth image, I have checked "override color". I could have checked "override texture" instead, because I already have tested that the effect is the same with both:

![B4](https://user-images.githubusercontent.com/32924279/136951550-989f803c-8f5e-4fdb-9125-ca4c7bf50c41.jpg)

In the fifth image, I have unchecked "override color" again, in order to not change anything in the spell configuration:

![B5](https://user-images.githubusercontent.com/32924279/136951685-b315a792-0850-4a0c-966a-0392fa990045.jpg)

As you can see in the sixth image, when I try to cast the spell again, now in the "miscellaneous" section the "measure template" appears:

![B6](https://user-images.githubusercontent.com/32924279/136952119-ec9c78f8-9883-4e77-88e0-b5b750e6f9c6.jpg)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.98.0
