### ISSUE TITLE
Bonus Arcane Spellcaster Level not working

### ISSUE THREAD

**Issue by RafaelFett** [Rughalt/D35E#790]
When creating a class, on the configuration, special features, adding Bonus Arcane Spellcaster don't work.

![image](https://user-images.githubusercontent.com/62724675/137582907-64fb683e-940f-44d7-a7a5-d704aadcde56.png)

**Comment by Rughalt** [comment]
Hi! I cannot reproduce this. Are you sure that the feature was added correctly?
![image](https://user-images.githubusercontent.com/802214/139596862-34ba0476-5c2e-496e-a028-ab0e07de1e01.png)

**Comment by RafaelFett** [comment]
You are right, it's not about the arcane spellcast, is about a checkbox.
![image](https://user-images.githubusercontent.com/62724675/139597284-a1dfe090-a0cb-4db2-96d1-dba0702bc097.png)
This was unchecked, sorry the false alarm, thanks as always for the hard work.
