### ISSUE TITLE
Level tiles overlap section below when width decreased

### ISSUE THREAD

**Issue by agrtga** [Rughalt/D35E#792]
The level tiles on the Features-Classes tab will overlap onto the class section below it if the form width is decreased to the point where the number of tiles in a row cannot display at least 13. This problem is illustrated in the attached screen clip.

The section with the tiles should grow dynamically, or the minimum width of the form should be increased to prevent it.
<img width="393" alt="vtt-tile-overlap" src="https://user-images.githubusercontent.com/12749451/137591683-941522d3-8ae4-4ab9-a7a2-010728352a9e.png">
.

**Comment by Rughalt** [comment]
Fixed, will be out in 0.99. Additionally corrected behaviour when amount of levels is over 26
