### ISSUE TITLE
Magic Item with use per day or unlimited use not working

### ISSUE THREAD

**Issue by Quasimojo82** [Rughalt/D35E#794]
Created a magic item that has multiple spells at different caster levels, some a certain amount of use per day like the Cure Light Wounds, and some that are supposed to be unlimited at will use like Dancing Lights. The cure light works based on the action button, and subtracts the uses from the per day total, but rolls only 1d8 instead of 1d8+5. The Halt Undead action button does nothing, not even putting a description in the chat window. The Flare spell works but subtracts a charge and only works once. 

Item is equipped on the character sheet as can be seen in the one screenshot with the screenshot of the item as the other. 

![image](https://user-images.githubusercontent.com/92641155/137594055-18659ad7-2560-46e4-9027-5a511dba709a.png)
![image](https://user-images.githubusercontent.com/92641155/137594066-5fdc3d44-7312-464a-a84b-d05160f97060.png)

**Comment by Quasimojo82** [comment]
Not sure if it is related or a separate issue, but as another example, the Gauntlet of Rust does not update the charges when you click the action button for the Rusting Grasp spell. It displays the spell text in chat and the item remains at 1 charge. I also tried checking off the common uses pool checkbox and that did not update it either.

**Comment by Rughalt** [comment]
Fixed, will be out in 0.98
