### ISSUE TITLE
FR: link feats to items

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#799]
Drunva asked:
![image](https://user-images.githubusercontent.com/55966777/138568825-4b7cede8-bb34-4837-bab5-8e17fbc13cd1.png)

this could be solved by simply allowing links to feats on an items enhancements tab, perhaps.
![image](https://user-images.githubusercontent.com/55966777/138568845-e2d07902-1594-4412-bfdb-2cc9625020b9.png)

i presume this would add a "Feats" header to the  Magic Item Updates section (after Basic enhancements, Buffs, Spell Uses)?
![image](https://user-images.githubusercontent.com/55966777/138568919-dd7c68af-e151-42ea-b66e-701469a0f2d4.png)

this would make it possible to create metamagic rods from the SRD, although i expect trying to have limitations of uses of the feat will have to be left to the GM without significant additional coding.
(https://www.d20srd.org/srd/magicItems/rods.htm#metamagicRods)

**Comment by Rughalt** [comment]
![image](https://user-images.githubusercontent.com/802214/139595915-edffca1f-dcee-441e-9443-71062b4d7e42.png)
