### ISSUE TITLE
Bug: Some weapons don´t do damage 

### ISSUE THREAD

**Issue by irbian** [Rughalt/D35E#803]
On the SRD, only the net https://www.d20srd.org/srd/equipment/weapons.htm

**Comment by Rughalt** [comment]
Added ability to add effect notes to the weapon, and doing that and setting damage to 0 will make the weapon do no damage. It will roll attack normally and display effect in chat card. The Net in the compendium is updated.
![image](https://user-images.githubusercontent.com/802214/140616222-d796f698-0760-4085-a3ef-8d6e40a5a8ee.png)
![image](https://user-images.githubusercontent.com/802214/140616228-809b47be-da50-4ee0-b330-c4934bfad627.png)
