### ISSUE TITLE
When you edit a buff, you can't see the descrition text unless you push the edit text button.

### ISSUE THREAD

**Issue by ilore** [Rughalt/D35E#804]
When you drag and drop a Buff into a character sheet and push on it, you can see the descriptive text:

![weird](https://user-images.githubusercontent.com/32924279/139664830-42c01965-d628-49c1-bfd8-67c5b96577ed.jpg)

But, when you edit the Buff, the text in the descrition tab is empty:

![Weird-2](https://user-images.githubusercontent.com/32924279/139664905-36a0f6e7-fe1b-444a-b763-47be08bf0c3a.jpg)

However, If you push the edit text button, you can see the text:

![Weird-3](https://user-images.githubusercontent.com/32924279/139664954-f13520ef-97ce-48f0-9bcb-6eeacea35cb2.jpg)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.98
