### ISSUE TITLE
Feature request: Add @item.level variable to combat changes modification formula

### ISSUE THREAD

**Issue by cilvet** [Rughalt/D35E#805]
This doesn't work: 
<img width="540" alt="Captura de pantalla 2021-11-01 a las 18 30 19" src="https://user-images.githubusercontent.com/14343618/139714221-c53acc91-99e3-4058-8815-12ea98e3389f.png">

This works: 
<img width="533" alt="Captura de pantalla 2021-11-01 a las 18 30 55" src="https://user-images.githubusercontent.com/14343618/139714308-9f5e0e3b-7f9e-40aa-b59c-1f75aae487a3.png">

**Comment by Rughalt** [comment]
Added as `@source.level` to as `@item.level` already points to a level if item that is being used, not the one that is providing special action.
