### ISSUE TITLE
Bug: Special actions can't activate auras

### ISSUE THREAD

**Issue by cilvet** [Rughalt/D35E#812]
Auras can be created from compedium with:
` Create unique "Generic aura 1" from D35E.common-auras on self`
An aura's level can be set with:
` Set aura "Generic aura 1" field data.level to 1 on self`
however, activating an aura with a special action doesn't seem to work:
`Activate aura "Generic aura 1" on self;`

Steps to reproduce: 
- import the items in the first comment into world
- unlock the System's Common auras compedium and add "Generic aura 1" to it (I know this is not a good practice, but it's good enough for this test)
- add "Generic feat 1" to a character
- Activate "Generic feat 1"

**Comment by cilvet** [comment]
[zipped_json.zip](https://github.com/Rughalt/D35E/files/7467336/zipped_json.zip)

**Comment by Rughalt** [comment]
Added ability for special actions to activate auras
