### ISSUE TITLE
Bug: Templates increase base feats as though they added hit dice

### ISSUE THREAD

**Issue by Zazmul1** [Rughalt/D35E#813]
When a template is added to a monster/NPC, it increases the number of feats they have in their base feat pools as though they had twice as many hit dice. Probably due to the program counting "levels" in the template as HD. 
![image](https://user-images.githubusercontent.com/93670391/140102607-8d9c3f4e-76cb-4bb8-ac68-a9011c946654.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.98
