### ISSUE TITLE
Resistances applying before a saving throw

### ISSUE THREAD

**Issue by Quasimojo82** [Rughalt/D35E#814]
Resist energy needs to apply after the save and it appears it is applying before the save. Resist energy itself is applied to the character correctly and subtracts the correct amount of damage, but this happens prior to the saving throw for the spell, when given that option. In the example below, the NPC has fire resist 20, makes the save, and still takes 4 damage because it is subtracting the 20 fire damage from the 28 total before then applying the full or half damage from the save.
![image](https://user-images.githubusercontent.com/92641155/140613862-8d9c2db0-de04-4644-82c9-28e0c9fc8d88.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.98
![image](https://user-images.githubusercontent.com/802214/140615445-42a56776-a53a-4b02-b6ff-6441457937a8.png)
