### ISSUE TITLE
Bug: Missing Bonus Skill Points

### ISSUE THREAD

**Issue by RinVindor** [Rughalt/D35E#819]
My players making characters and not using the Progression tools discovered that adding the Human race does not affect available Skill Points.

**Comment by wmve** [comment]
following screenshot shows 1st lvl human fighter (nothing else defined) with only 8 skill points

<img width="534" alt="SNAG-0774" src="https://user-images.githubusercontent.com/55966777/140675525-a033f4a8-7c8e-44c6-ab82-1fd51b099b9f.png">

should be 12 points

**Comment by Rughalt** [comment]
Added, will automatically add item bonus skill points to the list.
