### ISSUE TITLE
use token character pic instead of primary pic for party HUD thumbnails

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#821]
Party HUD thumbnails often look awkward because they are centered on pics that don't have a face, for example, in the center.

![image](https://user-images.githubusercontent.com/55966777/140841287-14b3189a-47a2-457a-a924-2b47955700a5.png)

(alternately, having a selectable crop would be nice, but since the Party HUD thumbnails are round, and token pics are usually selected to fit in a square, they fit each other well and using the token pics would be less work).

**Comment by Rughalt** [comment]
Fixed, added client-side option to toggle the setting.
