### ISSUE TITLE
Caster level of wands doesn't work

### ISSUE THREAD

**Issue by Jarlok2** [Rughalt/D35E#827]
When you take a spell (for example Magic Missile) and drag to the inventory, you can select a wand to create it and you choose the caster level but the wand doesn't work properly. You have to change the @cl in the details of the wand, you have to choose a "Distance attack spell" and put the real level number instead "@cl" and then works.

**Comment by Rughalt** [comment]
Fixed, now newly created consumables have "isFromSpell" toggled and will follorCL set inside when rolling number of attacks.
