### ISSUE TITLE
FR: Popout chat messages

### ISSUE THREAD

**Issue by BlackWand1** [Rughalt/D35E#829]
Hi!

I know we talked about this on Discord a while back. But Foundry supports "right click" on chat messages and they should pop out as its own windows. But the system must implement this.

It would be awesome to have this functionality. Currently the attack card, lets say "magic missile" has 5 attacks, for each attack I apply, new chat cards is added to the chat and the "attack card" is slowly moved up in the chat window. Until you have to lots of scrolling backwards ;)

If one could right click and op them out, i could keep it and close it once all attacks has been applied.

Cheers

**Comment by Rughalt** [comment]
Added, will be out in 0.99
![image](https://user-images.githubusercontent.com/802214/142252788-bbf7624c-b31d-46db-b8ad-aaaf18dbd1bb.png)
