### ISSUE TITLE
FR: Collapsible containers

### ISSUE THREAD

**Issue by BlackWand1** [Rughalt/D35E#830]
Would be awesome if these containers would be collapsible. To minimize the "size" of the inventory.

![image](https://user-images.githubusercontent.com/85252943/141362843-4c0ec4c3-270a-4f18-98b6-cb99e6e68fac.png)

**Comment by BlackWand1** [comment]
If you want to go hardcore. Allow some kind of filter, that would automatically move items matching that filter into the container.

Like:
item.type=scroll
item.level=7
=move into this scroll case for lvl 7 spells.

**Comment by Rughalt** [comment]
Ability to collapse containers added.
> If you want to go hardcore. Allow some kind of filter, that would automatically move items matching that filter into the container. (...)
Please move this into a separate ticket

**Comment by Rughalt** [comment]
Moved action button to another ticket
