### ISSUE TITLE
[Bug] Spell Card Actions not working.

### ISSUE THREAD

**Issue by Gritakthegoblin** [Rughalt/D35E#838]
Hello, it's me a wild goblin. I've recently updated to the latest version of 3.5e SRD being 0.98.0, and I'm running into an issue that was not there before updating. Whenever I attempt to activate the action of a spell card, I receive this error.
![Screenshot 2021-11-16 231548](https://user-images.githubusercontent.com/77771375/142145682-66b0eb75-db14-483c-bd41-418dff7fc896.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.99
