### ISSUE TITLE
Skill Focus does not appear to add to Skill score

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#846]
steps to reproduce
- create new npc
- add feat Skill Focus
- set custom prop as shown

![image](https://user-images.githubusercontent.com/55966777/143623255-5a55d4be-078c-44f3-8de6-241b1e777a24.png)

expected behaviour: highlighted blue number for Appraise will be 3
actual behaviour: highlighted blue number for Appraise is 0 (unchanged)

**Comment by Rughalt** [comment]
Fixed in version 0.98.8 along with change on how Skill Focus works
