### ISSUE TITLE
[Bug] Hook `dropActorSheetData` is not invoked. ActorSheetPF `_onDrop` doesn't call super method from base Foundry ActorSheet

### ISSUE THREAD

**Issue by typhonrt** [Rughalt/D35E#847]
Greets,

An issue was filed against Forien's Quest Log about drag & drop functionality relating to dropping rewards / items onto the D35E actor sheet. I looked into it and it appears that ActorSheetPF `_onDrop` doesn't invoke the super method `_onDrop` on the base Foundry ActorSheet so the `dropActorSheetData` hook is never fired. Any module relying on the `dropActorSheetData` hook including the quest log will have broken functionality. 

Suggestion: If possible invoke the `super._onDrop` so the hooks fire or explicitly invoke the same hooks in your fully overridden `_onDrop`. 

Thanks again for all your work! 

See: https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues/5

**Comment by Rughalt** [comment]
I moved the functions to separate overrides and left _onDrop alone - this seems to keep all functionality and fix this issue. Thanks for reporting.
