### ISSUE TITLE
Actor sheet not opening after update to Version 0.98.1

### ISSUE THREAD

**Issue by ilDade4** [Rughalt/D35E#850]
Hello, 
my actor sheet are not opening after last update; also recreating does not allow to pull up character sheets

EDIT:  I think that the issues reside in the Default sheet that is no more working

**Comment by ilDade4** [comment]
Attaching 2 example actors  (rename file in .json as it was not letting me attach it) 

[fvtt-Actor-capitano-della-regina-dei-mari.txt](https://github.com/Rughalt/D35E/files/7620611/fvtt-Actor-capitano-della-regina-dei-mari.txt)

[fvtt-Actor-sead.txt](https://github.com/Rughalt/D35E/files/7620610/fvtt-Actor-sead.txt)

**Comment by ilDade4** [comment]
I think that the update somehow broke the Default sheet or the link within the actors , the problem should be there

**Comment by Rughalt** [comment]
Thanks, I will fix ASAP.

**Comment by Rughalt** [comment]
I cannot reproduce it locally, a screenshot of console (F12) would help a lot! Thanks

**Comment by ilDade4** [comment]
No man, thank you for your amazing work!

**Comment by ilDade4** [comment]
![Error_foundry](https://user-images.githubusercontent.com/95247585/143935069-2e247095-964f-42f6-8c42-740c7bae31ad.JPG)

**Comment by ilDade4** [comment]
I see that also the Compendium Pack shows empty now (no  error in console is shown for it), and some of the items that I created duplicating other items 


Error: No data was returned from template systems/D35E/templates/items//equipment.html
[No packages detected]
    at ItemSheetPF._renderInner (foundry.js:2221)
    at async ItemSheetPF._renderInner (foundry.js:2747)
    at async ItemSheetPF._render (foundry.js:2055)
    at async ItemSheetPF._render (foundry.js:2736)


I see that in fact the systems\D35E\templates folder is empty now, let me know if is enough for me to restore it from a backup or if you want to keep it like that for some time to further troubleshoot the issue

**Comment by Rughalt** [comment]
This looks like install related issue. It would be great if you could reach me on discord to troubleshoot!

**Comment by ilDade4** [comment]
Could  it be that I dont use the default user data path for the installation? 

 yes I can join discord, I have no headset on this PC but I can share screen or provide the data you need.

thanks again for the help

**Comment by Rughalt** [comment]
Headset is not needed, but text chat on discord is way easier.

**Comment by Axecleft** [comment]
I had the same issue a couple of months back. I thought it was from an update but it turned out to be that I had tried to enter a formula in the auto health setting. That caused the sheet to error every time I loaded one.

![image](https://user-images.githubusercontent.com/73614995/143965203-570f3ad8-7750-4fde-8027-5e3de9884e2f.png)
