### ISSUE TITLE
standard Weapon Focus feat does not have attributes locked

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#856]
open weapon focus from D35E Feats compendium.
it looks like this:

![image](https://user-images.githubusercontent.com/55966777/145227832-c6b67683-1513-47bf-9403-4a249719cf95.png)

uninitiated users may accidentally set the name of the attribute instead of the value.
suggest for robustness that we lock the attribute on that feat in the feats compendium

**Comment by Rughalt** [comment]
Changed the way this is set up and locked. Will be out in 0.99.
