### ISSUE TITLE
stock Unarmed Strike item has quantity 0

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#857]
...which causes created attacks to be disabled until you change the quantity to 1

steps to recreate:
- create new character
- add unarmed strike item
![image](https://user-images.githubusercontent.com/55966777/145321450-0b655756-4e35-44fd-aa3b-f4bd8927ccaa.png)
- create attack from unarmed strike
- examine combat tab
![image](https://user-images.githubusercontent.com/55966777/145321413-ceb8a03a-475c-41a3-a8c9-471d254bfbca.png)
expected result: unarmed strike is available
actual result: unarmed strike is listed but struck out

go back, check on unarmed strike item 
![image](https://user-images.githubusercontent.com/55966777/145321501-ec0a2eb6-9e71-4004-bad6-4873095d01c2.png)

so it appears that the default unarmed strike item has quantity 0

**Comment by Rughalt** [comment]
Fixed, will be out in 0.99
