### ISSUE TITLE
[Bug] Ranged attack penalty affecting 'Melee Attack Bonuses'

### ISSUE THREAD

**Issue by Gritakthegoblin** [Rughalt/D35E#860]
Hello, it's me a wild goblin. For some reason, a miscellaneous feature that I've made as the flaw 'Shaky' from the Unearthed Arcana Handbook. Is not correctly penalizing only ranged attacks, as I have it set to. Now, this does not affect melee attacks from weapons. However, it is strangely penalizing the combat tabs 'Melee attack bonuses'.

![Screenshot 2021-12-09 045829](https://user-images.githubusercontent.com/77771375/145393765-c18cc37c-9b3e-4b42-976f-1928bc6a05f4.png)
![Screenshot 2021-12-09 045814](https://user-images.githubusercontent.com/77771375/145393770-4d77bde6-2fc5-47bc-983d-56d91dc3473b.png)
![Screenshot 2021-12-09 045721](https://user-images.githubusercontent.com/77771375/145393771-b51e0b74-69ba-4805-a31a-3c4e9b1106b0.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.99
