### ISSUE TITLE
Animal Companion Level Issue

### ISSUE THREAD

**Issue by bizzar0helldemon** [Rughalt/D35E#862]
The Animal Companion Class feature is having a bug when it is telling the Class Animal Companion how to determine it's level. 

This first image will show case the issue at hand. The druid is level 6 but his animal companion is only level 5. 
![image](https://user-images.githubusercontent.com/96044517/145772696-d9696412-52c8-42c7-9221-31ac17c925f2.png)

The Ranger formula works until you hit level 12  
![image](https://user-images.githubusercontent.com/96044517/145773505-8ab70297-fb31-4eb2-b415-bb9535fb30a2.png)

![image](https://user-images.githubusercontent.com/96044517/145771907-fa2d28d6-fcbf-4408-8efa-9d057a001041.png)
The above imagine is the Default Ranger Minion Class Level Formula

![image](https://user-images.githubusercontent.com/96044517/145772021-45f63e1a-b9eb-43e3-891a-e2e2114d1c8c.png)
The above image is the Default Druid Minion Class Level Formula 

https://www.d20srd.org/srd/classes/druid.htm 
![image](https://user-images.githubusercontent.com/96044517/145772357-ae8cf19d-c51d-41ed-a186-6b14446c8e37.png)

https://www.d20srd.org/srd/classes/ranger.htm 
![image](https://user-images.githubusercontent.com/96044517/145772320-ab76684b-c9bb-4916-8d99-dd94fcd6d451.png)

![image](https://user-images.githubusercontent.com/96044517/145772443-755aac8d-c0ec-44ea-b5fb-57c831ddb88e.png)
The above is the fixed formula for Druid

![image](https://user-images.githubusercontent.com/96044517/145772514-8b3caedb-bbd8-4bba-aae1-0b86c0f1824c.png)
The above is the fixed formula for Rangers

**Comment by Rughalt** [comment]
I cannot reproduce the bug. The minion updates correctly (it takes some time as this needs to run an update loop over the minion actor *after* the base actor is changed. Usually opening class details on the owner of the minion fixes the problem (system does not try to always forcefully update the minion)
