### ISSUE TITLE
[Bug] Attacks no longer working with latest update.

### ISSUE THREAD

**Issue by Gritakthegoblin** [Rughalt/D35E#864]
Hello this is a wild goblin. The title says it all. Pre and Post update character sheets can't attack anymore.

![Screenshot 2021-12-13 153135](https://user-images.githubusercontent.com/77771375/145900485-0cce11af-f0eb-4c66-beae-457a1320a148.png)

**Comment by Axecleft** [comment]
I can confirm this:

![image](https://user-images.githubusercontent.com/73614995/145901278-e4e422c6-643c-48f8-9809-4842c3a88a21.png)

**Comment by Rughalt** [comment]
This should be fixed as of 0.98.9
