### ISSUE TITLE
weight value changed on item after dragging to character sheet

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#865]
steps to reproduce:

1. define an item with weight .05 (which is the weight of a standard coin)
2. set quantity to 1200 (note total weight 600)
3. drag to character sheet
expected behaviour:
actual behaviour: observed weight on item is 1200.  on further inspection the item "each" weight has been changed from .05 to .1

probably a rounding error in some math somewhere.  if so please round off only after something like the nearest hundredth.  (i know, sometimes those floating point precision errors creep in and add or subtract some very small portion, and you're probably trying to keep that from happening)

left: copy of item in items directory, before drag operation
right: copy of item on character sheet after dragging from item directory
![image](https://user-images.githubusercontent.com/55966777/146039042-444a6cfa-0cfd-4cea-a47b-568736304486.png)

**Comment by wmve** [comment]
yes, i know there are other ways of tracking coins.  i need to keep this loot separate.  also, figuring out if the PCs could even carry them all is an issue.  if some of them die/disappear i need to know where it all is and how much they have left, as they're frightfully short of money.

**Comment by Rughalt** [comment]
This turned out to be an issue to weight change for items when dropped to a Large character - their weight was adjusted. To fix that, *const weight* tickbox should be used.
