### ISSUE TITLE
Issue: Compendium Browsers are not working in core v9 and SRD v0.98.9

### ISSUE THREAD

**Issue by Axecleft** [Rughalt/D35E#879]
The Browse (Compendium name here) buttons are showing blank listings. with the latest update.

This does not generate an error in the console log.

![image](https://user-images.githubusercontent.com/73614995/147514285-fbfb1e05-e92a-49e0-b08f-339b05b3fc56.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.99
