### ISSUE TITLE
Token Resize not working in Buff

### ISSUE THREAD

**Issue by Eldintux** [Rughalt/D35E#885]
Buffs with token size changes don't seem to work. I'll put a picture of an enlarge buff I created for my Cleric. Has been absolutely fine. Upgraded to v9 yesterday now the Buff appears on the character sheet but nothing applies. I normally apply through a special action but even manually applying doesn't seem to work. In fact the updating symbol comes on & doesn't go away until I refresh. Once the buff is on the actor it can't be opened for editing either but can be it in a compendium or in the side bar. If I take the token resize off the buff applies as expected from special action or manual in all respects. Foundry V9.238 3.5ed 0.98.9 all modules removed.
![Screenshot from 2021-12-31 18-20-42](https://user-images.githubusercontent.com/75202428/147835541-217bd8ee-3a29-487c-b22e-de1467055243.png)

**Comment by Rughalt** [comment]
Fixed, will be out in 0.99
