### ISSUE TITLE
FR: Add an "apply double damage" option to roll defense windows.

### ISSUE THREAD

**Issue by ilore** [Rughalt/D35E#905]
Some weapons can apply double damage in certain circumstances. For example, spears and longspears deal double damage against charging enemies. So, it could be helpful with that kind of weapons adding an "apply double damage" option to "roll defense" windows.

**Comment by Axecleft** [comment]
There is no limit to how many times the damage of an attack can be applied. In the case of double or even triple damage the GM simply need to hit the apply button more than once.

**Comment by ilore** [comment]
> There is no limit to how many times the damage of an attack can be applied. In the case of double or even triple damage the GM simply need to hit the apply button more than once.

Hummm... yeah, maybe doing that is simpler than creating new buttons... good point!
