### ISSUE TITLE
Reducing the width of a character sheet makes Level Progression levels 25 and 26 go out of bounds

### ISSUE THREAD

**Issue by omegaghost** [Rughalt/D35E#98]
![image](https://user-images.githubusercontent.com/7759628/97242847-f89eec80-1805-11eb-8888-2667d608ff2f.png)

**Comment by Rughalt** [comment]
This is very hard to fix, as this breaks all flow (real levels are rendered differently than "placeholders"). I will probably disable ability to shrink character chard below certain size if I do not find correct way to deal with it.

**Comment by Axecleft** [comment]
What about grouping level progression into Campaign and Epic groups. Levels 1-20 are Campaign and Levels 21_40 Epic with a check box to flip display.

**Comment by Rughalt** [comment]
The character sheet can no longer be narrow enough so the fields overlap.
